Repository kuzzleio/kuzzle, pull requests merged in 2018-07, with the labels that each got.

#1145 deprecate "constructor" auth option and replace it with "authenticator"
  lib/api/core/plugins/pluginContext.js
  lib/api/core/plugins/pluginsManager.js
  test/api/core/pluginContext/pluginContext.test.js
  test/api/core/pluginsManager/strategy.test.js
Labels: changelog:enhancements

#1143 Add action and controller in request input for http events
  lib/api/controllers/routerController.js
  lib/api/core/httpRouter/index.js
  test/api/controllers/routerController/httpRequest.test.js
  test/api/core/httpRouter/httpRouter.test.js
Labels: changelog:bug-fixes

#1147 Test Kuzzle against different node LTS versions
  docker-compose/dev.yml
  docker-compose/scripts/run-test.sh
  docker-compose/test.yml
  test/travis-bin/run-tests.sh
Labels: changelog:enhancements

#1148 set ulimits for elasticsearch
  docker-compose/dev.yml
  docker-compose/test.yml
Labels: changelog:exclude

#1150 Update kuzzle-common-objects module
  package-lock.json
  package.json
  test/api/controllers/routerController/routerController.test.js
  test/api/core/hotelClerk/removeCustomerFromAllRooms.test.js
  test/services/implementations/broker.test.js
Labels: changelog:exclude

#1154 Prevent a crash when using pre-1.4.0 configuration files
  .kuzzlerc.sample
  default.config.js
  lib/services/index.js
Labels: changelog:bug-fixes

#1155 Inject protocol informations into the RequestContext object
  lib/api/controllers/funnelController.js
  lib/api/controllers/realtimeController.js
  lib/api/controllers/routerController.js
  lib/api/core/auth/tokenManager.js
  lib/api/core/entrypoints/embedded/index.js
  lib/api/core/entrypoints/embedded/protocols/http.js
  lib/api/core/entrypoints/embedded/protocols/socketio.js
  lib/api/core/entrypoints/embedded/protocols/websocket.js
  lib/api/core/entrypoints/proxy/index.js
  lib/api/core/hotelClerk.js
  lib/api/core/httpRouter/routeHandler.js
  lib/api/core/httpRouter/routePart.js
  lib/api/core/models/notifications/DocumentNotification.js
  lib/api/core/models/notifications/UserNotification.js
  lib/api/core/models/repositories/tokenRepository.js
  lib/api/core/statistics.js
  package-lock.json
  package.json
  test/api/controllers/routerController/routerController.test.js
  test/api/core/entrypoints/embedded/index.test.js
  test/api/core/entrypoints/embedded/protocols/socketio.test.js
  test/api/core/entrypoints/embedded/protocols/websocket.test.js
  test/api/core/hotelClerk/removeCustomerFromAllRooms.test.js
  test/api/core/hotelClerk/removeRoomForCustomer.test.js
  test/api/core/models/repositories/tokenRepository.test.js
  test/api/core/statistics.test.js
Labels: changelog:enhancements

#1159 Fix: authenticators are not registered when there is no strategies
  lib/api/core/plugins/pluginsManager.js
  package-lock.json
  package.json
  test/api/core/entrypoints/embedded/protocols/socketio.test.js
  test/api/core/entrypoints/embedded/protocols/websocket.test.js
  test/api/core/pluginsManager/strategy.test.js
Labels: changelog:bug-fixes

#1152 Add script to build and push docker images
  .travis.yml
  build-docker-images.sh
Labels: changelog:enhancements

#1162 Fix wrong ES version error message
  lib/services/elasticsearch.js
  lib/services/internalEngine/index.js
Labels: changelog:bug-fixes

#1163 Fix documentation URL in the startup message
  bin/README.md
  bin/commands/start.js
Labels: changelog:enhancements

#1164 Fix swagger invalid output format
  lib/api/core/swagger.js
Labels: changelog:bug-fixes

#1166 Release 1.4.2
  .kuzzlerc.sample
  .travis.yml
  bin/README.md
  bin/commands/start.js
  build-docker-images.sh
  default.config.js
  lib/api/controllers/authController.js
  lib/api/controllers/funnelController.js
  lib/api/controllers/realtimeController.js
  lib/api/controllers/routerController.js
  lib/api/core/auth/tokenManager.js
  lib/api/core/entrypoints/embedded/index.js
  lib/api/core/entrypoints/embedded/protocols/http.js
  lib/api/core/entrypoints/embedded/protocols/socketio.js
  lib/api/core/entrypoints/embedded/protocols/websocket.js
  lib/api/core/entrypoints/proxy/index.js
  lib/api/core/hotelClerk.js
  lib/api/core/httpRouter/routeHandler.js
  lib/api/core/httpRouter/routePart.js
  lib/api/core/models/notifications/DocumentNotification.js
  lib/api/core/models/notifications/UserNotification.js
  lib/api/core/models/repositories/tokenRepository.js
  lib/api/core/statistics.js
  lib/api/core/swagger.js
  lib/services/elasticsearch.js
  lib/services/index.js
  lib/services/internalEngine/index.js
  package-lock.json
  package.json
  test/api/controllers/routerController/routerController.test.js
  test/api/core/entrypoints/embedded/index.test.js
  test/api/core/entrypoints/embedded/protocols/http.test.js
  test/api/core/entrypoints/embedded/protocols/websocket.test.js
  test/api/core/hotelClerk/removeCustomerFromAllRooms.test.js
  test/api/core/hotelClerk/removeRoomForCustomer.test.js
  test/api/core/models/repositories/tokenRepository.test.js
  test/api/core/statistics.test.js
Labels: release
