Repository kuzzleio/kuzzle, pull requests merged in 2018-10, with the labels that each got.

#1202 remove dependency on elasticsearch for unit tests
  test/api/core/pluginsManager/run.test.js
  test/api/core/pluginsManager/trigger.test.js
Labels: changelog:bug-fixes

#1201 fixes #1200 - no access log with http:options
  lib/api/core/entrypoints/embedded/index.js
  lib/api/core/httpRouter/index.js
  package-lock.json
  test/api/core/entrypoints/embedded/index.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:bug-fixes

#1204 pipes can return a promise
  lib/api/core/plugins/pluginsManager.js
  package-lock.json
  test/api/core/pluginsManager/run.test.js
Labels: changelog:enhancements

#1203 Use local file to build kuzzle and plugin-dev images
  .travis.yml
  Dockerfile
  build-docker-images.sh
Labels: changelog:bug-fixes

#1205 Release 1.5.2
  .travis.yml
  Dockerfile
  build-docker-images.sh
  lib/api/controllers/adminController.js
  lib/api/core/entrypoints/embedded/index.js
  lib/api/core/httpRouter/index.js
  lib/api/core/janitor.js
  lib/api/core/plugins/pluginsManager.js
  package-lock.json
  package.json
  test/api/controllers/adminController.test.js
  test/api/core/entrypoints/embedded/index.test.js
  test/api/core/janitor.test.js
  test/api/core/pluginsManager/run.test.js
  test/api/core/pluginsManager/trigger.test.js
  test/mocks/kuzzle.mock.js
Labels: release

#1206 fix truncated object name in error messages
  lib/api/core/models/repositories/repository.js
  test/api/core/models/repositories/profileRepository.test.js
  test/api/core/models/repositories/repository.test.js
  test/api/core/models/repositories/userRepository.test.js
Labels: changelog:bug-fixes

#1207 [ci] Reduce Travis build duration using build stages
  .ci/config/pm2.json
  .ci/haproxy/haproxy.cfg
  .ci/haproxy/snakeoil.pem
  .ci/run-tests.sh
  .ci/scripts/docker-entrypoint.sh
  .ci/scripts/install-aarch64-deps.sh
  .ci/scripts/install-armhf-deps.sh
  .ci/scripts/install-plugins.sh
  .ci/scripts/run-test-arm.sh
  .ci/scripts/run-test.sh
  .ci/scripts/run.sh
  .ci/sonar.sh
  .ci/test-aarch64.yml
  .ci/test-armhf.yml
  .ci/test.yml
  .travis.yml
  package-lock.json
Labels: changelog:enhancements, priority-high

#1183 Kzl 443 arm
  .ci/config/pm2.json
  .ci/haproxy/haproxy.cfg
  .ci/haproxy/snakeoil.pem
  .ci/run-tests.sh
  .ci/scripts/docker-entrypoint.sh
  .ci/scripts/install-aarch64-deps.sh
  .ci/scripts/install-armhf-deps.sh
  .ci/scripts/install-plugins.sh
  .ci/scripts/run-test-arm.sh
  .ci/scripts/run-test.sh
  .ci/scripts/run.sh
  .ci/sonar.sh
  .ci/test-aarch64.yml
  .ci/test-armhf.yml
  .ci/test.yml
  .travis.yml
  lib/api/kuzzle.js
  package-lock.json
  package.json
  test/services/internalEngine/pluginBootstrap.test.js
  test/travis-bin/run-tests.sh
Labels: changelog:enhancements, changelog:optimizations

#1212 [ci] Disable SonarQube for community contributors
  .travis.yml
Labels: changelog:exclude

#1211 Add missing coma in .kuzzlerc.sample
  .kuzzlerc.sample
Labels: changelog:exclude

#1208 Fixes document.validate requiring an id
  lib/api/controllers/documentController.js
Labels: changelog:bug-fixes
