Repository kuzzleio/kuzzle, pull requests merged in 2018-02, with the labels that each got.

#1025 Allow plugins to attach PATCH verbs to their HTTP routes
  lib/api/core/entrypoints/embedded/protocols/http.js
  lib/api/core/httpRouter/index.js
  lib/api/core/plugins/pluginsManager.js
  test/api/core/entrypoints/embedded/protocols/http.test.js
  test/api/core/httpRouter/httpRouter.test.js
  test/api/core/pluginsManager/run.test.js
Labels: changelog:enhancements

#1026 Improve the database configuration documentation
  .kuzzlerc.sample
Labels: changelog:enhancements

#1029 Plugin instantiated requests should propagate volatile data
  lib/api/core/plugins/pluginContext.js
  test/api/controllers/securityController/users.test.js
  test/api/core/pluginContext/pluginContext.test.js
Labels: changelog:bug-fixes

#1034 Do not inject http headers into request's input args
  lib/api/core/httpRouter/index.js
  lib/api/core/httpRouter/routeHandler.js
  test/api/core/httpRouter/httpRouter.test.js
Labels: changelog:bug-fixes, changelog:enhancements

#1024 raise an error if the document is not active
  lib/services/elasticsearch.js
  test/services/implementations/elasticsearch.test.js
Labels: changelog:bug-fixes

#1033 catch any exception thrown inside an HTTP request scenario
  lib/api/core/httpRouter/index.js
  lib/api/core/httpRouter/routeHandler.js
  test/api/core/httpRouter/httpRouter.test.js
Labels: changelog:bug-fixes

#1042 force an index refresh after loading fixtures
  bin/commands/start.js
Labels: changelog:enhancements

#1039 Plugins bootstrap lock adjustements
  lib/services/internalEngine/pluginBootstrap.js
  test/services/internalEngine/pluginBootstrap.test.js
Labels: changelog:enhancements

#1041 Add validation for profile edition
  lib/api/core/models/security/profile.js
  test/api/core/models/security/profile.test.js
Labels: changelog:bug-fixes

#1040 fixes #1036 `callback is not a function`
  default.config.js
  lib/api/controllers/funnelController.js
  lib/api/core/plugins/pluginContext.js
  test/api/controllers/funnelController/executePluginRequest.test.js
  test/api/core/pluginContext/pluginContext.test.js
  test/api/core/pluginsManager/run.test.js
Labels: changelog:bug-fixes, need-documentation

#1014 Remove kuzzle from security object methods signatures
  lib/api/controllers/funnelController.js
  lib/api/controllers/securityController.js
  lib/api/core/hotelClerk.js
  lib/api/core/models/repositories/profileRepository.js
  lib/api/core/models/repositories/repository.js
  lib/api/core/models/repositories/roleRepository.js
  lib/api/core/models/repositories/userRepository.js
  lib/api/core/models/security/profile.js
  lib/api/core/models/security/role.js
  lib/api/core/models/security/user.js
  lib/config/index.js
  lib/services/elasticsearch.js
  lib/services/internalEngine/bootstrap.js
  test/api/controllers/funnelController/checkRights.test.js
  test/api/controllers/securityController/profiles.test.js
  test/api/controllers/securityController/roles.test.js
  test/api/controllers/securityController/users.test.js
  test/api/core/models/repositories/profileRepository.test.js
  test/api/core/models/repositories/repository.test.js
  test/api/core/models/repositories/roleRepository.test.js
  test/api/core/models/repositories/userRepository.test.js
  test/api/core/models/security/profile.test.js
  test/api/core/models/security/role.test.js
  test/api/core/models/security/user.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:enhancements

#1049 Improve docker build
  Dockerfile
  docker-compose/scripts/docker-entrypoint.sh
  docker-compose/scripts/run.sh
Labels: changelog:enhancements
