Repository kuzzleio/kuzzle, pull requests merged in 2018-06, with the labels that each got.

#1122 replace "npm --unsafe" with "npm --unsafe-perm"
  Dockerfile
  docker-compose/scripts/install-plugins.sh
  docker-compose/scripts/run-dev.sh
  docker-compose/scripts/run-test.sh
Labels: changelog:exclude

#1123 remove SIGPIPE from the list of abnormal termination signals
  lib/api/kuzzle.js
  test/api/kuzzle.test.js
Labels: changelog:bug-fixes

#1127 fixes #1124 - kuzzle info mapping mixed versions
  lib/api/core/indexCache.js
  lib/services/elasticsearch.js
  lib/services/internalEngine/index.js
  package-lock.json
  test/api/core/indexCache.test.js
  test/mocks/kuzzle.mock.js
  test/services/implementations/elasticsearch.test.js
Labels: changelog:bug-fixes

#1121 Keep Kuzzle metadata in document body
  lib/api/core/auth/formatProcessing.js
  lib/api/core/notifier.js
  lib/services/elasticsearch.js
  test/api/core/notifier/notifyDocumentReplace.test.js
  test/services/implementations/elasticsearch.test.js
Labels: changelog:new-features

#1126 Node.js v10 compatibility
  lib/api/core/entrypoints/embedded/index.js
  package-lock.json
  package.json
  test/.eslintrc.json
  test/api/cli/action.test.js
  test/api/cli/index.test.js
  test/api/controllers/authController.test.js
  test/api/controllers/collectionController.test.js
  test/api/controllers/indexController.test.js
  test/api/controllers/memoryStorageController.test.js
  test/api/controllers/realtimeController.test.js
  test/api/controllers/routerController/httpRequest.test.js
  test/api/controllers/securityController/createFirstAdmin.test.js
  test/api/controllers/securityController/credentials.test.js
  test/api/controllers/securityController/profiles.test.js
  test/api/controllers/securityController/roles.test.js
  test/api/controllers/securityController/users.test.js
  test/api/controllers/serverController.test.js
  test/api/core/entrypoints/embedded/index.test.js
  test/api/core/entrypoints/index.test.js
  test/api/core/hotelClerk/listSubscriptions.test.js
  test/api/core/hotelClerk/removeRooms.test.js
  test/api/core/indexCache.test.js
  test/api/core/models/repositories/pluginRepository.test.js
  test/api/core/models/repositories/profileRepository.test.js
  test/api/core/models/repositories/roleRepository.test.js
  test/api/core/models/repositories/tokenRepository.test.js
  test/api/core/models/security/profile.test.js
  test/api/core/models/security/user.test.js
  test/api/core/pluginContext/pluginContext.test.js
  test/api/core/pluginsManager/init.test.js
  test/api/core/pluginsManager/run.test.js
  test/api/core/pluginsManager/strategy.test.js
  test/api/core/pluginsManager/trigger.test.js
  test/api/core/statistics.test.js
  test/api/core/validation/init.test.js
  test/api/core/validation/types/geoShape.test.js
  test/api/core/validation/validate.test.js
  test/config/index.test.js
  test/mocks/kuzzle.mock.js
  test/mocks/plugins/pluginPackage.proto.mock.js
  test/services/garbageCollector.test.js
  test/services/implementations/broker.test.js
  test/services/implementations/elasticsearch.test.js
  test/services/redis.test.js
Labels: changelog:enhancements

#1130 Improve access logs performances
  .kuzzlerc.sample
  default.config.js
  docker-compose/dev.yml
  lib/api/core/entrypoints/embedded/index.js
  package-lock.json
  package.json
  test/api/core/entrypoints/embedded/index.test.js
Labels: changelog:enhancements

#1119 Allow internal cache hot reload
  features/kuzzle.feature
  features/step_definitions/elasticsearch.js
  features/support/api/apiBase.js
  features/support/api/http.js
  features/support/config.js
  lib/api/core/indexCache.js
  lib/services/elasticsearch.js
  lib/services/internalEngine/bootstrap.js
  package-lock.json
  protocols/.gitignore
  protocols/available/.gitignore
  protocols/enabled/.gitignore
  test/api/core/indexCache.test.js
  test/services/implementations/elasticsearch.test.js
  test/services/internalEngine/bootstrap.test.js
Labels: changelog:enhancements

#1132 Remove trailing whitespace
  features/support/world.js
  lib/api/controllers/cli/cleanDb.js
  lib/api/controllers/cli/dump.js
  lib/api/controllers/collectionController.js
  lib/api/controllers/documentController.js
  lib/api/controllers/funnelController.js
  lib/api/controllers/routerController.js
  lib/api/controllers/securityController.js
  lib/api/core/auth/passportWrapper.js
  lib/api/core/auth/tokenManager.js
  lib/api/core/entrypoints/embedded/context.js
  lib/api/core/hotelClerk.js
  lib/api/core/models/repositories/repository.js
  lib/api/core/models/repositories/tokenRepository.js
  lib/api/core/plugins/pluginContext.js
  lib/api/core/plugins/pluginsManager.js
  lib/api/core/statistics.js
  lib/api/core/validation/baseType.js
  lib/api/core/validation/index.js
  lib/api/core/validation/types/date.js
  lib/api/core/validation/types/email.js
  lib/api/core/validation/types/enum.js
  lib/api/core/validation/types/geoPoint.js
  lib/api/core/validation/types/geoShape.js
  lib/api/core/validation/types/integer.js
  lib/api/core/validation/types/ipAddress.js
  lib/api/core/validation/types/numeric.js
  lib/api/core/validation/types/object.js
  lib/api/core/validation/types/string.js
  lib/api/core/validation/types/url.js
  lib/services/broker/index.js
  lib/services/garbageCollector.js
  lib/services/internalEngine/pluginBootstrap.js
  test/api/controllers/documentController.test.js
  test/api/controllers/funnelController/execute.test.js
  test/api/controllers/funnelController/executePluginRequest.test.js
  test/api/controllers/funnelController/init.test.js
  test/api/core/auth/passportWrapper.test.js
  test/api/core/auth/tokenManager.test.js
  test/api/core/entrypoints/embedded/protocols/http.test.js
  test/api/core/entrypoints/embedded/protocols/websocket.test.js
  test/api/core/hotelClerk/removeRoomForCustomer.test.js
  test/api/core/hotelClerk/removeSubscription.test.js
  test/api/core/models/repositories/repository.test.js
  test/api/core/models/repositories/userRepository.test.js
  test/api/core/notifier/notifyDocumentMDelete.test.js
  test/api/core/notifier/notifyMethods.test.js
  test/mocks/services/redisClient.mock.js
Labels: changelog:exclude

#1137 Fix profile restrictions cache overwrites
  features/kuzzle.feature
  features/step_definitions/profiles.js
  features/support/world.js
  lib/api/core/models/security/profile.js
  lib/api/core/models/security/role.js
  test/api/core/models/security/role.test.js
Labels: changelog:securities

#1133 Fix document:mGet "includeTrash" option
  lib/services/elasticsearch.js
Labels: changelog:bug-fixes

#1139 update dependencies
  package-lock.json
  package.json
Labels: changelog:exclude

#1134 Add support for compressed HTTP requests (gzip, deflate)
  .kuzzlerc.sample
  cucumber.js
  default.config.js
  features/kuzzle.feature
  features/step_definitions/httpCompression.js
  features/support/api/http.js
  features/support/hooks.js
  lib/api/core/entrypoints/embedded/protocols/http.js
  lib/api/core/entrypoints/embedded/protocols/protocol.js
  lib/api/core/entrypoints/embedded/protocols/socketio.js
  lib/api/core/entrypoints/embedded/protocols/websocket.js
  lib/api/core/entrypoints/embedded/service/httpFormDataStream.js
  lib/api/core/httpRouter/index.js
  test/api/controllers/routerController/httpRequest.test.js
  test/api/core/entrypoints/embedded/protocols/http.test.js
  test/api/core/entrypoints/embedded/protocols/socketio.test.js
  test/api/core/entrypoints/embedded/protocols/websocket.test.js
  test/api/core/httpRouter/httpRouter.test.js
Labels: changelog:enhancements

#1144 fixes #1125 - aggs & sort on user search
  lib/api/controllers/securityController.js
  lib/api/core/models/repositories/repository.js
  lib/services/internalEngine/index.js
  package-lock.json
  test/api/controllers/securityController/users.test.js
  test/services/internalEngine/index.test.js
Labels: changelog:bug-fixes, need-documentation
