Repository kuzzleio/kuzzle, pull requests merged in 2018-09, with the labels that each got.

#1181 Plugins/Protocols manifest.json overhaul
  lib/api/core/abstractManifest.js
  lib/api/core/entrypoints/embedded/index.js
  lib/api/core/entrypoints/embedded/manifest.js
  lib/api/core/plugins/manifest.js
  lib/api/core/plugins/pluginsManager.js
  lib/api/kuzzle.js
  lib/config/index.js
  test/api/controllers/authController.test.js
  test/api/core/abstractManifest.test.js
  test/api/core/entrypoints/embedded/index.test.js
  test/api/core/janitor.test.js
  test/api/core/pluginsManager/init.test.js
  test/api/core/pluginsManager/manifest.js
  test/api/core/pluginsManager/manifest.test.js
  test/api/core/pluginsManager/run.test.js
  test/api/core/pluginsManager/strategy.test.js
  test/api/core/pluginsManager/trigger.test.js
  test/config/index.test.js
  test/mocha.opts
Labels: changelog:enhancements

#1190 Update docker build script for new branch name 1-dev
  build-docker-images.sh
  lib/api/core/abstractManifest.js
  lib/services/index.js
  test/api/core/abstractManifest.test.js
Labels: changelog:exclude

#1197 Update to Koncorde 1.2.0
  package-lock.json
  package.json
Labels: changelog:enhancements

#1192 Fix docker password variable in travis.yml
  .travis.yml
Labels: changelog:exclude

#1198 Upgrade the CLI to JS SDK 6-beta
  bin/commands/createFirstAdmin.js
  bin/commands/dump.js
  bin/commands/resetCache.js
  bin/commands/resetDatabase.js
  bin/commands/resetKuzzleData.js
  bin/commands/resetSecurity.js
  bin/commands/sendAction.js
  bin/commands/shutdown.js
Labels: changelog:enhancements

#1196 fix lgtm alerts
  features/step_definitions/profiles.js
  features/step_definitions/role.js
  lib/api/core/entrypoints/embedded/index.js
  lib/api/core/models/security/role.js
  lib/api/core/validation/index.js
  lib/services/redis.js
Labels: changelog:bug-fixes

#1199 Release 1.5.1
  .travis.yml
  bin/commands/createFirstAdmin.js
  bin/commands/dump.js
  bin/commands/resetCache.js
  bin/commands/resetDatabase.js
  bin/commands/resetKuzzleData.js
  bin/commands/resetSecurity.js
  bin/commands/sendAction.js
  bin/commands/shutdown.js
  features/step_definitions/profiles.js
  features/step_definitions/role.js
  lib/api/core/entrypoints/embedded/index.js
  lib/api/core/models/security/role.js
  lib/api/core/validation/index.js
  lib/services/redis.js
  package-lock.json
  package.json
Labels: release
