Repository kuzzleio/kuzzle, pull requests merged in 2018-03, with the labels that each got.

#1048 make common mapping configurable
  .kuzzlerc.sample
  default.config.js
  docker-compose/dev.yml
  lib/config/index.js
  lib/services/elasticsearch.js
  lib/services/internalEngine/bootstrap.js
  test/services/implementations/elasticsearch.test.js
Labels: changelog:bug-fixes

#1058 Release 1.2.7
  .kuzzlerc.sample
  Dockerfile
  bin/commands/start.js
  default.config.js
  docker-compose/dev.yml
  docker-compose/scripts/docker-entrypoint.sh
  docker-compose/scripts/run.sh
  features/run.sh
  features/support/api/http.js
  lib/api/controllers/funnelController.js
  lib/api/controllers/securityController.js
  lib/api/controllers/serverController.js
  lib/api/core/entrypoints/embedded/protocols/http.js
  lib/api/core/hotelClerk.js
  lib/api/core/httpRouter/index.js
  lib/api/core/httpRouter/routeHandler.js
  lib/api/core/models/repositories/profileRepository.js
  lib/api/core/models/repositories/repository.js
  lib/api/core/models/repositories/roleRepository.js
  lib/api/core/models/repositories/userRepository.js
  lib/api/core/models/security/profile.js
  lib/api/core/models/security/role.js
  lib/api/core/models/security/user.js
  lib/api/core/plugins/pluginContext.js
  lib/api/core/plugins/pluginsManager.js
  lib/api/core/statistics.js
  lib/config/httpRoutes.js
  lib/services/elasticsearch.js
  lib/services/internalEngine/bootstrap.js
  lib/services/internalEngine/pluginBootstrap.js
  package-lock.json
  package.json
  test/api/controllers/funnelController/checkRights.test.js
  test/api/controllers/funnelController/executePluginRequest.test.js
  test/api/controllers/securityController/profiles.test.js
  test/api/controllers/securityController/roles.test.js
  test/api/controllers/securityController/users.test.js
  test/api/controllers/serverController.test.js
  test/api/core/entrypoints/embedded/protocols/http.test.js
  test/api/core/httpRouter/httpRouter.test.js
  test/api/core/models/repositories/profileRepository.test.js
  test/api/core/models/repositories/repository.test.js
  test/api/core/models/repositories/roleRepository.test.js
  test/api/core/models/repositories/userRepository.test.js
  test/api/core/models/security/profile.test.js
  test/api/core/models/security/role.test.js
  test/api/core/models/security/user.test.js
  test/api/core/pluginContext/pluginContext.test.js
  test/api/core/pluginsManager/run.test.js
  test/mocks/kuzzle.mock.js
  test/services/implementations/elasticsearch.test.js
  test/services/internalEngine/pluginBootstrap.test.js
Labels: release

#1063 fixes #1062 - update mapping collisions
  lib/services/elasticsearch.js
  package.json
  test/services/implementations/elasticsearch.test.js
Labels: changelog:breaking-changes, priority-blocking

#1064 Dependencies update
  features/kuzzle.feature
  features/run.sh
  features/step_definitions/all.js
  features/step_definitions/authentication.js
  features/step_definitions/bulk.js
  features/step_definitions/collections.js
  features/step_definitions/countDocuments.js
  features/step_definitions/credentials.js
  features/step_definitions/deleteDocument.js
  features/step_definitions/indexes.js
  features/step_definitions/memoryStorage.js
  features/step_definitions/notifications.js
  features/step_definitions/now.js
  features/step_definitions/profiles.js
  features/step_definitions/publishMessage.js
  features/step_definitions/readDocument.js
  features/step_definitions/role.js
  features/step_definitions/serverController.js
  features/step_definitions/statistics.js
  features/step_definitions/subscription.js
  features/step_definitions/users.js
  features/step_definitions/validation.js
  features/step_definitions/wait.js
  features/step_definitions/writeDocument.js
  features/support/api/websocket.js
  features/support/hooks.js
  features/support/world.js
  lib/services/broker/wsBrokerClient.js
  lib/services/broker/wsBrokerServer.js
  package.json
  test/api/cli/index.test.js
  test/api/controllers/securityController/users.test.js
  test/api/core/models/repositories/pluginRepository.test.js
  test/api/core/pluginsManager/strategy.test.js
  test/api/core/validation/init.test.js
  test/api/core/validation/types/date.test.js
  test/api/core/validation/types/geoPoint.test.js
  test/api/core/validation/types/geoShape.test.js
  test/api/core/validation/util.test.js
  test/api/core/validation/validate.test.js
  test/mocha.opts
  test/services/implementations/broker.test.js
  test/services/implementations/elasticsearch.test.js
  test/services/internalEngine/index.test.js
  test/util/esWrapper.test.js
Labels: changelog:securities

#1066 Hotfix: head and options http headers
  lib/api/core/httpRouter/index.js
  package.json
  test/api/core/httpRouter/httpRouter.test.js
Labels: changelog:bug-fixes

#1059 limit message size for websocket and socket.io
  .kuzzlerc.sample
  lib/api/core/entrypoints/embedded/protocols/http.js
  lib/api/core/entrypoints/embedded/protocols/protocol.js
  lib/api/core/entrypoints/embedded/protocols/socketio.js
  lib/api/core/entrypoints/embedded/protocols/websocket.js
  test/api/core/entrypoints/embedded/protocols/http.test.js
  test/api/core/entrypoints/embedded/protocols/socketio.test.js
  test/api/core/entrypoints/embedded/protocols/websocket.test.js
Labels: changelog:bug-fixes
