Repository kuzzleio/kuzzle, pull requests merged in 2018-08, with the labels that each got.

#1171 Fix #1015: Add token expiration information to login response
  lib/api/controllers/authController.js
  test/api/controllers/authController.test.js
Labels: changelog:enhancements

#1170 Hotfix: auth. rejection reason not forwarded to users
  lib/api/core/auth/passportWrapper.js
  lib/api/core/plugins/pluginsManager.js
  package-lock.json
  package.json
  test/api/core/auth/passportWrapper.test.js
  test/api/core/pluginsManager/strategy.test.js
Labels: changelog:bug-fixes

#1172 disable dump by default
  default.config.js
  test/api/controllers/funnelController/executePluginRequest.test.js
Labels: changelog:exclude

#1158 Replace ParseError errors with BadRequestError objects
  lib/api/core/models/security/role.js
  test/api/core/models/security/role.test.js
Labels: changelog:enhancements

#1176 Fix #1174: granting rights to the "ms" controller should also work with its "memoryStorage" alias
  lib/api/core/models/security/profile.js
  lib/api/core/models/security/role.js
  test/api/core/models/security/role.test.js
Labels: changelog:bug-fixes

#1173 Fix #1115: Standardize the scrollId return value
  features/step_definitions/readDocument.js
  lib/services/elasticsearch.js
  test/services/implementations/elasticsearch.test.js
Labels: changelog:enhancements

#1167 Initialize repositories before plugins
  docker-compose/test.yml
  lib/api/kuzzle.js
Labels: changelog:bug-fixes

#1175 allow to search document with empty query through a HTTP GET request
  lib/config/httpRoutes.js
  test/api/controllers/routerController/httpRequest.test.js
Labels: changelog:enhancements

#1178 Use local multi-stage build for kuzzleio/plugin-dev and kuzzleio/kuzzle
  .travis.yml
  Dockerfile
  README.md
  build-docker-images.sh
Labels: changelog:enhancements

#1186 KZL 46 - Add metadata to published documents
  lib/api/controllers/realtimeController.js
  test/api/controllers/realtimeController.test.js
Labels: changelog:enhancements

#1185 KZL 454 - Allow subscribe filters on metadata
  features/kuzzle.feature
  lib/api/controllers/documentController.js
  lib/api/core/notifier.js
  test/api/core/notifier/notifyDocumentReplace.test.js
  test/api/core/notifier/publish.test.js
Labels: changelog:enhancements

#1187 Add LGTM code quality badges
  README.md
Labels: changelog:enhancements

#1182 KZL 290 - Add fixtures for securities
  bin/commands/start.js
  bin/kuzzle
  docker-compose/config/pm2-dev.json
  lib/api/controllers/securityController.js
  lib/api/core/janitor.js
  lib/api/core/models/repositories/pluginRepository.js
  lib/api/core/models/repositories/profileRepository.js
  lib/api/core/models/repositories/repository.js
  lib/api/core/models/repositories/roleRepository.js
  lib/api/core/models/repositories/userRepository.js
  lib/services/elasticsearch.js
  test/api/controllers/securityController/roles.test.js
  test/api/core/janitor.test.js
  test/api/core/models/repositories/profileRepository.test.js
  test/api/core/models/repositories/repository.test.js
  test/mocks/fixtures.json
  test/mocks/mappings.json
  test/mocks/securities.json
Labels: changelog:new-features
