Repository kuzzleio/kuzzle, pull requests merged in 2018-04, with the labels that each got.

#1080 Fix a bug preventing user profiles from being cached
  lib/api/controllers/securityController.js
  lib/api/core/auth/formatProcessing.js
  lib/api/core/models/repositories/profileRepository.js
  lib/api/core/models/repositories/repository.js
  lib/api/core/models/repositories/userRepository.js
  lib/services/internalEngine/index.js
  test/api/core/models/repositories/profileRepository.test.js
Labels: changelog:bug-fixes

#1081 dependencies update
  Dockerfile
  ROADMAP.md
  docker-compose/scripts/docker-entrypoint.sh
  package-lock.json
  package.json
Labels: changelog:exclude

#1073 Use bulk insertions for multi-documents API routes
  .kuzzlerc.sample
  .nycrc
  default.config.js
  docker-compose/scripts/run-test.sh
  features/README.md
  features/run.sh
  features/support/hooks.js
  features/support/world.js
  lib/api/controllers/documentController.js
  lib/api/controllers/funnelController.js
  lib/api/core/models/repositories/repository.js
  lib/api/core/notifier.js
  lib/api/core/statistics.js
  lib/config/index.js
  lib/services/elasticsearch.js
  lib/services/redis.js
  test/api/controllers/documentController.test.js
  test/api/controllers/funnelController/executePluginRequest.test.js
  test/api/controllers/funnelController/processRequest.test.js
  test/api/core/models/repositories/repository.test.js
  test/api/core/models/repositories/tokenRepository.test.js
  test/api/core/notifier/notifyDocumentMDelete.test.js
  test/api/core/notifier/notifyDocumentReplace.test.js
  test/api/core/notifier/notifyDocumentUpdate.test.js
  test/api/core/notifier/publish.test.js
  test/api/core/statistics.test.js
  test/config/index.test.js
  test/mocks/kuzzle.mock.js
  test/mocks/services/elasticsearchClient.mock.js
  test/services/implementations/elasticsearch.test.js
  test/services/redis.test.js
Labels: changelog:enhancements

#1084 should not generate a dump on SIGTERM
  lib/api/kuzzle.js
  test/api/kuzzle.test.js
Labels: changelog:bug-fixes

#1083 Kuzzle CLI was unable to connect to Kuzzle Server
  features/support/api/websocket.js
  lib/api/core/entrypoints/embedded/protocols/websocket.js
  lib/services/broker/wsBrokerClient.js
  lib/services/broker/wsBrokerServer.js
  package-lock.json
  package.json
  test/api/core/entrypoints/embedded/protocols/websocket.test.js
  test/services/implementations/broker.test.js
Labels: changelog:bug-fixes, priority-blocking

#1086 Fix #1068: JWT expire sooner than expected
  features/kuzzle.feature
  features/step_definitions/subscription.js
  features/support/api/apiBase.js
  lib/api/controllers/authController.js
  lib/api/controllers/realtimeController.js
  lib/api/core/auth/tokenManager.js
  lib/api/core/hotelClerk.js
  lib/api/core/models/repositories/repository.js
  lib/api/core/models/repositories/tokenRepository.js
  lib/api/core/models/security/token.js
  lib/api/core/plugins/pluginsManager.js
  test/api/controllers/authController.test.js
  test/api/core/auth/tokenManager.test.js
  test/api/core/models/repositories/tokenRepository.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:bug-fixes

#1087 Fix performances issue when retrieving/searching numerous users at once
  lib/api/core/entrypoints/embedded/protocols/http.js
  lib/api/core/models/repositories/profileRepository.js
  lib/api/core/models/repositories/repository.js
  lib/api/core/models/repositories/roleRepository.js
  lib/api/core/models/repositories/userRepository.js
  lib/api/core/models/security/profile.js
  lib/api/core/models/security/role.js
  lib/api/core/models/security/user.js
  lib/services/internalEngine/index.js
  test/api/core/models/repositories/profileRepository.test.js
  test/api/core/models/repositories/roleRepository.test.js
  test/api/core/models/repositories/userRepository.test.js
Labels: changelog:bug-fixes

#1092 Add pull request template
  .github/pull_request_template.md
Labels: changelog:exclude

#1088 remove promise warnings from the internal engine's bootstrap
  lib/services/internalEngine/bootstrap.js
Labels: changelog:exclude

#1100 Fix links in README.md
  README.md
Labels: changelog:bug-fixes
