Repository kuzzleio/kuzzle, pull requests merged in 2018-05, with the labels that each got.

#1096 Add strict format checking to profile definitions
  .github/pull_request_template.md
  lib/api/core/models/security/profile.js
  lib/api/core/models/security/user.js
  test/api/controllers/securityController/profiles.test.js
  test/api/core/models/repositories/profileRepository.test.js
  test/api/core/models/security/profile.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:bug-fixes

#1094 add feature tests for createFirstAdmin method
  features/kuzzle.feature
  features/step_definitions/profiles.js
  features/step_definitions/role.js
  features/step_definitions/users.js
  features/support/api/apiBase.js
  features/support/api/http.js
  features/support/hooks.js
  features/support/world.js
  lib/api/core/httpRouter/index.js
  lib/api/core/httpRouter/routePart.js
  lib/config/httpRoutes.js
  package.json
Labels: changelog:exclude, need-documentation

#1108 Add events on http routing
  bin/README.md
  bin/commands/start.js
  docker-compose/dev.yml
  docker-compose/scripts/install-plugins.sh
  docker-compose/scripts/run-dev.sh
  docker-compose/scripts/run-test.sh
  docker-compose/test.yml
  lib/api/core/httpRouter/index.js
  lib/api/kuzzle.js
  test/api/controllers/cli/cleanDb.test.js
  test/api/controllers/collectionController.test.js
  test/api/controllers/funnelController/execute.test.js
  test/api/controllers/funnelController/executePluginRequest.test.js
  test/api/controllers/funnelController/processRequest.test.js
  test/api/controllers/memoryStorageController.test.js
  test/api/controllers/routerController/httpRequest.test.js
  test/api/core/auth/passportWrapper.test.js
  test/api/core/hotelClerk/removeRoomForCustomer.test.js
  test/api/core/hotelClerk/removeSubscription.test.js
  test/api/core/httpRouter/httpRouter.test.js
  test/api/core/models/security/user.test.js
  test/api/core/notifier/notifyDocumentMDelete.test.js
  test/api/core/notifier/notifyMethods.test.js
  test/api/core/notifier/publish.test.js
  test/api/core/pluginContext/pluginContext.test.js
  test/services/implementations/elasticsearch.test.js
  test/services/redis.test.js
Labels: changelog:new-features

#1114 Allow mapping in collection creation route
  lib/api/controllers/collectionController.js
  lib/services/elasticsearch.js
  package-lock.json
  test/services/implementations/elasticsearch.test.js
Labels: changelog:new-features

#1117 Document validators bugfixes
  lib/api/controllers/collectionController.js
  lib/api/core/validation/baseType.js
  lib/api/core/validation/index.js
  lib/api/core/validation/types/anything.js
  lib/api/core/validation/types/boolean.js
  lib/api/core/validation/types/date.js
  lib/api/core/validation/types/email.js
  lib/api/core/validation/types/enum.js
  lib/api/core/validation/types/geoPoint.js
  lib/api/core/validation/types/geoShape.js
  lib/api/core/validation/types/integer.js
  lib/api/core/validation/types/ipAddress.js
  lib/api/core/validation/types/numeric.js
  lib/api/core/validation/types/object.js
  lib/api/core/validation/types/string.js
  lib/api/core/validation/types/type.js.template
  lib/api/core/validation/types/url.js
  package-lock.json
  package.json
  test/api/controllers/collectionController.test.js
  test/api/core/validation/baseType.test.js
  test/api/core/validation/init.test.js
  test/api/core/validation/types/anything.test.js
  test/api/core/validation/types/boolean.test.js
  test/api/core/validation/types/date.test.js
  test/api/core/validation/types/email.test.js
  test/api/core/validation/types/enum.test.js
  test/api/core/validation/types/geoPoint.test.js
  test/api/core/validation/types/geoShape.test.js
  test/api/core/validation/types/integer.test.js
  test/api/core/validation/types/ipAddress.test.js
  test/api/core/validation/types/numeric.test.js
  test/api/core/validation/types/object.test.js
  test/api/core/validation/types/string.test.js
  test/api/core/validation/types/url.test.js
  test/api/core/validation/util.test.js
  test/api/core/validation/validate.test.js
Labels: changelog:bug-fixes
