Repository kuzzleio/kuzzle, pull requests merged in 2018-11, with the labels that each got.

#1215 Release 1.5.3
  .ci/config/pm2.json
  .ci/haproxy/haproxy.cfg
  .ci/haproxy/snakeoil.pem
  .ci/run-tests.sh
  .ci/scripts/docker-entrypoint.sh
  .ci/scripts/install-aarch64-deps.sh
  .ci/scripts/install-armhf-deps.sh
  .ci/scripts/install-plugins.sh
  .ci/scripts/run-test-arm.sh
  .ci/scripts/run-test.sh
  .ci/scripts/run.sh
  .ci/sonar.sh
  .ci/test-aarch64.yml
  .ci/test-armhf.yml
  .ci/test.yml
  .kuzzlerc.sample
  .travis.yml
  lib/api/controllers/documentController.js
  lib/api/core/models/repositories/repository.js
  lib/api/kuzzle.js
  package-lock.json
  package.json
  test/api/core/models/repositories/profileRepository.test.js
  test/api/core/models/repositories/repository.test.js
  test/api/core/models/repositories/userRepository.test.js
  test/services/internalEngine/pluginBootstrap.test.js
  test/travis-bin/run-tests.sh
Labels: release

#1216 [dockerhub] Fix docker image builder
  .travis.yml
  build-docker-images.sh
Labels: changelog:bug-fixes

#1217 update dependency: use https to get kuzzle-sdk from git
  package-lock.json
  package.json
Labels: changelog:exclude

#1218 Upgrade Koncorde version
  package-lock.json
  package.json
Labels: changelog:enhancements

#1222 Release 1.5.4
  .travis.yml
  build-docker-images.sh
  package-lock.json
  package.json
Labels: release
