Repository kuzzleio/kuzzle, pull requests merged in 2019-11, with the labels that each got.

#1487 Add kuzzle version to the dumped informations
  lib/api/core/janitor.js
  test/api/core/janitor.test.js
Labels: changelog:enhancements

#1494 Check for SDK compatibility against current Kuzzle version
  doc/1/api/essentials/errors/codes/index.md
  lib/api/controllers/funnelController.js
  lib/config/error-codes/api.json
  lib/config/sdkCompatibility.json
  test/api/controllers/funnelController/processRequest.test.js
Labels: changelog:enhancements

#1495 Check for SDK compatibility against current Kuzzle version
  doc/2/api/essentials/errors/codes/index.md
  docker-compose.yml
  lib/api/controllers/funnelController.js
  lib/config/error-codes/api.json
  lib/config/sdkCompatibility.json
  test/api/controllers/funnelController/processRequest.test.js
Labels: 2.x, changelog:enhancements

#1506 Properly destroy a user after a credentials creation failure
  lib/api/controllers/securityController.js
  test/api/controllers/securityController/users.test.js
Labels: changelog:bug-fixes

#1509 mapping - enable dynamic templates
  lib/services/elasticsearch.js
  test/services/implementations/elasticsearch.test.js
Labels: changelog:enhancements

#1510 mapping - enable dynamic templates
  lib/services/elasticsearch.js
  test/services/elasticsearch.test.js
Labels: changelog:enhancements

#1499 Expose an Elasticsearch client constructor in plugin context
  .ci/scripts/run-test-arm.sh
  .ci/scripts/run-test.sh
  .ci/scripts/run.sh
  .gitignore
  bin/start-kuzzle-server
  doc/2/plugins/plugin-context/constructors/elasticsearch/index.md
  docker-compose/config/pm2-dev.json
  docker-compose/scripts/run.sh
  features-sdk/PluginContext.feature
  lib/api/controllers/routerController.js
  lib/api/core/plugins/pluginContext.js
  lib/services/elasticsearch.js
  plugins/available/functional-test-plugin/index.js
  plugins/available/functional-test-plugin/manifest.json
  test/api/core/pluginContext/pluginContext.test.js
  test/services/elasticsearch.test.js
Labels: 2.x, changelog:new-features

#1501 Add collection delete
  bin/start-kuzzle-server
  doc/2/api/controllers/collection/delete/index.md
  doc/2/guides/upgrade-kuzzle/changes/index.md
  docker-compose.yml
  docker-compose/scripts/run-dev.sh
  features-sdk/CollectionController.feature
  lib/api/controllers/collectionController.js
  lib/api/core/storage/clientAdapter.js
  lib/api/core/storage/indexStorage.js
  lib/config/httpRoutes.js
  lib/services/elasticsearch.js
  test/api/controllers/collectionController.test.js
  test/mocks/clientAdapter.mock.js
  test/mocks/elasticsearch.mock.js
  test/services/elasticsearch.test.js
Labels: 2.x, changelog:new-features

#1507 Properly destroy a user after a credentials creation failure
  lib/api/controllers/securityController.js
  test/api/controllers/securityController/users.test.js
Labels: 2.x, changelog:bug-fixes

#1508 Use external vault package
  bin/commands/decryptSecrets.js
  bin/commands/encryptSecrets.js
  features/kuzzle.feature
  lib/api/core/vault.js
  lib/api/kuzzle.js
  package-lock.json
  package.json
  test/api/core/vault.test.js
  test/api/kuzzle.test.js
Labels: changelog:bug-fixes

#1502 Add a new "document:exists" API route
  .eslintrc.json
  doc/2/api/controllers/document/exists/index.md
  features-sdk/.eslintrc.json
  features-sdk/DocumentController.feature
  features-sdk/fixtures/fixtures.js
  features-sdk/fixtures/mappings.js
  features-sdk/step_definitions/documents-steps.js
  features-sdk/step_definitions/index-steps.js
  features-sdk/step_definitions/security-steps.js
  features-sdk/support/hooks.js
  package.json
Labels: 2.x, changelog:new-features

#1515 Fix functional tests
  features-sdk/run.sh
  features-sdk/support/hooks.js
Labels: 2.x, changelog:exclude

#1512 fix subscribing with a dead connection
  lib/api/controllers/realtimeController.js
  test/api/controllers/realtimeController.test.js
Labels: 2.x, changelog:bug-fixes

#1511 Hotfix/subscribe dead connection
  .ci/scripts/install-plugins.sh
  .ci/scripts/run-test.sh
  lib/api/controllers/realtimeController.js
  test/api/controllers/realtimeController.test.js
Labels: changelog:bug-fixes

#1513 Add link to the roadmap in the README
  README.md
Labels: changelog:exclude

#1518 fix-default-mapping-for-discovered-collection
  lib/api/core/indexCache.js
  lib/services/internalEngine/index.js
  test/api/core/indexCache.test.js
  test/services/internalEngine/index.test.js
Labels: changelog:bug-fixes

#1496 Update CLI documentation
  doc/2/guides/essentials/cli/index.md
  doc/2/guides/essentials/installing-kuzzle/index.md
  doc/2/guides/essentials/secrets-vault/index.md
  doc/2/guides/getting-started/running-kuzzle/index.md
  doc/2/protocols/native-protocols/mqtt/index.md
  features/step_definitions/cli.js
Labels: 2.x, changelog:exclude

#1503 Add functional tests for generic:document:write event
  doc/2/plugins/plugin-context/constructors/elasticsearch/index.md
  features-sdk/DocumentController.feature
  features-sdk/PluginEvents.feature
  features-sdk/step_definitions/controllers-steps.js
  features-sdk/step_definitions/documents-steps.js
  features-sdk/step_definitions/plugin-events-steps.js
  features-sdk/support/hooks.js
  features-sdk/support/world.js
  features/kuzzle.feature
  plugins/available/functional-test-plugin/index.js
  test/services/elasticsearch.test.js
Labels: 2.x, changelog:exclude

#1514 Use external Vault
  .ci/scripts/run.sh
  .ci/test-aarch64.yml
  .ci/test-armhf.yml
  .ci/test.yml
  docker-compose.yml
  features-sdk/PluginContext.feature
  features-sdk/fixtures/secrets.enc.json
  features-sdk/fixtures/secrets.json
  features-sdk/support/hooks.js
  features-sdk/support/world.js
  features/support/hooks.js
  lib/api/core/vault.js
  lib/api/kuzzle.js
  package-lock.json
  package.json
  plugins/available/functional-test-plugin/index.js
  test/api/core/vault.test.js
  test/api/kuzzle.test.js
Labels: 2.x, changelog:enhancements

#1505 Fix delete profile while being used by user
  features/kuzzle.feature
  features/step_definitions/profiles.js
  lib/api/core/models/repositories/profileRepository.js
Labels: changelog:bug-fixes

#1524 Remove usage of array.shift
  lib/services/elasticsearch.js
Labels: 2.x, changelog:exclude

#1527 Remove superfluous shard check when checking connection to the ES stack
  .ci/scripts/run-test-arm.sh
  .ci/scripts/run-test.sh
  .ci/scripts/run.sh
  docker-compose/dev.yml
  docker-compose/scripts/run-dev.sh
  docker-compose/scripts/run.sh
Labels: changelog:exclude

#1528 Remove superfluous shard check when checking connection to the ES stack
  .ci/scripts/run-test-arm.sh
  .ci/scripts/run-test.sh
  docker-compose/scripts/run-dev.sh
  docker-compose/scripts/run.sh
Labels: 2.x, changelog:exclude

#1530 Rejects new API requests during a shutdown sequence
  doc/2/api/essentials/errors/codes/index.md
  doc/2/plugins/guides/events/core-shutdown/index.md
  lib/api/controllers/funnelController.js
  lib/api/core/janitor.js
  lib/api/kuzzle.js
  lib/config/error-codes/api.json
  lib/util/shutdown.js
  package-lock.json
  package.json
  test/api/controllers/funnelController/execute.test.js
  test/api/core/janitor.test.js
  test/services/elasticsearch.test.js
  test/util/shutdown.test.js
Labels: 2.x, changelog:bug-fixes

#1529 Fix shutdown process
  lib/api/core/janitor.js
  lib/api/kuzzle.js
  lib/util/shutdown.js
  package-lock.json
  package.json
  test/api/core/janitor.test.js
  test/mocks/kuzzle.mock.js
  test/util/shutdown.test.js
Labels: 1.x, changelog:bug-fixes

#1531 Enforce naming rules on indexes and collections
  doc/2/api/controllers/collection/create/index.md
  doc/2/api/controllers/index/create/index.md
  doc/2/api/essentials/errors/codes/index.md
  lib/api/controllers/collection.js
  lib/config/error-codes/services.json
  lib/core/models/repositories/profileRepository.js
  lib/core/models/security/profile.js
  lib/core/storage/clientAdapter.js
  lib/services/elasticsearch.js
  test/core/models/repositories/profileRepository.test.js
  test/core/models/security/profile.test.js
  test/mocks/clientAdapter.mock.js
  test/services/elasticsearch.test.js
Labels: 2.x, changelog:bug-fixes
