Repository kuzzleio/kuzzle, pull requests merged in 2019-07, with the labels that each got.

#1329 Add document global events (database:*)
  features/step_definitions/deleteDocument.js
  lib/api/controllers/funnelController.js
  lib/api/core/plugins/pluginsManager.js
  lib/api/kuzzle.js
  lib/config/documentEventAliases.js
  lib/util/DocumentExtractor.js
  test/api/controllers/funnelController/performDocumentAlias.test.js
  test/api/controllers/funnelController/processRequest.test.js
  test/util/DocumentExtractor.test.js
Labels: changelog:new-features, need-documentation

#1306 Add new throw custom method, change error management
  lib/api/controllers/controller.js
  lib/api/controllers/serverController.js
  lib/api/core/hotelClerk.js
  lib/api/core/janitor.js
  lib/api/core/vault.js
  lib/api/kuzzle.js
  lib/config/error-codes/api.json
  lib/config/error-codes/index.js
  lib/config/error-codes/internal.json
  lib/config/error-codes/throw.js
  package-lock.json
  test/api/controllers/serverController.test.js
  test/api/core/hotelClerk/addSubscription.test.js
  test/api/core/hotelClerk/countSubscription.test.js
  test/api/core/hotelClerk/removeRoomForCustomer.test.js
  test/api/kuzzle.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:enhancements, do-not-merge

#1345 Re-enable Node.js 6 functional tests on PR
  .travis.yml
Labels: changelog:exclude

#1343 Do not let the Elasticsearch error wrapper overwrite the original stack trace
  lib/services/elasticsearch.js
  lib/util/esWrapper.js
  test/services/implementations/elasticsearch.test.js
  test/util/esWrapper.test.js
Labels: changelog:enhancements

#1346 Remove error stack traces leaks in production environment
  lib/api/core/entrypoints/embedded/index.js
  lib/api/core/entrypoints/embedded/protocols/http.js
  lib/api/core/entrypoints/embedded/protocols/mqtt.js
  lib/api/core/entrypoints/embedded/protocols/protocol.js
  lib/api/core/entrypoints/embedded/protocols/websocket.js
  lib/api/core/entrypoints/embedded/removeErrorStack.js
  package-lock.json
  package.json
  test/api/core/entrypoints/embedded/protocols/http.test.js
  test/api/core/entrypoints/embedded/protocols/mqtt.test.js
  test/api/core/entrypoints/embedded/protocols/websocket.test.js
  test/util/errorMatcher.js
Labels: changelog:securities

#1344 Fix default mappings on aliases
  lib/services/internalEngine/index.js
  lib/util/esWrapper.js
  test/util/esWrapper.test.js
Labels: changelog:bug-fixes

#1348 Add meaningful error message in plugins init
  lib/api/controllers/funnelController.js
  lib/api/core/plugins/pluginsManager.js
  lib/util/didYouMean.js
  package-lock.json
  package.json
  test/api/controllers/funnelController/checkRights.test.js
  test/api/core/pluginsManager/run.test.js
  test/util/didYouMean.test.js
Labels: changelog:enhancements

#1349 Add feature request template
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
Labels: changelog:exclude

#1340 Fix automated dumps and shutdown sequence
  lib/api/controllers/adminController.js
  lib/api/controllers/funnelController.js
  lib/api/core/janitor.js
  lib/api/kuzzle.js
  lib/config/error-codes/internal.json
  test/api/controllers/funnelController/executePluginRequest.test.js
  test/api/core/janitor.test.js
Labels: changelog:bug-fixes

#1353 Fix call stack exceeded error on ms:mget and ms:mset
  .gitignore
  lib/api/controllers/memoryStorageController.js
  test/api/controllers/memoryStorageController.test.js
Labels: changelog:bug-fixes

#1350 Add public route to list api actions
  doc/1/api/controllers/server/public-api/index.md
  features/kuzzle.feature
  features/step_definitions/serverController.js
  features/support/api/apiBase.js
  features/support/api/http.js
  lib/api/controllers/adminController.js
  lib/api/controllers/authController.js
  lib/api/controllers/baseController.js
  lib/api/controllers/bulkController.js
  lib/api/controllers/collectionController.js
  lib/api/controllers/documentController.js
  lib/api/controllers/indexController.js
  lib/api/controllers/memoryStorageController.js
  lib/api/controllers/realtimeController.js
  lib/api/controllers/securityController.js
  lib/api/controllers/serverController.js
  lib/config/httpRoutes.js
  test/api/controllers/adminController.test.js
  test/api/controllers/authController.test.js
  test/api/controllers/baseController.test.js
  test/api/controllers/bulkController.test.js
  test/api/controllers/collectionController.test.js
  test/api/controllers/documentController.test.js
  test/api/controllers/indexController.test.js
  test/api/controllers/memoryStorageController.test.js
  test/api/controllers/realtimeController.test.js
  test/api/controllers/securityController/index.js
  test/api/controllers/serverController.test.js
  test/mocks/controller.mock.js
Labels: changelog:new-features

#1363 Fix documentation deployment conditions
  .travis.yml
Labels: changelog:exclude

#1359 Fix a typo in the plugin's raw request documentation
  doc/1/plugins/plugin-context/constructors/request/index.md
Labels: changelog:exclude

#1354 Add error message on wrong mapping
  lib/api/core/plugins/pluginsManager.js
  lib/config/error-codes/external.json
  lib/services/elasticsearch.js
  lib/services/internalEngine/bootstrap.js
  test/services/implementations/elasticsearch.test.js
Labels: changelog:enhancements

#1368 Provide a copy of Kuzzle's configuration to plugins
  lib/api/core/plugins/pluginsManager.js
  test/api/core/pluginsManager/init.test.js
Labels: changelog:bug-fixes
