Repository kuzzleio/kuzzle, pull requests merged in 2019-09, with the labels that each got.

#1433 Fix cache roles and profiles
  lib/api/core/models/repositories/profileRepository.js
  lib/api/core/models/repositories/roleRepository.js
  test/api/core/models/repositories/profileRepository.test.js
  test/api/core/models/repositories/roleRepository.test.js
Labels: changelog:bug-fixes

#1440 Run codecov only after success
  .travis.yml
Labels: changelog:exclude

#1425 Add encryptSecrets and decryptSecrets route in adminController
  doc/2/api/controllers/admin/decrypt-secrets/index.md
  doc/2/api/controllers/admin/encrypt-secrets/index.md
  features/kuzzle.feature
  features/step_definitions/adminController.js
  features/support/api/apiBase.js
  features/support/api/http.js
  lib/api/controllers/adminController.js
  lib/api/core/vault.js
  lib/config/error-codes/internal.json
  lib/config/httpRoutes.js
  test/api/controllers/adminController.test.js
  test/api/core/vault.test.js
  test/mocks/kuzzle.mock.js
Labels: 2.x, changelog:new-features

#1443 fix 404
  doc/2/plugins/plugin-context/accessors/sdk/index.md
Labels: changelog:exclude

#1444 Revert "Add encryptSecrets and decryptSecrets route in adminController"
  doc/2/api/controllers/admin/decrypt-secrets/index.md
  doc/2/api/controllers/admin/encrypt-secrets/index.md
  features/kuzzle.feature
  features/step_definitions/adminController.js
  features/support/api/apiBase.js
  features/support/api/http.js
  lib/api/controllers/adminController.js
  lib/api/core/vault.js
  lib/config/error-codes/internal.json
  lib/config/httpRoutes.js
  test/api/controllers/adminController.test.js
  test/api/core/vault.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:exclude

#1418 Add event on new/removed connection
  doc/2/plugins/guides/events/connection-new/index.md
  doc/2/plugins/guides/events/connection-remove/index.md
  lib/api/core/entrypoints/clientConnection.js
  lib/api/core/entrypoints/index.js
  lib/api/core/entrypoints/protocols/http.js
  test/api/core/entrypoints/clientConnection.test.js
  test/api/core/entrypoints/index.test.js
Labels: 2.x, changelog:exclude

#1412 fix-404
  doc/1/guides/cookbooks/realtime-api/terms/index.md
  doc/1/guides/essentials/real-time/index.md
  doc/1/plugins/guides/events/api-events/index.md
  doc/1/plugins/guides/events/http-delete/index.md
  doc/1/plugins/guides/events/http-get/index.md
  doc/1/plugins/guides/events/http-head/index.md
  doc/1/plugins/guides/events/http-options/index.md
  doc/1/plugins/guides/events/http-patch/index.md
  doc/1/plugins/guides/events/http-post/index.md
  doc/1/plugins/guides/events/http-put/index.md
  doc/1/plugins/guides/events/plugin-events/index.md
  doc/1/plugins/guides/events/request-on-authorized/index.md
  doc/1/plugins/guides/events/request-on-error/index.md
  doc/1/plugins/guides/events/request-on-success/index.md
  doc/1/plugins/guides/events/request-on-unauthorized/index.md
  doc/1/plugins/guides/strategies/auth-functions/index.md
  doc/1/plugins/plugin-context/accessors/execute/index.md
  doc/1/plugins/plugin-context/accessors/intro/index.md
  doc/1/plugins/plugin-context/accessors/sdk/index.md
  doc/1/plugins/plugin-context/accessors/validation/index.md
  doc/1/plugins/plugin-context/constructors/request/index.md
  doc/1/plugins/plugin-context/errors/partialerror/index.md
Labels: changelog:exclude

#1430 Allow uppercased plugins
  doc/1/api/essentials/errors/subcodes/index.md
  doc/1/plugins/guides/manual-setup/prerequisites/index.md
  lib/api/core/plugins/manifest.js
  lib/api/core/plugins/pluginsManager.js
  lib/config/error-codes/plugins.json
  test/api/core/pluginsManager/init.test.js
  test/api/core/pluginsManager/manifest.test.js
Labels: changelog:enhancements

#1432 Allow uppercased plugins
  doc/2/plugins/guides/manual-setup/prerequisites/index.md
  lib/api/core/plugins/manifest.js
  lib/api/core/plugins/pluginsManager.js
  lib/config/error-codes/plugins.json
  test/api/core/pluginsManager/init.test.js
  test/api/core/pluginsManager/manifest.test.js
Labels: 2.x, changelog:enhancements

#1428 Drop support for permission closures
  lib/api/core/entrypoints/index.js
  lib/api/core/plugins/pluginContext.js
  package-lock.json
Labels: 2.x, changelog:breaking-changes

#1405 Add subcodes documentation
  .travis.yml
  doc/2/api/essentials/errors/subcodes/index.md
  doc/generate-subcodes-doc.js
  package.json
Labels: 2.x, changelog:exclude

#1395 Add documentation of the errors manager
  doc/1/api/essentials/errors/index.md
  doc/1/plugins/plugin-context/customize-errors/index.md
  doc/1/plugins/plugin-context/errors/kuzzleerror/index.md
  lib/api/controllers/authController.js
  lib/api/controllers/bulkController.js
  lib/api/controllers/collectionController.js
  lib/api/controllers/documentController.js
  lib/api/controllers/funnelController.js
  lib/api/controllers/routerController.js
  lib/api/controllers/securityController.js
  lib/api/controllers/serverController.js
  lib/api/core/auth/passportWrapper.js
  lib/api/core/entrypoints/embedded/protocols/http.js
  lib/api/core/entrypoints/embedded/protocols/mqtt.js
  lib/api/core/entrypoints/embedded/protocols/websocket.js
  lib/api/core/hotelClerk.js
  lib/api/core/httpRouter/index.js
  lib/api/core/janitor.js
  lib/api/core/models/repositories/profileRepository.js
  lib/api/core/models/repositories/repository.js
  lib/api/core/models/repositories/roleRepository.js
  lib/api/core/models/repositories/tokenRepository.js
  lib/api/core/models/security/profile.js
  lib/api/core/models/security/role.js
  lib/api/core/plugins/pluginContext.js
  lib/api/core/plugins/pluginsManager.js
  lib/api/core/sandbox/index.js
  lib/api/core/sdk/funnelProtocol.js
  lib/api/core/statistics.js
  lib/api/core/validation/index.js
  lib/config/error-codes/throw.js
  lib/services/elasticsearch.js
  lib/services/internalEngine/index.js
  lib/services/redis.js
  lib/services/service.js
  lib/util/esWrapper.js
  test/api/core/entrypoints/embedded/protocols/http.test.js
  test/services/implementations/elasticsearch.test.js
  test/util/errorMatcher.js
Labels: changelog:exclude

#1441 Add more example to security:getCredentialsById documentation
  doc/2/api/controllers/security/get-credentials-by-id/index.md
Labels: 2.x, changelog:exclude

#1408 Fix a crash occuring when trying to ping dead sockets
  .eslintrc.json
  doc/2/api/essentials/errors/subcodes/index.md
  lib/api/core/entrypoints/protocols/websocket.js
  test/api/core/entrypoints/protocols/websocket.test.js
Labels: 2.x, changelog:bug-fixes

#1415 Add subcodes error to requestAssertions
  doc/1/api/essentials/errors/subcodes/index.md
  doc/2/api/essentials/errors/subcodes/index.md
  doc/generate-subcodes-doc.js
  lib/config/error-codes/api.json
  lib/util/requestAssertions.js
Labels: 2.x, changelog:exclude

#1442 Add documentation of the errors manager
  doc/1/plugins/plugin-context/customize-errors/index.md
  doc/2/api/essentials/errors/index.md
  doc/2/plugins/plugin-context/errors/kuzzleerror/index.md
Labels: 2.x, changelog:exclude

#1435 Fix cache roles and profiles
  lib/api/core/models/repositories/profileRepository.js
  lib/api/core/models/repositories/roleRepository.js
  test/api/core/models/repositories/profileRepository.test.js
  test/api/core/models/repositories/roleRepository.test.js
Labels: 2.x, changelog:bug-fixes

#1437 Fix hydrating a profile with unexisting role
  lib/api/core/models/repositories/profileRepository.js
  test/api/core/models/repositories/profileRepository.test.js
Labels: changelog:bug-fixes

#1438 Fix hydrating a profile with unexisting role
  lib/api/core/models/repositories/profileRepository.js
  test/api/core/models/repositories/profileRepository.test.js
Labels: 2.x, changelog:bug-fixes

#1453 Fix linter and unit test errors.
  doc/2/api/essentials/errors/subcodes/index.md
  doc/generate-subcodes-doc.js
  lib/api/core/storage/indexCache.js
  lib/config/index.js
  test/api/core/models/repositories/roleRepository.test.js
  test/api/core/storage/bootstrap/internalIndexBootstrap.test.js
  test/mocks/indexEngine.mock.js
Labels: 2.x, changelog:exclude

#1416 Fix building KuzzleErrors with non KuzzleError for errorsManager
  doc/2/api/essentials/errors/subcodes/index.md
  lib/api/controllers/authController.js
  lib/api/controllers/funnelController.js
  lib/api/core/auth/passportWrapper.js
  lib/api/core/entrypoints/protocols/http.js
  lib/api/core/httpRouter/index.js
  lib/api/core/plugins/pluginsManager.js
  lib/api/core/validation/index.js
  lib/config/error-codes/plugins.json
  lib/config/error-codes/throw.js
  test/api/controllers/funnelController/handleProcessRequestError.test.js
  test/api/core/auth/passportWrapper.test.js
  test/api/core/entrypoints/protocols/http.test.js
  test/api/core/models/repositories/roleRepository.test.js
  test/api/core/pluginsManager/run.test.js
  test/api/core/validation/init.test.js
Labels: 2.x, changelog:bug-fixes

#1454 Fix a bug that prevents Kuzzle to shutdown
  lib/api/kuzzle.js
  lib/util/shutdown.js
Labels: changelog:bug-fixes

#1451 Fix document:mGet to return a partial error with missing docs
  doc/1/api/controllers/document/m-get/index.md
  doc/1/api/essentials/errors/subcodes/index.md
  lib/api/controllers/documentController.js
  lib/config/error-codes/api.json
  test/api/controllers/documentController.test.js
Labels: changelog:bug-fixes

#1455 fix init indices containing a dot
  .travis.yml
  lib/util/esWrapper.js
  test/util/esWrapper.test.js
Labels: changelog:bug-fixes

#1450 Fix 404
  doc/1/plugins/guides/events/api-events/index.md
  doc/1/plugins/guides/events/http-delete/index.md
  doc/1/plugins/guides/events/http-get/index.md
  doc/1/plugins/guides/events/http-head/index.md
  doc/1/plugins/guides/events/http-options/index.md
  doc/1/plugins/guides/events/http-patch/index.md
  doc/1/plugins/guides/events/http-post/index.md
  doc/1/plugins/guides/events/http-put/index.md
  doc/1/plugins/guides/events/plugin-events/index.md
  doc/1/plugins/guides/events/request-on-authorized/index.md
  doc/1/plugins/guides/events/request-on-error/index.md
  doc/1/plugins/guides/events/request-on-success/index.md
  doc/1/plugins/guides/events/request-on-unauthorized/index.md
  doc/1/plugins/guides/strategies/auth-functions/index.md
  doc/1/plugins/plugin-context/accessors/execute/index.md
  doc/1/plugins/plugin-context/accessors/validation/index.md
  doc/1/plugins/plugin-context/constructors/request/index.md
  doc/1/plugins/plugin-context/errors/partialerror/index.md
Labels: changelog:exclude

#1452 Fix admin:resetSecurity result typo and documentation
  doc/1/api/controllers/admin/reset-security/index.md
  lib/api/controllers/adminController.js
Labels: changelog:bug-fixes

#1459 Access to the plugin repository using the lowercased manifest name
  lib/api/core/plugins/pluginsManager.js
  test/api/core/pluginsManager/strategy.test.js
Labels: changelog:bug-fixes

#1460 Remove error subcodes documentation
  .travis.yml
  doc/1/api/essentials/errors/index.md
  doc/1/api/essentials/errors/subcodes/index.md
Labels: changelog:exclude

#1461 Dependencies update
  doc/1/plugins/plugin-context/customize-errors/index.md
  package-lock.json
  package.json
Labels: changelog:exclude

#1462 Restore compatibility with Node.js 6
  .gitignore
  doc/1/api/controllers/admin/dump/index.md
  package-lock.json
  package.json
Labels: changelog:bug-fixes

#1463 Fix an unhandled promise rejection
  lib/api/controllers/adminController.js
  test/api/controllers/adminController.test.js
Labels: changelog:bug-fixes

#1464 Fix an unhandled promise rejection
  lib/api/controllers/adminController.js
  test/api/controllers/adminController.test.js
Labels: 2.x, changelog:bug-fixes

#1448 Plugins and protocols manifest files are now required
  doc/2/guides/migrate-from-v1/introduction/index.md
  doc/2/plugins/guides/manual-setup/prerequisites/index.md
  lib/api/core/entrypoints/index.js
  lib/api/core/entrypoints/protocolManifest.js
  lib/api/core/plugins/pluginManifest.js
  lib/api/core/plugins/pluginsManager.js
  test/api/core/entrypoints/index.test.js
  test/api/core/pluginsManager/init.test.js
  test/api/core/pluginsManager/manifest.test.js
Labels: 2.x, changelog:breaking-changes

#1445 Drop support for documents trashcan, garbage collector, and with the _meta tag
  .kuzzlerc.sample
  default.config.js
  doc/2/api/controllers/document/count/index.md
  doc/2/api/controllers/document/get/index.md
  doc/2/api/controllers/document/m-get/index.md
  doc/2/api/controllers/document/search/index.md
  doc/2/api/essentials/notifications/index.md
  doc/2/guides/essentials/document-metadata/index.md
  doc/2/guides/essentials/real-time/index.md
  doc/2/guides/essentials/store-access-data/index.md
  doc/2/guides/essentials/user-authentication/index.md
  doc/2/guides/migrate-from-v1/introduction/index.md
  lib/api/controllers/serverController.js
  lib/api/core/notifier.js
  lib/services/garbageCollector.js
  test/api/controllers/securityController/profiles.test.js
  test/api/controllers/securityController/roles.test.js
  test/api/core/notifier/notifyDocumentMDelete.test.js
  test/api/core/notifier/notifyDocumentReplace.test.js
  test/api/core/notifier/notifyDocumentUpdate.test.js
  test/services/garbageCollector.test.js
Labels: 2.x, changelog:breaking-changes

#1421 Add ability to use errorsManager in plugins
  lib/api/core/plugins/pluginContext.js
  lib/api/core/plugins/pluginsManager.js
  lib/config/error-codes/index.js
  lib/config/error-codes/internal.json
  lib/config/error-codes/plugins.json
  lib/config/error-codes/throw.js
  test/api/core/pluginsManager/init.test.js
Labels: 2.x, changelog:exclude

#1456 Fix admin:resetSecurity result typo and documentation
  doc/2/api/controllers/admin/reset-security/index.md
  lib/api/controllers/adminController.js
Labels: 2.x, changelog:bug-fixes

#1468 Fix CLI start --enable-plugin command
  bin/commands/start.js
  docker-compose/scripts/run.sh
  package-lock.json
  package.json
Labels: changelog:bug-fixes, priority-high

#1469 Make the connection headers writable again
  lib/api/core/entrypoints/embedded/clientConnection.js
  test/api/core/entrypoints/embedded/clientConnection.test.js
  test/api/core/entrypoints/embedded/index.test.js
Labels: changelog:bug-fixes

#1466 Support unicode string in notifications
  lib/api/core/entrypoints/embedded/protocols/websocket.js
  test/api/core/entrypoints/embedded/protocols/websocket.test.js
Labels: changelog:bug-fixes

#1467 Support unicode payload in notifications
  lib/api/core/entrypoints/protocols/websocket.js
  test/api/core/entrypoints/protocols/websocket.test.js
Labels: 2.x, changelog:bug-fixes

#1471 Fix CLI start --enable-plugin command
  bin/commands/start.js
  docker-compose/scripts/run.sh
Labels: 2.x, changelog:bug-fixes

#1470 Make the connection headers writable again
  lib/api/core/entrypoints/clientConnection.js
  test/api/core/entrypoints/clientConnection.test.js
  test/api/core/entrypoints/index.test.js
Labels: changelog:bug-fixes

#1472 Remove CLI commands
  .ci/test-aarch64.yml
  .ci/test-armhf.yml
  .ci/test.yml
  bin/README.md
  bin/build-cli.js
  bin/colorOutput.js
  bin/commands/clearCache.js
  bin/commands/createFirstAdmin.js
  bin/commands/decryptSecrets.js
  bin/commands/dump.js
  bin/commands/encryptSecrets.js
  bin/commands/getSdk.js
  bin/commands/indexDump.js
  bin/commands/indexRestore.js
  bin/commands/loadFixtures.js
  bin/commands/loadJson.js
  bin/commands/loadMappings.js
  bin/commands/loadSecurities.js
  bin/commands/resetDatabase.js
  bin/commands/resetKuzzleData.js
  bin/commands/resetSecurity.js
  bin/commands/shutdown.js
  bin/commands/start.js
  bin/kuzzle
  bin/start-kuzzle-server
  doc/2/guides/migrate-from-v1/introduction/index.md
  docker-compose.yml
  docker-compose/config/pm2-dev.json
  docker-compose/scripts/run-dev.sh
  docker-compose/scripts/run.sh
  features/kuzzle.feature
  package-lock.json
  package.json
  test/bin/commands/start.test.js
Labels: changelog:breaking-changes

#1475 Adapt script to push major tag to Dockerhub
  build-docker-images.sh
Labels: changelog:exclude

#1480 Allow to dynamically add strategy in the pugin init method
  lib/api/core/plugins/pluginsManager.js
Labels: 2.x, changelog:bug-fixes, wip
