Repository kuzzleio/kuzzle, pull requests merged in 2019-02, with the labels that each got.

#1240 Fix unhandled error in mqtt when requestId is not a string
  .kuzzlerc.sample
  default.config.js
  lib/api/core/entrypoints/embedded/protocols/mqtt.js
  test/api/core/entrypoints/embedded/protocols/mqtt.test.js
  test/mocks/services/elasticsearchClient.mock.js
Labels: changelog:bug-fixes

#1237 Pipe plugins throwing error will bypass triggerPipes error management
  lib/api/core/plugins/pluginsManager.js
  test/api/core/pluginsManager/trigger.test.js
Labels: changelog:bug-fixes

#1242 Provide a meaningful feedback when an invalid kuid is returned by a plugin
  lib/api/core/plugins/pluginsManager.js
  test/api/core/pluginsManager/strategy.test.js
Labels: changelog:enhancements

#1239 Fix createFirstAdmin HTTP route
  features/support/api/http.js
  lib/config/httpRoutes.js
Labels: changelog:bug-fixes, need-documentation

#1249 Fix SDK constructor in CLI's sendAction
  bin/commands/sendAction.js
Labels: changelog:bug-fixes

#1252 [dependencies] Upgrade kuzzle sdk version
  package-lock.json
  package.json
Labels: changelog:exclude

#1246 Remove deprecation warnings from unit tests output
  test/api/core/pluginContext/pluginContext.test.js
Labels: changelog:exclude

#1250 Make "collection:getSpecifications" error messages meaningful
  lib/api/controllers/collectionController.js
  test/api/controllers/collectionController.test.js
Labels: changelog:enhancements
