Repository kuzzleio/kuzzle, pull requests merged in 2019-06, with the labels that each got.

#1301 Upgrade the WebSocket libraries
  .kuzzlerc.sample
  default.config.js
  features/support/api/websocket.js
  lib/api/core/entrypoints/embedded/index.js
  lib/api/core/entrypoints/embedded/protocols/http.js
  lib/api/core/entrypoints/embedded/protocols/mqtt.js
  lib/api/core/entrypoints/embedded/protocols/protocol.js
  lib/api/core/entrypoints/embedded/protocols/socketio.js
  lib/api/core/entrypoints/embedded/protocols/websocket.js
  lib/services/broker/wsBrokerClient.js
  lib/services/broker/wsBrokerServer.js
  package-lock.json
  package.json
  test/api/core/entrypoints/embedded/index.test.js
  test/api/core/entrypoints/embedded/protocols/http.test.js
  test/api/core/entrypoints/embedded/protocols/websocket.test.js
  test/services/implementations/broker.test.js
Labels: changelog:enhancements

#1313 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/issue_template/bug.md
Labels: changelog:exclude

#1311 Fix promise leaks
  lib/api/controllers/documentController.js
  lib/api/controllers/realtimeController.js
  lib/api/core/auth/tokenManager.js
  lib/api/core/hotelClerk.js
  lib/api/core/notifier.js
  test/api/controllers/documentController.test.js
  test/api/controllers/realtimeController.test.js
  test/api/core/auth/tokenManager.test.js
  test/api/core/hotelClerk/removeCustomerFromAllRooms.test.js
  test/api/core/hotelClerk/removeRoomForCustomer.test.js
  test/api/core/hotelClerk/removeSubscription.test.js
  test/api/core/notifier/notifyDocumentMDelete.test.js
  test/api/core/notifier/notifyDocumentReplace.test.js
  test/api/core/notifier/notifyDocumentUpdate.test.js
  test/api/core/notifier/notifyMethods.test.js
  test/api/core/notifier/publish.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:bug-fixes

#1314 Remove _id from bulk:write 2e route
  features/support/api/http.js
  lib/api/kuzzle.js
  lib/config/httpRoutes.js
Labels: changelog:exclude

#1316 [hotfix] notifier `cache` and `storage` set to `undefined`
  .travis.yml
  lib/api/core/notifier.js
Labels: changelog:bug-fixes, changelog:exclude

#1318 Add a maximum ttl to auth:login
  .kuzzlerc.sample
  default.config.js
  lib/api/core/models/repositories/tokenRepository.js
  test/api/core/models/repositories/tokenRepository.test.js
Labels: changelog:new-features, changelog:securities

#1315 Add the new Vault module to handle encrypted application secrets
  .gitignore
  bin/commands/decryptSecrets.js
  bin/commands/encryptSecrets.js
  bin/kuzzle
  config/.keep
  docker-compose/dev.yml
  features/kuzzle.feature
  features/step_definitions/cli.js
  lib/api/core/plugins/pluginContext.js
  lib/api/core/vault.js
  lib/api/kuzzle.js
  test/api/core/pluginContext/pluginContext.test.js
  test/api/core/vault.test.js
  test/api/kuzzle.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:new-features

#1323 Prevent using an incompatible version of the Javascript SDK
  package-lock.json
  package.json
  plugins/protocols/available/.gitignore
  plugins/protocols/enabled/.gitignore
Labels: changelog:bug-fixes

#1326 Fix vault encryption
  bin/commands/decryptSecrets.js
  lib/api/core/vault.js
  package-lock.json
  package.json
  test/api/core/vault.test.js
Labels: changelog:bug-fixes

#1324 Add document global events (database:*)
  features/step_definitions/deleteDocument.js
  lib/api/controllers/funnelController.js
  lib/config/documentEventAliases.js
  lib/util/DocumentExtractor.js
  test/api/controllers/funnelController/performDocumentAlias.test.js
  test/api/controllers/funnelController/processRequest.test.js
  test/util/DocumentExtractor.test.js
Labels: changelog:new-features, do-not-merge, need-documentation

#1327 Fix es bulk precondition error message
  lib/services/elasticsearch.js
  test/services/implementations/elasticsearch.test.js
Labels: changelog:bug-fixes

#1321 [ci] functional tests on node 10. Test on travis
  .ci/scripts/run-test.sh
  .ci/sonar.sh
  .travis.yml
Labels: changelog:enhancements

#1331 Allow env or default value in vault cli
  bin/commands/decryptSecrets.js
  bin/commands/encryptSecrets.js
  bin/kuzzle
  lib/api/core/vault.js
  test/api/core/vault.test.js
Labels: changelog:enhancements

#1337 Make the Kuzzle return a BadRequestException if it receives an invalid Content-Type header
  lib/api/core/entrypoints/embedded/protocols/http.js
  package-lock.json
  package.json
  test/api/core/entrypoints/embedded/protocols/http.test.js
Labels: changelog:bug-fixes, changelog:securities

#1339 Remove Sonarqube cache
  .travis.yml
Labels: changelog:exclude
