Repository kuzzleio/kuzzle, pull requests merged in 2019-12, with the labels that each got.

#1540 API documentation: fix index:create response example
  doc/2/api/controllers/index/create/index.md
Labels: 2.x, changelog:exclude

#1539 Fix URL parsing w/ trailing slash & querystring
  lib/core/httpRouter/index.js
  lib/core/httpRouter/routePart.js
  test/core/httpRouter/httpRouter.test.js
Labels: 2.x, changelog:bug-fixes

#1536 Prevent overloads caused by pre-funnel pipes
  .kuzzlerc.sample
  default.config.js
  doc/2/api/essentials/errors/codes/index.md
  lib/config/error-codes/plugin.json
  lib/core/httpRouter/index.js
  lib/core/plugins/manager.js
  lib/core/plugins/pipeRunner.js
  lib/core/router.js
  lib/kuzzle.js
  test/core/plugins/manager/pipe.test.js
  test/core/plugins/manager/pipeRunner.test.js
  test/core/router/httpRequest.test.js
  test/core/router/router.test.js
  test/mocks/kuzzle.mock.js
Labels: 2.x, changelog:enhancements

#1534 Configured server limit were not applied to some m* and deleteByQuery routes
  doc/2/api/controllers/collection/truncate/index.md
  doc/2/api/controllers/document/delete-by-query/index.md
  doc/2/api/controllers/document/m-create-or-replace/index.md
  doc/2/api/controllers/document/m-create/index.md
  doc/2/api/controllers/document/m-delete/index.md
  doc/2/api/controllers/document/m-get/index.md
  doc/2/api/controllers/document/m-replace/index.md
  doc/2/api/controllers/document/m-update/index.md
  features/run.sh
  lib/api/controllers/base.js
  lib/api/controllers/document.js
  lib/api/controllers/security.js
  lib/config/error-codes/services.json
  lib/services/elasticsearch.js
  test/api/controllers/document.test.js
  test/services/elasticsearch.test.js
Labels: 2.x, changelog:bug-fixes

#1533 Add plugin version to server info
  default.config.js
  features-sdk/ServerController.feature
  features-sdk/step_definitions/controllers-steps.js
  features-sdk/support/assertions.js
  features/kuzzle.feature
  features/step_definitions/serverController.js
  features/support/api/apiBase.js
  features/support/api/http.js
  lib/api/controllers/server.js
  lib/core/plugins/manager.js
  plugins/available/functional-test-plugin/package.json
  test/core/plugins/manager/init.test.js
Labels: changelog:enhancements

#1538 Fix URL parsing w/ trailing slash & querystring
  lib/api/core/httpRouter/index.js
  lib/api/core/httpRouter/routePart.js
  test/api/core/httpRouter/httpRouter.test.js
Labels: 1.x, changelog:bug-fixes

#1545 Fix default secret file loading
  doc/2/guides/essentials/secrets-vault/index.md
  lib/kuzzle.js
  package-lock.json
  package.json
  test/kuzzle.test.js
Labels: 2.x, changelog:bug-fixes

#1519 Use document mGet route in GET
  doc/2/api/controllers/document/m-get/index.md
  features-sdk/DocumentController.feature
  features-sdk/PluginEvents.feature
  features-sdk/SecurityController.feature
  features-sdk/step_definitions/documents-steps.js
  lib/api/controllers/document.js
  lib/config/httpRoutes.js
  lib/util/DocumentExtractor.js
  test/util/DocumentExtractor.test.js
Labels: 2.x, changelog:enhancements

#1552 Keep kuzzle_info after truncating a collection
  doc/2/api/controllers/collection/get-mapping/index.md
  features-sdk/CollectionController.feature
  features-sdk/DocumentController.feature
  features-sdk/support/assertions.js
  features/kuzzle.feature
  lib/services/elasticsearch.js
Labels: changelog:bug-fixes
