Repository kuzzleio/kuzzle, pull requests merged in 2019-03, with the labels that each got.

#1254 Fix return values authorized for pipes
  lib/api/core/notifier.js
  lib/api/core/plugins/pluginsManager.js
  package-lock.json
  package.json
  test/api/core/pluginsManager/run.test.js
Labels: changelog:bug-fixes

#1256 Https for development stack
  CONTRIBUTING.md
  docker-compose/dev.yml
  docker-compose/haproxy/haproxy.cfg
  docker-compose/haproxy/snakeoil.pem
  docker-compose/nginx/kuzzle.conf
  docker-compose/nginx/kuzzle.loc.crt
  docker-compose/nginx/kuzzle.loc.key
  docker-compose/nginx/kuzzleCA.crt
Labels: changelog:exclude

#1259 [http] Allow configuration of CORS methods & headers
  .kuzzlerc.sample
  default.config.js
  lib/api/core/httpRouter/index.js
  test/api/controllers/routerController/httpRequest.test.js
  test/api/core/httpRouter/httpRouter.test.js
Labels: changelog:enhancements

#1255 Add loading of fixtures mappings securities admin controller
  bin/commands/loadFixtures.js
  bin/commands/loadJson.js
  bin/commands/loadMappings.js
  bin/commands/loadSecurities.js
  bin/commands/start.js
  bin/kuzzle
  lib/api/controllers/adminController.js
  lib/api/core/janitor.js
  test/api/controllers/adminController.test.js
  test/api/core/janitor.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:enhancements, need-documentation

#1245 KZL-1005 - Add method to use request context in SDK queries
  lib/api/core/plugins/pluginContext.js
  lib/api/core/sdk/funnelProtocol.js
  package-lock.json
  test/api/core/pluginContext/pluginContext.test.js
  test/api/core/sdk/funnelProtocol.test.js
Labels: changelog:enhancements

#1266 Fix controllers action leak
  lib/api/controllers/adminController.js
  lib/api/controllers/authController.js
  lib/api/controllers/bulkController.js
  lib/api/controllers/collectionController.js
  lib/api/controllers/controller.js
  lib/api/controllers/documentController.js
  lib/api/controllers/funnelController.js
  lib/api/controllers/indexController.js
  lib/api/controllers/memoryStorageController.js
  lib/api/controllers/realtimeController.js
  lib/api/controllers/securityController.js
  lib/api/controllers/serverController.js
  test/api/controllers/adminController.test.js
  test/api/controllers/authController.test.js
  test/api/controllers/baseController.test.js
  test/api/controllers/bulkController.test.js
  test/api/controllers/collectionController.test.js
  test/api/controllers/documentController.test.js
  test/api/controllers/funnelController/executePluginRequest.test.js
  test/api/controllers/funnelController/handleProcessRequestError.test.js
  test/api/controllers/funnelController/processRequest.test.js
  test/api/controllers/indexController.test.js
  test/api/controllers/memoryStorageController.test.js
  test/api/controllers/realtimeController.test.js
  test/api/controllers/securityController/createFirstAdmin.test.js
  test/api/controllers/securityController/index.js
  test/api/controllers/serverController.test.js
  test/api/core/entrypoints/embedded/index.test.js
  test/api/core/entrypoints/embedded/protocols/mqtt.test.js
  test/mocks/controller.mock.js
  test/mocks/kuzzle.mock.js
Labels: changelog:bug-fixes

#1267 Fix the "IsAuthenticated" assertion
  lib/api/controllers/authController.js
  lib/api/controllers/controller.js
  lib/api/controllers/funnelController.js
  lib/api/kuzzle.js
  lib/util/requestAssertions.js
  test/api/controllers/authController.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:bug-fixes

#1260 Update readme
  README.md
Labels: changelog:exclude

#1262 Increase the nofiles ulimit
  docker-compose/dev.yml
Labels: changelog:exclude

#1261 [dependencies] update dependencies
  package-lock.json
  package.json
  test/api/core/indexCache.test.js
  test/api/core/notifier/notifyDocumentMDelete.test.js
  test/api/core/notifier/notifyDocumentReplace.test.js
  test/api/core/notifier/notifyDocumentUpdate.test.js
Labels: changelog:exclude

#1269 Fix aggregations for the security:searchXxx API routes
  lib/services/internalEngine/index.js
  test/api/controllers/securityController/users.test.js
  test/services/internalEngine/index.test.js
Labels: changelog:bug-fixes

#1263 Change start sequence for mappings, fixtures and securities
  bin/commands/start.js
  lib/api/core/janitor.js
  lib/api/kuzzle.js
  package-lock.json
  test/api/kuzzle.test.js
Labels: changelog:bug-fixes

#1270 Remove useless format property for winston logs
  .kuzzlerc.sample
  default.config.js
Labels: changelog:exclude

#1265 KZL-508 - auth:refreshToken
  .kuzzlerc.sample
  default.config.js
  features/kuzzle.feature
  features/step_definitions/authentication.js
  features/support/api/apiBase.js
  features/support/api/http.js
  lib/api/controllers/authController.js
  lib/api/core/auth/tokenManager.js
  lib/api/core/models/security/token.js
  lib/config/httpRoutes.js
  package-lock.json
  test/api/controllers/authController.test.js
  test/api/core/auth/tokenManager.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:new-features

#1272 fix regression injected by #1263
  bin/commands/start.js
Labels: changelog:exclude

#1277 Fix documentation links
  .kuzzlerc.sample
  CONTRIBUTING.md
  bin/commands/start.js
Labels: changelog:exclude

#1278 Fix fixtures loading on start
  .kuzzlerc.sample
  CONTRIBUTING.md
  bin/commands/start.js
  docker-compose/config/pm2-dev.json
  docker-compose/dev.yml
  docker-compose/fixtures/fixtures.json
  docker-compose/fixtures/mappings.json
  docker-compose/fixtures/securities.json
  package-lock.json
  package.json
  test/bin/commands/start.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:bug-fixes, priority-high
