Repository kuzzleio/kuzzle, pull requests merged in 2019-01, with the labels that each got.

#1229 Add explicit errors message when misusing the pipes
  lib/api/core/plugins/pluginsManager.js
  package-lock.json
  package.json
  test/api/core/pluginsManager/run.test.js
Labels: changelog:enhancements

#1231 Es aliases compatibility
  lib/api/core/indexCache.js
  lib/services/internalEngine/index.js
  test/api/core/indexCache.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:bug-fixes

#1234 Fix SDK dependency
  package-lock.json
  package.json
Labels: changelog:bug-fixes

#1236 [README] Fix typos
  README.md
Labels: changelog:enhancements

#1227 Allow usage of a function with plugin hook, pipe and controller actions
  lib/api/core/plugins/pluginContext.js
  lib/api/core/plugins/pluginsManager.js
  package-lock.json
  test/api/core/pluginsManager/run.test.js
Labels: changelog:enhancements

#1235 Allow to set request error for request:onError pipes
  lib/api/controllers/funnelController.js
  test/api/controllers/funnelController/handleProcessRequestError.test.js
Labels: changelog:bug-fixes

#1238 Release 1.6.0
  .ci/scripts/run-test.sh
  .ci/test-aarch64.yml
  .ci/test-armhf.yml
  .ci/test.yml
  .kuzzlerc.sample
  Dockerfile
  README.md
  cucumber.js
  default.config.js
  docker-compose/dev.yml
  features/run.sh
  features/support/api/mqtt.js
  features/support/world.js
  lib/api/controllers/funnelController.js
  lib/api/core/entrypoints/embedded/index.js
  lib/api/core/entrypoints/embedded/protocols/mqtt.js
  lib/api/core/indexCache.js
  lib/api/core/plugins/pluginContext.js
  lib/api/core/plugins/pluginsManager.js
  lib/services/internalEngine/index.js
  lib/util/deprecate.js
  package-lock.json
  package.json
  test/api/controllers/funnelController/handleProcessRequestError.test.js
  test/api/core/entrypoints/embedded/protocols/mqtt.test.js
  test/api/core/indexCache.test.js
  test/api/core/pluginContext/pluginContext.test.js
  test/api/core/pluginsManager/run.test.js
  test/mocks/kuzzle.mock.js
  test/util/deprecate.test.js
Labels: release
