Repository kuzzleio/kuzzle, pull requests merged in 2019-05, with the labels that each got.

#1295 fixes #1243 - improve validation error messages
  lib/api/controllers/documentController.js
  lib/api/controllers/realtimeController.js
  lib/api/core/plugins/pluginContext.js
  lib/api/core/validation/index.js
  test/api/controllers/documentController.test.js
  test/api/controllers/realtimeController.test.js
  test/api/core/pluginContext/pluginContext.test.js
  test/api/core/validation/validate.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:enhancements

#1297 Fix timeouts on plugin action returing the request
  lib/api/controllers/funnelController.js
  test/api/controllers/funnelController/processRequest.test.js
Labels: changelog:bug-fixes

#1300 [KZL-522] Collection specifications methods cloisoned to a collection
  features/kuzzle.feature
  features/step_definitions/validation.js
  features/support/api/apiBase.js
  features/support/api/http.js
  lib/api/controllers/collectionController.js
  lib/config/httpRoutes.js
  test/api/controllers/collectionController.test.js
Labels: changelog:enhancements

#1298 Fix disabled protocol initialization
  lib/api/core/entrypoints/embedded/index.js
  lib/api/core/entrypoints/embedded/protocols/http.js
  lib/api/core/entrypoints/embedded/protocols/mqtt.js
  lib/api/core/entrypoints/embedded/protocols/protocol.js
  lib/api/core/entrypoints/embedded/protocols/socketio.js
  lib/api/core/entrypoints/embedded/protocols/websocket.js
  lib/api/core/httpRouter/index.js
  lib/services/broker/index.js
  test/api/core/entrypoints/embedded/index.test.js
  test/api/core/entrypoints/embedded/protocols/http.test.js
  test/api/core/entrypoints/embedded/protocols/mqtt.test.js
  test/api/core/entrypoints/embedded/protocols/socketio.test.js
  test/api/core/entrypoints/embedded/protocols/websocket.test.js
Labels: changelog:bug-fixes

#1307 Hotfix: correctly compute mUpdate notifications against the updated document
  lib/services/elasticsearch.js
  package-lock.json
  package.json
  test/services/implementations/elasticsearch.test.js
Labels: changelog:bug-fixes, priority-blocking

#1305 [KZL-291] pipes & hooks: wildcarded event
  lib/api/core/plugins/pluginsManager.js
  lib/api/kuzzle.js
  package.json
  test/api/core/pluginsManager/run.test.js
  test/api/core/pluginsManager/trigger.test.js
  test/mocks/services/redisClient.mock.js
Labels: changelog:new-features

#1302 Add write and mWrite
  features/kuzzle.feature
  features/step_definitions/bulk.js
  features/support/api/apiBase.js
  features/support/api/http.js
  lib/api/controllers/bulkController.js
  lib/api/controllers/collectionController.js
  lib/api/controllers/controller.js
  lib/api/core/plugins/pluginContext.js
  lib/config/httpRoutes.js
  lib/services/elasticsearch.js
  test/api/controllers/baseController.test.js
  test/api/controllers/bulkController.test.js
  test/services/implementations/elasticsearch.test.js
Labels: changelog:new-features, need-documentation

#1310 Fix CLI login, credentials not sent
  bin/commands/sendAction.js
  package-lock.json
  package.json
Labels: changelog:bug-fixes, priority-high

#1308 Events triggering refactor
  lib/api/controllers/authController.js
  lib/api/controllers/collectionController.js
  lib/api/controllers/documentController.js
  lib/api/controllers/funnelController.js
  lib/api/controllers/routerController.js
  lib/api/core/auth/formatProcessing.js
  lib/api/core/entrypoints/embedded/context.js
  lib/api/core/entrypoints/embedded/index.js
  lib/api/core/entrypoints/embedded/protocols/mqtt.js
  lib/api/core/entrypoints/embedded/protocols/socketio.js
  lib/api/core/entrypoints/embedded/protocols/websocket.js
  lib/api/core/hotelClerk.js
  lib/api/core/httpRouter/index.js
  lib/api/core/indexCache.js
  lib/api/core/models/repositories/profileRepository.js
  lib/api/core/models/repositories/roleRepository.js
  lib/api/core/models/security/role.js
  lib/api/core/notifier.js
  lib/api/core/plugins/pluginContext.js
  lib/api/core/plugins/pluginsManager.js
  lib/api/core/validation/index.js
  lib/api/kuzzle.js
  lib/services/broker/index.js
  lib/services/broker/wsBrokerClient.js
  lib/services/broker/wsBrokerServer.js
  lib/services/elasticsearch.js
  lib/services/garbageCollector.js
  lib/services/internalEngine/bootstrap.js
  lib/services/redis.js
  test/api/controllers/authController.test.js
  test/api/controllers/collectionController.test.js
  test/api/controllers/funnelController/checkRights.test.js
  test/api/controllers/funnelController/execute.test.js
  test/api/controllers/funnelController/executePluginRequest.test.js
  test/api/controllers/funnelController/handleProcessRequestError.test.js
  test/api/controllers/funnelController/processRequest.test.js
  test/api/controllers/routerController/httpRequest.test.js
  test/api/controllers/routerController/routerController.test.js
  test/api/core/entrypoints/embedded/index.test.js
  test/api/core/entrypoints/embedded/protocols/socketio.test.js
  test/api/core/entrypoints/embedded/protocols/websocket.test.js
  test/api/core/hotelClerk/removeCustomerFromAllRooms.test.js
  test/api/core/httpRouter/httpRouter.test.js
  test/api/core/models/repositories/profileRepository.test.js
  test/api/core/models/repositories/roleRepository.test.js
  test/api/core/notifier/notifyMethods.test.js
  test/api/core/pluginContext/pluginContext.test.js
  test/api/core/pluginsManager/pipe.test.js
  test/api/core/pluginsManager/run.test.js
  test/api/core/validation/init.test.js
  test/api/kuzzle.test.js
  test/mocks/kuzzle.mock.js
  test/mocks/services/ws.mock.js
  test/services/garbageCollector.test.js
  test/services/implementations/broker.test.js
  test/services/implementations/elasticsearch.test.js
Labels: changelog:enhancements
