Repository kuzzleio/kuzzle, pull requests merged in 2019-08, with the labels that each got.

#1370 Remove superfluous protocols related directories
  plugins/protocols/available/.gitignore
  plugins/protocols/enabled/.gitignore
Labels: changelog:exclude

#1365 Do not check for a connection existence if none is set
  doc/doc.sh
  lib/api/controllers/funnelController.js
  lib/api/controllers/routerController.js
  lib/api/core/entrypoints/proxy/index.js
  lib/api/core/httpRouter/index.js
  lib/api/core/httpRouter/routeHandler.js
  test/api/controllers/funnelController/execute.test.js
  test/api/controllers/routerController/routerController.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:bug-fixes

#1356 Dependencies update
  lib/api/controllers/securityController.js
  lib/api/core/plugins/pluginsManager.js
  lib/api/core/validation/index.js
  lib/api/core/validation/types/date.js
  lib/api/core/validation/types/email.js
  lib/api/core/validation/types/enum.js
  lib/api/core/validation/types/geoShape.js
  lib/api/core/validation/types/ipAddress.js
  lib/api/core/validation/types/numeric.js
  lib/api/core/validation/types/object.js
  lib/api/core/validation/types/string.js
  lib/api/core/validation/types/url.js
  lib/config/error-codes/index.js
  lib/services/elasticsearch.js
  lib/util/requestAssertions.js
  package-lock.json
  package.json
  test/api/core/validation/init.test.js
  test/api/core/validation/types/integer.test.js
  test/api/core/validation/types/numeric.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:enhancements

#1367 [debug] add a few debug calls to request processing
  lib/api/controllers/funnelController.js
  lib/api/core/entrypoints/embedded/index.js
Labels: changelog:exclude

#1358 Add subcodes to Plugins core service
  lib/api/core/entrypoints/proxy/index.js
  lib/api/core/plugins/manifest.js
  lib/api/core/plugins/pluginContext.js
  lib/api/core/plugins/pluginsManager.js
  lib/api/core/sandbox/index.js
  lib/config/error-codes/index.js
  lib/config/error-codes/plugins.json
Labels: changelog:enhancements

#1362 Add subcodes core embedded entrypoint
  lib/api/core/entrypoints/embedded/clientConnection.js
  lib/api/core/entrypoints/embedded/index.js
  lib/api/core/entrypoints/embedded/service/httpFormDataStream.js
  lib/api/core/entrypoints/index.js
  lib/config/error-codes/entrypoints.json
  lib/config/error-codes/index.js
  test/api/core/entrypoints/embedded/index.test.js
Labels: changelog:enhancements

#1361 Add subcodes to Protocols
  lib/api/core/entrypoints/embedded/protocols/http.js
  lib/api/core/entrypoints/embedded/protocols/mqtt.js
  lib/api/core/entrypoints/embedded/protocols/websocket.js
  lib/api/core/indexCache.js
  lib/config/error-codes/index.js
  lib/config/error-codes/protocols.json
  lib/config/error-codes/throw.js
  test/api/core/entrypoints/embedded/index.test.js
  test/api/core/entrypoints/embedded/protocols/http.test.js
  test/api/core/entrypoints/embedded/protocols/mqtt.test.js
  test/api/core/entrypoints/embedded/protocols/websocket.test.js
  test/util/errorMatcher.js
Labels: changelog:enhancements

#1357 Add subcodes to Validation core service
  lib/api/core/validation/baseType.js
  lib/api/core/validation/index.js
  lib/api/core/validation/types/date.js
  lib/api/core/validation/types/email.js
  lib/api/core/validation/types/enum.js
  lib/api/core/validation/types/geoShape.js
  lib/api/core/validation/types/ipAddress.js
  lib/api/core/validation/types/numeric.js
  lib/api/core/validation/types/object.js
  lib/api/core/validation/types/string.js
  lib/api/core/validation/types/url.js
  lib/config/error-codes/internal.json
  lib/services/elasticsearch.js
  test/api/core/validation/types/date.test.js
  test/api/core/validation/types/email.test.js
  test/api/core/validation/types/enum.test.js
  test/api/core/validation/types/geoShape.test.js
  test/api/core/validation/types/ipAddress.test.js
  test/api/core/validation/types/numeric.test.js
  test/api/core/validation/types/object.test.js
  test/api/core/validation/types/string.test.js
  test/api/core/validation/types/url.test.js
  test/api/core/validation/util.test.js
Labels: changelog:enhancements

#1360 Make some realtime API actions available to plugins
  doc/1/plugins/plugin-context/accessors/sdk/index.md
  doc/doc.sh
  lib/api/core/plugins/pluginContext.js
  lib/api/core/sdk/funnelProtocol.js
  lib/config/error-codes/internal.json
  lib/config/error-codes/plugins.json
  test/api/core/pluginContext/pluginContext.test.js
  test/api/core/sdk/funnelProtocol.test.js
Labels: changelog:enhancements

#1375 Always set the content length for HTTP responses
  lib/api/core/entrypoints/embedded/protocols/http.js
  test/api/core/entrypoints/embedded/protocols/http.test.js
  test/util/errorMatcher.js
Labels: changelog:bug-fixes

#1379 Allow "type" mapping property for nested objects
  lib/services/elasticsearch.js
  package-lock.json
  package.json
  test/services/implementations/elasticsearch.test.js
Labels: changelog:bug-fixes

#1373 Add cli dump indexes doc
  doc/1/guides/essentials/cli/index.md
  doc/1/guides/essentials/real-time/index.md
Labels: changelog:exclude

#1333 Add subcodes to kuzzle core entrypoints
  lib/api/controllers/adminController.js
  lib/api/controllers/authController.js
  lib/api/controllers/baseController.js
  lib/api/controllers/bulkController.js
  lib/api/controllers/collectionController.js
  lib/api/controllers/documentController.js
  lib/api/controllers/funnelController.js
  lib/api/controllers/indexController.js
  lib/api/controllers/memoryStorageController.js
  lib/api/controllers/realtimeController.js
  lib/api/controllers/routerController.js
  lib/api/controllers/securityController.js
  lib/api/controllers/serverController.js
  lib/api/core/hotelClerk.js
  lib/config/error-codes/api.json
  lib/config/error-codes/internal.json
  test/api/controllers/adminController.test.js
  test/api/controllers/authController.test.js
  test/api/controllers/baseController.test.js
  test/api/controllers/collectionController.test.js
  test/api/controllers/documentController.test.js
  test/api/controllers/funnelController/executePluginRequest.test.js
  test/api/controllers/funnelController/processRequest.test.js
  test/api/controllers/memoryStorageController.test.js
  test/api/controllers/securityController/credentials.test.js
  test/api/controllers/securityController/index.js
  test/api/controllers/securityController/profiles.test.js
  test/api/controllers/securityController/roles.test.js
  test/api/controllers/securityController/users.test.js
  test/api/controllers/serverController.test.js
  test/api/core/hotelClerk/removeRooms.test.js
  test/api/kuzzle.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:enhancements

#1364 Add the fields that triggered update notifications
  features/kuzzle.feature
  features/step_definitions/notifications.js
  lib/api/core/notifier.js
  test/api/core/notifier/notifyDocumentUpdate.test.js
Labels: changelog:enhancements

#1371 Fix erroneous protocols.execute documentation
  doc/1/protocols/api/entrypoint/execute/index.md
Labels: changelog:exclude

#1374 Add revokeTokens route to Security Controller
  doc/1/api/controllers/security/revoke-tokens/index.md
  features/kuzzle.feature
  features/step_definitions/users.js
  features/support/api/apiBase.js
  features/support/api/http.js
  lib/api/controllers/securityController.js
  lib/config/httpRoutes.js
  test/api/controllers/securityController/users.test.js
Labels: changelog:new-features

#1376 Add subcodes for Redis service
  lib/config/error-codes/external.json
  lib/services/redis.js
Labels: changelog:enhancements

#1382 Fix lost subscriptions when authentication tokens expire
  .eslintrc.json
  features/kuzzle.feature
  features/support/api/websocketBase.js
  lib/api/core/auth/tokenManager.js
  lib/api/core/models/repositories/tokenRepository.js
  package-lock.json
  package.json
  test/api/core/auth/tokenManager.test.js
  test/api/core/models/repositories/tokenRepository.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:bug-fixes

#1383 Add more subcodes to controllers
  lib/api/controllers/authController.js
  lib/api/controllers/funnelController.js
  lib/api/controllers/routerController.js
  lib/api/controllers/securityController.js
  lib/api/core/models/repositories/profileRepository.js
  lib/api/core/models/repositories/repository.js
  lib/api/core/models/repositories/roleRepository.js
  lib/api/core/models/repositories/tokenRepository.js
  lib/api/core/models/repositories/userRepository.js
  lib/api/core/models/security/profile.js
  lib/api/core/models/security/role.js
  lib/api/core/models/security/user.js
  lib/config/error-codes/api.json
  lib/config/error-codes/plugins.json
  test/api/controllers/funnelController/processRequest.test.js
  test/api/core/models/repositories/profileRepository.test.js
  test/api/core/models/repositories/tokenRepository.test.js
Labels: changelog:enhancements

#1378 Add more subcodes error for PluginImplementationError
  lib/api/core/abstractManifest.js
  lib/api/core/auth/passportWrapper.js
  lib/api/core/plugins/pluginsManager.js
  lib/api/core/validation/index.js
  lib/config/error-codes/api.json
  lib/config/error-codes/plugins.json
  test/api/core/abstractManifest.test.js
  test/api/core/auth/passportWrapper.test.js
  test/api/core/pluginsManager/init.test.js
  test/api/core/pluginsManager/run.test.js
  test/api/core/validation/init.test.js
Labels: changelog:enhancements

#1377 Add subcodes to HttpRouter
  lib/api/core/entrypoints/embedded/index.js
  lib/api/core/entrypoints/embedded/protocols/http.js
  lib/api/core/entrypoints/embedded/protocols/mqtt.js
  lib/api/core/entrypoints/embedded/protocols/websocket.js
  lib/api/core/httpRouter/index.js
  lib/api/core/httpRouter/routeHandler.js
  lib/config/error-codes/api.json
  lib/config/error-codes/entrypoints.json
  lib/config/error-codes/external.json
  lib/config/error-codes/index.js
  lib/config/error-codes/network.json
  lib/config/error-codes/plugins.json
  lib/config/error-codes/protocols.json
  test/api/controllers/routerController/httpRequest.test.js
  test/api/core/entrypoints/embedded/protocols/http.test.js
  test/api/core/entrypoints/embedded/protocols/mqtt.test.js
  test/api/core/entrypoints/embedded/protocols/websocket.test.js
  test/api/core/httpRouter/httpRouter.test.js
Labels: changelog:enhancements

#1384 Fix dead link in plugin context introduction
  doc/1/plugins/plugin-context/accessors/intro/index.md
  doc/doc.sh
Labels: changelog:exclude

#1387 Add test for duplicates errors codes in config files
  lib/config/error-codes/api.json
  lib/config/error-codes/external.json
  lib/config/error-codes/index.js
  lib/config/error-codes/internal.json
Labels: changelog:enhancements

#1381 Add option to logout to revoke all sessions at once
  doc/1/api/controllers/auth/logout/index.md
  features/kuzzle.feature
  features/step_definitions/authentication.js
  features/support/api/apiBase.js
  lib/api/controllers/authController.js
  test/api/controllers/authController.test.js
Labels: changelog:enhancements

#1380 Fix wrong return value from collection truncate
  lib/api/controllers/collectionController.js
  test/api/controllers/collectionController.test.js
Labels: changelog:bug-fixes

#1389 Add more error subcodes in core components
  lib/api/core/sandbox/index.js
  lib/api/core/statistics.js
  lib/api/core/validation/index.js
  lib/config/error-codes/internal.json
Labels: changelog:enhancements

#1390 Add subcode to ESWrapper
  lib/config/error-codes/external.json
  lib/config/error-codes/throw.js
  lib/util/esWrapper.js
  test/api/kuzzle.test.js
  test/services/implementations/elasticsearch.test.js
  test/util/esWrapper.test.js
Labels: changelog:enhancements

#1394 Improve DRY with Anchors and add missing caches
  .ci/scripts/install-aarch64-deps.sh
  .ci/scripts/install-armhf-deps.sh
  .ci/scripts/run-test.sh
  .travis.yml
  doc/doc.sh
Labels: changelog:exclude

#1399 Add migration guide
  doc/2/guides/migrate-from-v1/index.md
  doc/2/guides/migrate-from-v1/introduction/index.md
Labels: 2.x, changelog:exclude

#1396 Document HotelClerk's core events
  doc/1/plugins/guides/events/core-hotelclerk-addSubscription/index.md
  doc/1/plugins/guides/events/core-hotelclerk-remove-room-for-customer/index.md
  lib/api/core/hotelClerk.js
Labels: changelog:exclude

#1402 Document HotelClerk's core events
  doc/2/plugins/guides/events/core-hotelclerk-addSubscription/index.md
  doc/2/plugins/guides/events/core-hotelclerk-remove-room-for-customer/index.md
  lib/api/core/hotelClerk.js
Labels: 2.x, changelog:exclude

#1404 Fix error codes generation
  lib/config/error-codes/throw.js
  test/api/kuzzle.test.js
  test/config/throw.test.js
Labels: changelog:exclude

#1398 Add subcodes documentation
  .travis.yml
  doc/1/api/essentials/errors/subcodes/index.md
  doc/generate-subcodes-doc.js
  package.json
Labels: changelog:exclude

#1406 Fix always succeeding tests
  test/api/core/httpRouter/httpRouter.test.js
Labels: changelog:exclude

#1407 Fix a crash occuring when trying to ping dead sockets
  .eslintrc.json
  lib/api/core/entrypoints/embedded/protocols/websocket.js
  test/api/core/entrypoints/embedded/protocols/websocket.test.js
Labels: changelog:bug-fixes

#1409 Add '--enable-plugins' option to 'start' CLI command
  bin/commands/indexRestore.js
  bin/commands/start.js
  bin/kuzzle
  doc/1/guides/essentials/cli/index.md
  lib/api/core/plugins/pluginsManager.js
  lib/api/kuzzle.js
  test/api/core/pluginsManager/init.test.js
  test/bin/commands/start.test.js
Labels: changelog:enhancements

#1411 Update Node.js version for Docker images
  Dockerfile
Labels: changelog:enhancements

#1414 Update Node.js version for Docker images
  Dockerfile
  lib/services/index.js
Labels: 2.x, changelog:enhancements

#1413 Add subcodes error to requestAssertions
  doc/1/api/essentials/errors/subcodes/index.md
  lib/config/error-codes/api.json
  lib/util/requestAssertions.js
Labels: changelog:enhancements

#1419 Add more error subcodes to Kuzzle
  doc/1/api/essentials/errors/subcodes/index.md
  lib/config/error-codes/internal.json
  lib/config/index.js
  lib/services/index.js
Labels: changelog:enhancements

#1422 allow some realtime methods from plugins
  lib/api/core/plugins/pluginContext.js
  lib/api/core/sdk/funnelProtocol.js
  package-lock.json
  package.json
  test/api/core/abstractManifest.test.js
  test/api/core/entrypoints/embedded/index.test.js
  test/api/core/pluginContext/pluginContext.test.js
  test/api/core/pluginsManager/init.test.js
  test/api/core/pluginsManager/manifest.js
  test/api/core/pluginsManager/manifest.test.js
  test/api/core/sdk/funnelProtocol.test.js
Labels: changelog:enhancements

#1417 Add event on new/removed connection
  doc/1/plugins/guides/events/connection-new/index.md
  doc/1/plugins/guides/events/connection-remove/index.md
  lib/api/core/entrypoints/embedded/clientConnection.js
  lib/api/core/entrypoints/embedded/index.js
  lib/api/core/entrypoints/embedded/protocols/http.js
  test/api/core/entrypoints/embedded/clientConnection.test.js
  test/api/core/entrypoints/embedded/index.test.js
Labels: changelog:enhancements

#1400 Fix building KuzzleErrors with non KuzzleError for errorsManager
  lib/api/controllers/authController.js
  lib/api/controllers/funnelController.js
  lib/api/core/auth/passportWrapper.js
  lib/api/core/entrypoints/embedded/protocols/http.js
  lib/api/core/plugins/pluginsManager.js
  lib/api/core/validation/index.js
  lib/config/error-codes/plugins.json
  lib/config/error-codes/throw.js
  test/api/controllers/funnelController/handleProcessRequestError.test.js
  test/api/core/auth/passportWrapper.test.js
  test/api/core/pluginsManager/run.test.js
  test/api/core/validation/init.test.js
Labels: changelog:bug-fixes

#1391 Add ability to use errorsManager in plugins
  doc/1/api/essentials/errors/subcodes/index.md
  doc/generate-subcodes-doc.js
  lib/api/core/plugins/pluginContext.js
  lib/api/core/plugins/pluginsManager.js
  lib/config/error-codes/index.js
  lib/config/error-codes/plugins.json
  lib/config/error-codes/throw.js
  test/api/core/notifier/notifyDocumentMDelete.test.js
  test/api/core/pluginsManager/init.test.js
Labels: changelog:enhancements
