Repository kuzzleio/kuzzle, pull requests merged in 2019-04, with the labels that each got.

#1283 Expose new admin:load* routes
  features/kuzzle.feature
  features/step_definitions/adminController.js
  features/support/api/apiBase.js
  features/support/api/http.js
  features/support/hooks.js
  lib/api/controllers/adminController.js
  lib/api/core/janitor.js
  lib/config/httpRoutes.js
  lib/util/requestAssertions.js
  package-lock.json
  package.json
  test/api/core/janitor.test.js
  test/api/kuzzle.test.js
  test/bin/commands/start.test.js
Labels: changelog:bug-fixes, priority-high

#1279 Users must be authenticated to use auth:logout
  lib/api/controllers/authController.js
  test/api/controllers/authController.test.js
Labels: changelog:bug-fixes

#1282 [bugfix] scan keys on redis cluster
  lib/services/redis.js
Labels: changelog:bug-fixes

#1273 Fix incomplete access logs
  lib/api/core/entrypoints/embedded/index.js
  lib/api/core/models/repositories/userRepository.js
  test/api/core/entrypoints/embedded/index.test.js
  test/api/core/entrypoints/embedded/protocols/http.test.js
Labels: changelog:enhancements

#1284 Cluster/functional tests
  cucumber.js
  features/kuzzle.feature
  features/step_definitions/notifications.js
  features/step_definitions/wait.js
  lib/api/core/hotelClerk.js
  test/api/core/hotelClerk/removeCustomerFromAllRooms.test.js
  test/api/core/hotelClerk/removeRoomForCustomer.test.js
  test/api/core/hotelClerk/removeSubscription.test.js
Labels: changelog:exclude

#1286 [bugfix] allows bulk inserts on aliases
  lib/services/elasticsearch.js
  test/mocks/services/elasticsearchClient.mock.js
  test/services/implementations/elasticsearch.test.js
Labels: changelog:bug-fixes, priority-high

#1289 [WebSocket] Handle ping/pong packets
  .kuzzlerc.sample
  default.config.js
  lib/api/core/entrypoints/embedded/index.js
  lib/api/core/entrypoints/embedded/protocols/mqtt.js
  lib/api/core/entrypoints/embedded/protocols/socketio.js
  lib/api/core/entrypoints/embedded/protocols/websocket.js
  test/api/core/entrypoints/embedded/protocols/websocket.test.js
Labels: changelog:enhancements

#1290 Add stackoverflow to issue template
  .github/issue_template.md
Labels: changelog:exclude

#1288 [bulk] fix an error when trying a non-partial bulk update
  lib/services/elasticsearch.js
  test/services/implementations/elasticsearch.test.js
Labels: changelog:bug-fixes

#1291 [Kuzzle CLI] Fix --help on subcommands
  bin/kuzzle
  package.json
Labels: changelog:enhancements

#1257 Add ability to define mapping policy for new fields
  .kuzzlerc.sample
  default.config.js
  docker-compose/scripts/run-dev.sh
  features/kuzzle.feature
  features/step_definitions/collections.js
  features/support/api/apiBase.js
  features/support/api/http.js
  lib/api/controllers/collectionController.js
  lib/api/controllers/controller.js
  lib/api/core/indexCache.js
  lib/api/core/janitor.js
  lib/services/elasticsearch.js
  lib/services/internalEngine/index.js
  lib/util/esWrapper.js
  package-lock.json
  package.json
  test/api/controllers/baseController.test.js
  test/api/core/indexCache.test.js
  test/api/core/janitor.test.js
  test/mocks/kuzzle.mock.js
  test/services/implementations/elasticsearch.test.js
  test/services/internalEngine/index.test.js
  test/util/esWrapper.test.js
Labels: changelog:enhancements

#1292 KZL 1032 - Throw an error when the realtime controller is invoked by plugin developers
  lib/api/core/plugins/pluginContext.js
  lib/api/core/sdk/funnelProtocol.js
  test/api/core/pluginContext/pluginContext.test.js
  test/api/core/sdk/funnelProtocol.test.js
Labels: changelog:enhancements

#1293 Release 1.7.3
  .kuzzlerc.sample
  bin/kuzzle
  cucumber.js
  default.config.js
  docker-compose/scripts/run-dev.sh
  features/kuzzle.feature
  features/step_definitions/collections.js
  features/step_definitions/notifications.js
  features/step_definitions/wait.js
  features/support/api/apiBase.js
  features/support/api/http.js
  lib/api/controllers/authController.js
  lib/api/controllers/collectionController.js
  lib/api/controllers/controller.js
  lib/api/core/entrypoints/embedded/index.js
  lib/api/core/entrypoints/embedded/protocols/mqtt.js
  lib/api/core/entrypoints/embedded/protocols/socketio.js
  lib/api/core/entrypoints/embedded/protocols/websocket.js
  lib/api/core/hotelClerk.js
  lib/api/core/indexCache.js
  lib/api/core/janitor.js
  lib/api/core/models/repositories/userRepository.js
  lib/api/core/plugins/pluginContext.js
  lib/api/core/sdk/funnelProtocol.js
  lib/services/elasticsearch.js
  lib/services/internalEngine/index.js
  lib/services/redis.js
  lib/util/esWrapper.js
  package-lock.json
  package.json
  test/api/controllers/authController.test.js
  test/api/controllers/baseController.test.js
  test/api/core/entrypoints/embedded/index.test.js
  test/api/core/entrypoints/embedded/protocols/http.test.js
  test/api/core/entrypoints/embedded/protocols/websocket.test.js
  test/api/core/hotelClerk/removeCustomerFromAllRooms.test.js
  test/api/core/hotelClerk/removeRoomForCustomer.test.js
  test/api/core/hotelClerk/removeSubscription.test.js
  test/api/core/indexCache.test.js
  test/api/core/janitor.test.js
  test/api/core/pluginContext/pluginContext.test.js
  test/api/core/sdk/funnelProtocol.test.js
  test/mocks/kuzzle.mock.js
  test/mocks/services/elasticsearchClient.mock.js
  test/services/implementations/elasticsearch.test.js
  test/services/internalEngine/index.test.js
  test/util/esWrapper.test.js
Labels: release
