Repository kuzzleio/kuzzle, pull requests merged in 2019-10, with the labels that each got.

#1482 Fix socketio connections leak
  lib/api/core/entrypoints/embedded/index.js
  lib/api/core/entrypoints/embedded/protocols/socketio.js
  package-lock.json
  package.json
  test/api/core/entrypoints/embedded/index.test.js
  test/api/core/entrypoints/embedded/protocols/http.test.js
  test/api/core/entrypoints/embedded/protocols/socketio.test.js
  test/api/core/entrypoints/embedded/protocols/websocket.test.js
Labels: changelog:bug-fixes

#1483 Fix socketio connections leak & deactivate this protocol by default
  .kuzzlerc.sample
  default.config.js
  lib/api/core/entrypoints/index.js
  lib/api/core/entrypoints/protocols/socketio.js
  test/api/core/entrypoints/index.test.js
  test/api/core/entrypoints/protocols/http.test.js
  test/api/core/entrypoints/protocols/socketio.test.js
  test/api/core/entrypoints/protocols/websocket.test.js
Labels: 2.x, changelog:bug-fixes

#1485 Fix Boy Scout Rule in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 2.x, changelog:exclude

#1479 Allow to dynamically add strategy in the plugin init method
  doc/1/plugins/guides/strategies/overview/index.md
  lib/api/core/plugins/pluginsManager.js
  test/api/core/pluginsManager/strategy.test.js
Labels: changelog:bug-fixes

#1490 Add debug entries in the elasticsearch service
  lib/services/elasticsearch.js
Labels: 2.x, changelog:exclude

#1493 Fix socketio version for node6
  package-lock.json
  package.json
Labels: changelog:bug-fixes

#1488 Add kuzzle version to the dumped informations
  lib/api/core/janitor.js
  test/api/core/janitor.test.js
Labels: 2.x, changelog:enhancements

#1500 Remove Dsl constructor from plugin context
  .kuzzlerc.sample
  default.config.js
  doc/2/guides/upgrade-kuzzle/changes/index.md
  doc/2/plugins/plugin-context/constructors/dsl/index.md
  features-sdk/SecurityController.feature
  features-sdk/step_definitions/security-steps.js
  features-sdk/support/hooks.js
  features-sdk/support/world.js
  features/kuzzle.feature
  features/step_definitions/profiles.js
  features/step_definitions/users.js
  features/support/hooks.js
  lib/api/controllers/adminController.js
  lib/api/controllers/securityController.js
  lib/api/core/models/repositories/profileRepository.js
  lib/api/core/models/repositories/repository.js
  lib/api/core/models/repositories/roleRepository.js
  lib/api/core/models/security/profile.js
  lib/api/core/plugins/pluginContext.js
  lib/api/core/storage/bootstrap/internalIndexBootstrap.js
  lib/services/elasticsearch.js
  test/api/controllers/adminController.test.js
  test/api/core/pluginContext/pluginContext.test.js
  test/api/core/storage/bootstrap/internalIndexBootstrap.test.js
  test/services/elasticsearch.test.js
Labels: 2.x, changelog:breaking-changes

#1498 Add highlight to search results
  doc/2/api/controllers/document/search/index.md
  features-sdk/DocumentController.feature
  features-sdk/step_definitions/documents-steps.js
  lib/services/elasticsearch.js
  lib/util/esWrapper.js
  test/services/elasticsearch.test.js
Labels: 2.x, changelog:enhancements
