Repository kuzzleio/kuzzle, pull requests merged in 2020-09, with the labels that each got.

#1760 Sonar issue fix: don't override InternalError
  lib/kerror/codes/index.js
  lib/kerror/index.js
Labels: 2.x, changelog:exclude

#1755 Better stacktrace for sdk
  lib/core/shared/sdk/funnelProtocol.js
  test/core/shared/sdk/funnelProtocol.test.js
Labels: 2.x, changelog:enhancements

#1765 Make getRequestSlot accept a function in place of a string
  lib/api/funnel.js
  test/api/funnel/execute.test.js
Labels: 2.x, changelog:exclude

#1764 Add current commit to server:info
  lib/core/application/backend.ts
  lib/core/plugin/plugin.js
  test/api/controller/server.test.js
  test/core/application/Backend.test.js
  test/mocks/fs.mock.js
Labels: 2.x, changelog:enhancements

#1769 Avoid printing ES errors in development
  lib/service/storage/esWrapper.js
  test/service/storage/esWrapper.test.js
Labels: 2.x, changelog:enhancements

#1780 Prevent a race condition when bootstraping kuzzle indexes at startup
  .ci/test-cluster.yml
  lib/core/storage/bootstrap/safeBootstrap.js
  lib/service/storage/elasticsearch.js
  test/mocks/service/elasticsearchClient.mock.js
Labels: 2.x, changelog:bug-fixes

#1779 Remove minimist dependency
  features/support/hooks.js
  package.json
Labels: 2.x, changelog:exclude

#1782 Avoid useless allocations in plugin context
  lib/core/plugin/pluginContext.js
Labels: 2.x, changelog:enhancements

#1763 Use the latest SDK compatible with Typescript
  .eslintignore
  .gitignore
  lib/core/application/backend.ts
  lib/core/plugin/pluginContext.js
  lib/core/shared/sdk/embeddedSdk.ts
  lib/util/interfaces.ts
  package-lock.json
  package.json
  test/core/application/Backend.test.js
  test/core/plugin/context/context.test.js
  test/core/shared/sdk/embeddedSdk.test.js
Labels: 2.x, changelog:enhancements

#1785 Correctly handles the expiresIn option
  lib/core/security/tokenRepository.js
  test/core/security/tokenRepository.test.js
Labels: 2.x, changelog:bug-fixes

#1759 Expose Controller class for Kaaf
  docker/scripts/functional-tests-controller.ts
  docker/scripts/start-kuzzle-dev.ts
  features-sdk/Application.feature
  index.ts
  lib/core/application/backend.ts
  lib/util/interfaces.ts
Labels: 2.x, changelog:new-features

#1789 Update CONTRIBUTING.md
  CONTRIBUTING.md
  docker-compose.yml
Labels: 2.x, changelog:exclude
