Repository kuzzleio/kuzzle, pull requests merged in 2020-03, with the labels that each got.

#1579 Fix defaulting for document.update and document.scroll options
  lib/services/elasticsearch.js
  test/services/elasticsearch.test.js
Labels: 2.x, changelog:bug-fixes

#1575 Split error codes documentation
  .ci/scripts/check-error-codes-documentation.sh
  .travis.yml
  doc/2/api/controllers/collection/create/index.md
  doc/2/api/controllers/collection/delete-specifications/index.md
  doc/2/api/controllers/collection/delete/index.md
  doc/2/api/controllers/collection/exists/index.md
  doc/2/api/controllers/collection/get-mapping/index.md
  doc/2/api/controllers/collection/get-specifications/index.md
  doc/2/api/controllers/collection/list/index.md
  doc/2/api/controllers/collection/refresh/index.md
  doc/2/api/controllers/collection/scroll-specifications/index.md
  doc/2/api/controllers/collection/search-specifications/index.md
  doc/2/api/controllers/collection/truncate/index.md
  doc/2/api/controllers/collection/update-mapping/index.md
  doc/2/api/controllers/collection/update-specifications/index.md
  doc/2/api/controllers/collection/update/index.md
  doc/2/api/controllers/collection/validate-specifications/index.md
  doc/2/api/controllers/index/create/index.md
  doc/2/api/controllers/index/delete/index.md
  doc/2/api/controllers/index/exists/index.md
  doc/2/api/controllers/index/list/index.md
  doc/2/api/controllers/index/m-delete/index.md
  doc/2/api/controllers/security/refresh/index.md
  doc/2/api/essentials/error-codes/api/index.md
  doc/2/api/essentials/error-codes/core/index.md
  doc/2/api/essentials/error-codes/index.md
  doc/2/api/essentials/error-codes/network/index.md
  doc/2/api/essentials/error-codes/plugin/index.md
  doc/2/api/essentials/error-codes/protocol/index.md
  doc/2/api/essentials/error-codes/security/index.md
  doc/2/api/essentials/error-codes/services/index.md
  doc/2/api/essentials/error-codes/validation/index.md
  doc/2/api/essentials/error-handling/index.md
  doc/2/api/essentials/errors/codes/index.md
  doc/2/api/essentials/errors/index.md
  doc/2/api/essentials/kuzzle-response/index.md
  doc/2/plugins/guides/events/core-overload/index.md
  doc/2/plugins/plugin-context/errors-manager/index.md
  doc/build-error-codes.js
  package.json
Labels: 2.x, changelog:exclude

#1582 [ci] do not deploy documentation if the build fails
  .travis.yml
Labels: 2.x, changelog:exclude

#1580 Release 2.1.1
  .mocharc.json
  doc/2/api/controllers/security/create-or-replace-role/index.md
  doc/2/api/controllers/security/create-role/index.md
  doc/2/api/controllers/security/update-role/index.md
  doc/2/api/essentials/error-codes/security/index.md
  features-sdk/PluginEvents.feature
  features-sdk/SecurityController.feature
  features-sdk/step_definitions/controllers-steps.js
  features-sdk/step_definitions/security-steps.js
  features/kuzzle.feature
  lib/api/controllers/security.js
  lib/api/controllers/server.js
  lib/api/funnel.js
  lib/config/error-codes/security.json
  lib/core/entrypoints/protocols/mqtt.js
  lib/core/models/repositories/roleRepository.js
  lib/core/models/repositories/userRepository.js
  lib/core/plugins/context.js
  lib/core/plugins/manager.js
  lib/core/statistics.js
  lib/core/swagger.js
  lib/kuzzle.js
  lib/services/elasticsearch.js
  lib/util/log.js
  package-lock.json
  package.json
  test/api/funnel/execute.test.js
  test/api/funnel/processRequest.test.js
  test/core/entrypoints/protocols/mqtt.test.js
  test/core/models/repositories/roleRepository.test.js
  test/core/plugins/context/context.test.js
  test/core/statistics.test.js
  test/kuzzle.test.js
  test/mocha.opts
  test/mocks/kuzzle.mock.js
  test/services/elasticsearch.test.js
Labels: release

#1576 Add meaningful error message on strict mapping rejection
  doc/2/api/essentials/error-codes/services/index.md
  features-sdk/AdminController.feature
  features-sdk/AuthController.feature
  features-sdk/BulkController.feature
  features-sdk/CollectionController.feature
  features-sdk/DocumentController.feature
  features-sdk/IndexController.feature
  features-sdk/PluginContext.feature
  features-sdk/PluginEvents.feature
  features-sdk/SecurityController.feature
  features-sdk/ServerController.feature
  lib/config/error-codes/services.json
  lib/core/entrypoints/index.js
  lib/core/janitor.js
  lib/core/plugins/manager.js
  lib/util/esWrapper.js
  test/core/janitor.test.js
Labels: 2.x, changelog:enhancements

#1563 Add more security actions logs
  lib/api/controllers/admin.js
  lib/api/controllers/base.js
  lib/api/controllers/security.js
  lib/api/funnel.js
  lib/core/janitor.js
  test/api/controllers/security/index.js
  test/api/controllers/security/profiles.test.js
  test/api/controllers/security/roles.test.js
  test/api/controllers/security/users.test.js
Labels: 2.x, changelog:enhancements

#1581 Add document "version" to mUpdate response
  doc/2/api/controllers/document/m-update/index.md
  features-sdk/DocumentController.feature
  lib/services/elasticsearch.js
Labels: 2.x, changelog:enhancements

#1578 Allow to limit scroll usage
  .kuzzlerc.sample
  default.config.js
  doc/2/api/controllers/collection/scroll-specifications/index.md
  doc/2/api/controllers/document/scroll/index.md
  doc/2/api/controllers/document/search/index.md
  doc/2/api/essentials/error-codes/services/index.md
  doc/2/guides/essentials/store-access-data/index.md
  doc/2/plugins/plugin-context/constructors/repository/index.md
  lib/api/funnel.js
  lib/config/error-codes/services.json
  lib/services/elasticsearch.js
  test/mocks/kuzzle.mock.js
  test/services/elasticsearch.test.js
Labels: 2.x, changelog:enhancements

#1570 Fix realtime:publish from embedded SDK
  .ci/scripts/check-error-codes-documentation.sh
  .travis.yml
  doc/2/api/essentials/error-codes/plugin/index.md
  lib/api/controllers/realtime.js
  lib/config/error-codes/plugin.json
  lib/core/plugins/context.js
  lib/core/sdk/funnelProtocol.js
  test/api/controllers/realtime.test.js
  test/core/plugins/context/context.test.js
  test/core/sdk/funnelProtocol.test.js
Labels: 2.x, changelog:bug-fixes

#1586 Fix settings loading fail on opened indexes
  doc/2/api/controllers/collection/update-mapping/index.md
  doc/2/api/controllers/collection/update/index.md
  lib/services/elasticsearch.js
  package-lock.json
  package.json
Labels: 2.x, changelog:bug-fixes

#1585 Use index cache for index/collection listing
  doc/2/api/controllers/index/list/index.md
  features-sdk/CollectionController.feature
  features-sdk/IndexController.feature
  features-sdk/step_definitions/controllers-steps.js
  features/kuzzle.feature
  lib/api/controllers/index.js
  lib/core/storage/clientAdapter.js
  lib/core/storage/storageEngine.js
  test/core/storage/clientAdapter.test.js
  test/core/storage/storageEngine.test.js
  test/mocks/kuzzle.mock.js
Labels: 2.x, changelog:enhancements

#1588 Add kourou to plugin-dev image
  Dockerfile
Labels: changelog:exclude

#1590 Release 2.1.2
  .ci/scripts/check-error-codes-documentation.sh
  .kuzzlerc.sample
  .travis.yml
  default.config.js
  doc/2/api/controllers/collection/scroll-specifications/index.md
  doc/2/api/controllers/document/m-update/index.md
  doc/2/api/controllers/document/scroll/index.md
  doc/2/api/controllers/document/search/index.md
  doc/2/api/controllers/index/list/index.md
  doc/2/api/essentials/error-codes/plugin/index.md
  doc/2/api/essentials/error-codes/services/index.md
  doc/2/guides/essentials/store-access-data/index.md
  doc/2/plugins/plugin-context/constructors/repository/index.md
  features-sdk/AdminController.feature
  features-sdk/AuthController.feature
  features-sdk/BulkController.feature
  features-sdk/CollectionController.feature
  features-sdk/DocumentController.feature
  features-sdk/IndexController.feature
  features-sdk/PluginContext.feature
  features-sdk/PluginEvents.feature
  features-sdk/SecurityController.feature
  features-sdk/ServerController.feature
  features-sdk/step_definitions/controllers-steps.js
  features/kuzzle.feature
  lib/api/controllers/admin.js
  lib/api/controllers/base.js
  lib/api/controllers/index.js
  lib/api/controllers/realtime.js
  lib/api/controllers/security.js
  lib/api/funnel.js
  lib/config/error-codes/plugin.json
  lib/config/error-codes/services.json
  lib/core/entrypoints/index.js
  lib/core/janitor.js
  lib/core/plugins/context.js
  lib/core/plugins/manager.js
  lib/core/sdk/funnelProtocol.js
  lib/core/storage/clientAdapter.js
  lib/core/storage/storageEngine.js
  lib/services/elasticsearch.js
  lib/util/esWrapper.js
  package-lock.json
  package.json
  test/api/controllers/realtime.test.js
  test/api/controllers/security/index.js
  test/api/controllers/security/profiles.test.js
  test/api/controllers/security/roles.test.js
  test/api/controllers/security/users.test.js
  test/core/janitor.test.js
  test/core/plugins/context/context.test.js
  test/core/sdk/funnelProtocol.test.js
  test/core/storage/clientAdapter.test.js
  test/core/storage/storageEngine.test.js
  test/mocks/kuzzle.mock.js
  test/services/elasticsearch.test.js
Labels: release
