Repository kuzzleio/kuzzle, pull requests merged in 2020-07, with the labels that each got.

#1698 Fix generic events on search queries
  doc/2/api/essentials/error-codes/core/index.md
  doc/2/plugins/guides/events/generic-document-events/index.md
  lib/api/documentExtractor.js
  lib/api/funnel.js
  lib/config/documentEventAliases.js
  lib/kerror/codes/core.json
  test/api/documentExtractor.test.js
Labels: 2.x, changelog:bug-fixes

#1699 Fix missing curl in Docker images
  bin/wait-elasticsearch
  bin/wait-kuzzle
  docker/images/kuzzle.alpine/Dockerfile
  docker/images/kuzzle.scratch/Dockerfile
  docker/images/kuzzle/Dockerfile
  docker/images/plugin-dev/Dockerfile
Labels: 2.x, changelog:exclude

#1700 Fix: handling of Elasticsearch aliases
  lib/core/storage/storageEngine.js
  lib/service/storage/elasticsearch.js
  package-lock.json
  package.json
  test/core/storage/storageEngine.test.js
  test/service/storage/elasticsearch.test.js
Labels: changelog:bug-fixes

#1604 Add request ID in log
  .ci/scripts/run-test-arm.sh
  .ci/scripts/run-test.sh
  .travis.yml
  lib/api/funnel.js
  lib/kuzzle/kuzzle.js
  lib/kuzzle/log.js
  lib/util/asyncStore.js
  test/api/funnel/execute.test.js
  test/mocks/kuzzle.mock.js
  test/util/asyncStore.test.js
Labels: 2.x, changelog:enhancements

#1702 Updates search index only when dynamic changes from false to true
  lib/service/storage/elasticsearch.js
  test/service/storage/elasticsearch.test.js
Labels: 2.x, changelog:enhancements

#1695 Fix dump generation
  lib/kuzzle/kuzzle.js
  test/kuzzle/kuzzle.test.js
  test/mocks/kuzzle.mock.js
Labels: 2.x, changelog:bug-fixes

#1701 Fix: description should not be required for plugin custom errors
  doc/2/plugins/plugin-context/kerror/index.md
  lib/kerror/codes/index.js
  package-lock.json
  package.json
  test/kerror/codes.test.js
Labels: 2.x, changelog:bug-fixes

#1711 Prevent timeouts when refreshing large indexes
  lib/service/storage/elasticsearch.js
  test/service/storage/elasticsearch.test.js
Labels: 2.x, changelog:bug-fixes

#1712 Preserve auth plugin error thrown during user creation
  lib/api/controller/security.js
  test/api/controller/security/users.test.js
Labels: 2.x, changelog:bug-fixes

#1717 Add cache invalidation events
  lib/core/security/profileRepository.js
  lib/core/security/roleRepository.js
  test/core/security/profileRepository.test.js
  test/core/security/roleRepository.test.js
Labels: 2.x, changelog:bug-fixes

#1715 Fix HTTP multipart crash
  features/fixtures/bad-multipart.req
  features/kuzzle.feature
  features/step_definitions/http.js
  lib/core/network/service/httpFormDataStream.js
Labels: 2.x, changelog:bug-fixes

#1714 Remove limits for bulk controller
  doc/2/api/controllers/bulk/import/index.md
  doc/2/api/controllers/bulk/m-write/index.md
  lib/api/controller/bulk.js
  lib/service/storage/elasticsearch.js
  test/api/controller/bulk.test.js
  test/service/storage/elasticsearch.test.js
Labels: 2.x, changelog:enhancements

#1710 Log ES request errors
  lib/service/storage/elasticsearch.js
  lib/service/storage/esWrapper.js
  test/service/storage/esWrapper.test.js
Labels: 2.x, changelog:enhancements

#1713 Fix the "total" property returned by security:searchUsers
  features-sdk/SecurityController.feature
  features-sdk/step_definitions/controllers-steps.js
  features-sdk/step_definitions/security-steps.js
  lib/core/shared/repository.js
Labels: 2.x, changelog:bug-fixes

#1724 Return the right total number of searched documents with non-scroll searches
  lib/service/storage/elasticsearch.js
  test/service/storage/elasticsearch.test.js
Labels: 2.x, changelog:bug-fixes

#1722 Correctly load ES aliases when they point to non-existing Kuzzle indexes
  lib/core/storage/storageEngine.js
  test/core/storage/storageEngine.test.js
Labels: 2.x, changelog:bug-fixes

#1716 Fix HTTP multipart crash
  features/fixtures/bad-multipart.req
  features/kuzzle.feature
  features/step_definitions/http.js
  lib/api/core/entrypoints/embedded/service/httpFormDataStream.js
Labels: 1.x, changelog:bug-fixes

#1725 Release 1.11.2
  features/fixtures/bad-multipart.req
  features/kuzzle.feature
  features/step_definitions/http.js
  lib/api/core/entrypoints/embedded/service/httpFormDataStream.js
  package-lock.json
  package.json
Labels: release

#1726 Prefix auth user related routes with _me
  doc/2/api/controllers/auth/create-my-credentials/index.md
  doc/2/api/controllers/auth/credentials-exists/index.md
  doc/2/api/controllers/auth/delete-my-credentials/index.md
  doc/2/api/controllers/auth/get-current-user/index.md
  doc/2/api/controllers/auth/get-my-credentials/index.md
  doc/2/api/controllers/auth/get-my-rights/index.md
  doc/2/api/controllers/auth/update-my-credentials/index.md
  doc/2/api/controllers/auth/update-self/index.md
  doc/2/api/controllers/auth/validate-my-credentials/index.md
  lib/config/httpRoutes.js
Labels: 2.x, changelog:enhancements

#1720 Allow to delete a still-used profile by removing it from assigned users
  doc/2/api/controllers/security/delete-profile/index.md
  features-sdk/SecurityController.feature
  lib/api/controller/security.js
  lib/core/security/profileRepository.js
  test/core/security/profileRepository.test.js
Labels: 2.x, changelog:enhancements

#1730 Fix failing tests
  doc/2/api/essentials/error-codes/plugin/index.md
  doc/2/api/essentials/error-codes/services/index.md
  features-sdk/Application.feature
  features-sdk/SecurityController.feature
  features-sdk/application/functional-tests-app.ts
  lib/core/plugin/plugin.js
  package-lock.json
  package.json
  test/core/plugin/context/context.test.js
  test/core/plugin/plugin.test.js
  test/core/plugin/pluginsManager.test.js
Labels: 2.x, changelog:exclude

#1739 Fix: load manifest configuration correctly
  lib/core/network/entryPoint.js
  lib/core/network/protocolManifest.js
  lib/core/plugin/plugin.js
  lib/core/plugin/pluginManifest.js
  lib/core/shared/abstractManifest.js
  test/core/plugin/pluginManifest.test.js
  test/core/shared/abstractManifest.test.js
Labels: 2.x, changelog:exclude

#1738 Normalize security event names to our latest convention
  lib/api/controller/auth.js
  lib/api/controller/security.js
  lib/api/controller/server.js
  lib/core/auth/tokenManager.js
  lib/core/network/entryPoint.js
  lib/core/security/userRepository.js
  test/api/controller/auth.test.js
  test/api/controller/security/users.test.js
  test/api/controller/server.test.js
  test/api/funnel/execute.test.js
  test/api/funnel/init.test.js
  test/core/auth/tokenManager.test.js
  test/core/network/entryPoint.test.js
  test/core/security/userRepository.test.js
Labels: 2.x, changelog:exclude
