Repository kuzzleio/kuzzle, pull requests merged in 2020-08, with the labels that each got.

#1742 Documentation: fix rendering of a few href links
  doc/2/protocols/api/context/request/index.md
Labels: 2.x, changelog:exclude

#1744 Logs why a ws connection is closed
  lib/core/network/protocols/websocket.js
Labels: 2.x, changelog:exclude

#1748 Fix docs admin console missing images
  doc/2/guides/essentials/admin-console/index.md
Labels: changelog:exclude

#1751 Add a "remaining" property to scroll search results
  doc/2/api/controllers/document/scroll/index.md
  doc/2/api/controllers/document/search/index.md
  features-sdk/DocumentController.feature
  features-sdk/run.sh
  features-sdk/step_definitions/documents-steps.js
  lib/api/controller/document.js
  lib/service/storage/elasticsearch.js
  test/api/controller/document.test.js
  test/service/storage/elasticsearch.test.js
Labels: 2.x, changelog:enhancements

#1745 Ensure correct values for mappings dynamic properties
  doc/2/api/controllers/collection/create/index.md
  doc/2/api/controllers/collection/update/index.md
  doc/2/api/essentials/error-codes/services/index.md
  doc/2/guides/essentials/database-mappings/index.md
  lib/core/application/backend.ts
  lib/kerror/codes/1-services.json
  lib/service/storage/elasticsearch.js
  test/core/framework/Backend.test.js
  test/service/storage/elasticsearch.test.js
Labels: 2.x, changelog:enhancements

#1753 Allow plugins to execute API requests during their init phase
  lib/core/network/entryPoint.js
  lib/core/network/protocols/internal.js
  lib/core/shared/sdk/funnelProtocol.js
  lib/kuzzle/kuzzle.js
  package-lock.json
  package.json
  plugins/available/functional-test-plugin/functionalTestPlugin.js
  test/core/network/protocols/internal.test.js
  test/core/shared/sdk/funnelProtocol.test.js
  test/kuzzle/kuzzle.test.js
Labels: 2.x, changelog:bug-fixes

#1740 Replace url property by path in HTTP routes definition
  doc/2/plugins/guides/controllers/index.md
  features-sdk/Application.feature
  features-sdk/application/functional-tests-app.ts
  features-sdk/fixtures/mappings.js
  features/step_definitions/statistics.js
  lib/api/controller/server.js
  lib/api/swagger.js
  lib/config/httpRoutes.js
  lib/core/application/backend.ts
  lib/core/network/httpRouter/index.js
  lib/core/network/router.js
  lib/core/plugin/plugin.js
  lib/core/plugin/pluginsManager.js
  lib/core/realtime/hotelClerk.js
  lib/core/security/profileRepository.js
  lib/kuzzle/kuzzle.js
  lib/service/storage/elasticsearch.js
  lib/util/interfaces.ts
  plugins/available/functional-test-plugin/functionalTestPlugin.js
  test/api/controller/server.test.js
  test/core/framework/Backend.test.js
  test/core/network/router/httpRequest.test.js
  test/core/plugin/pluginsManager.test.js
  test/core/realtime/hotelClerk/countSubscription.test.js
  test/kuzzle/kuzzle.test.js
  test/mocks/kuzzle.mock.js
  test/model/security/profile.test.js
  test/model/storage/apiKey.test.js
  tsconfig.json
Labels: 2.x, changelog:enhancements

#1758 Fix manifest loading for cluster
  bin/start-kuzzle-server
  lib/core/application/backend.ts
  lib/core/network/entryPoint.js
  lib/core/plugin/plugin.js
  lib/core/plugin/pluginsManager.js
  lib/kuzzle/kuzzle.js
  package-lock.json
  package.json
  test/core/framework/Backend.test.js
  test/core/network/entryPoint.test.js
  test/kuzzle/kuzzle.test.js
Labels: 2.x, changelog:bug-fixes

#1754 Make the dev image compatible with kaaf functional tests
  .kuzzlerc.sample
  bin/start-kuzzle-server
  bin/wait-elasticsearch
  bin/wait-kuzzle
  docker/scripts/run-dev.sh
  lib/config/default.config.js
  lib/service/storage/elasticsearch.js
Labels: 2.x, changelog:exclude

#1761 Fix typo in scroll document page
  doc/2/api/controllers/document/scroll/index.md
Labels: 2.x, changelog:exclude

#1757 Parallelize functional tests by protocol
  .travis.yml
  features-sdk/run.sh
  features/run.sh
  package.json
Labels: 2.x, changelog:exclude
