Repository kuzzleio/kuzzle, pull requests merged in 2020-11, with the labels that each got.

#1849 Deprecate misc.url for misc.path
  .travis.yml
  lib/core/network/httpRouter/routeHandler.js
  lib/core/network/protocols/http.js
  test/core/network/protocols/http.test.js
Labels: 2.x, changelog:enhancements

#1852 Dusting the manual install section
  doc/2/guides/essentials/installing-kuzzle/index.md
Labels: 2.x, changelog:exclude

#1853 Update obsolete ES configuration documentation
  doc/2/guides/essentials/configuration/index.md
Labels: 2.x

#1792 Add (un)subscription to PluginContext
  doc/2/plugins/plugin-context/accessors/subscription/index.md
  features-sdk/PluginContext.feature
  features-sdk/step_definitions/realtime-steps.js
  features-sdk/support/hooks.js
  lib/core/plugin/pluginContext.js
  package.json
  plugins/available/functional-test-plugin/functionalTestPlugin.js
  test/core/plugin/context/context.test.js
Labels: changelog:new-features

#1838 Add documentation - Develop on Kuzzle - API Controllers
  doc/2/guides/develop-on-kuzzle/1-backend-interactions/index.md
  doc/2/guides/develop-on-kuzzle/3-api-controllers/index.md
Labels: 2.x, changelog:exclude

#1845 Rewrite documentation - Main Concepts - Permissions
  doc/2/api/controllers/admin/load-securities/index.md
  doc/2/api/controllers/security/get-credential-fields/index.md
  doc/2/guides/main-concepts/4-permissions/index.md
  doc/2/guides/main-concepts/6-realtime-engine/index.md
Labels: 2.x, changelog:exclude

#1847 Rewrite documentation - Main Concepts - Realtime Engine
  doc/2/guides/getting-started/5-subscribe-realtime-notifications/index.md
  doc/2/guides/introduction/1-what-is-kuzzle/index.md
  doc/2/guides/main-concepts/6-realtime-engine/index.md
Labels: 2.x, changelog:exclude

#1856 Fix documentation - Getting Started
  doc/2/guides/advanced/6-export-import-data/index.md
  doc/2/guides/develop-on-kuzzle/3-api-controllers/index.md
  doc/2/guides/getting-started/1-run-kuzzle/index.md
  doc/2/guides/getting-started/2-store-and-access-data/index.md
  doc/2/guides/getting-started/3-set-up-permissions/index.md
  doc/2/guides/getting-started/4-authenticate-users/index.md
  doc/2/guides/getting-started/5-subscribe-realtime-notifications/index.md
  doc/2/guides/getting-started/7-create-new-controllers/index.md
  doc/2/guides/getting-started/8-customize-api-behavior/index.md
  doc/2/guides/introduction/1-what-is-kuzzle/index.md
  doc/2/guides/main-concepts/4-permissions/index.md
  doc/2/guides/main-concepts/6-realtime-engine/index.md
Labels: 2.x, changelog:exclude

#1857 Fix the HTTP index:mDelete endpoint
  features/support/api/http.js
  lib/config/httpRoutes.js
Labels: 2.x, changelog:bug-fixes

#1858 Fix index:mDelete to make it return the list of deleted indexes
  lib/core/storage/clientAdapter.js
  test/core/storage/clientAdapter.test.js
Labels: 2.x, changelog:bug-fixes

#1862 Release 2.7.0
  .ci/scripts/run-test.sh
  .travis.yml
  doc/2/api/index.md
  doc/2/guides/index.md
  doc/2/index.md
  doc/2/plugins/index.md
  doc/2/plugins/plugin-context/accessors/subscription/index.md
  doc/2/protocols/index.md
  features-sdk/PluginContext.feature
  features-sdk/step_definitions/realtime-steps.js
  features-sdk/support/hooks.js
  features/support/api/http.js
  lib/config/httpRoutes.js
  lib/core/network/httpRouter/routeHandler.js
  lib/core/network/protocols/http.js
  lib/core/plugin/pluginContext.js
  lib/core/storage/clientAdapter.js
  package-lock.json
  package.json
  plugins/available/functional-test-plugin/functionalTestPlugin.js
  test/core/network/protocols/http.test.js
  test/core/plugin/context/context.test.js
  test/core/storage/clientAdapter.test.js
Labels: release

#1860 Add documentation - Main Concepts - Data Storage
  doc/2/guides/getting-started/2-store-and-access-data/index.md
  doc/2/guides/main-concepts/2-data-storage/index.md
  lib/service/storage/elasticsearch.js
Labels: 2.x, changelog:exclude

#1864 [Doc > Code-examples > IOT > JS] publish.js snippet fix
  doc/2/guides/code-examples/iot/javascript/snippets/publish.js
Labels: 2.x, changelog:exclude

#1866 Add missing version tag
  doc/2/plugins/plugin-context/accessors/subscription/index.md
Labels: 2.x, changelog:exclude

#1870 Fix document:mCreate documentation
  doc/2/api/controllers/document/m-create/index.md
Labels: 2.x, changelog:exclude

#1863 Add documentation - Main Concepts - Querying
  doc/2/guides/getting-started/2-store-and-access-data/index.md
  doc/2/guides/getting-started/4-authenticate-users/index.md
  doc/2/guides/getting-started/5-subscribe-realtime-notifications/index.md
  doc/2/guides/main-concepts/3-querying/index.md
Labels: 2.x, changelog:exclude

#1865 Add documentation - Main Concepts - Authentication
  .kuzzlerc.sample
  doc/2/guides/getting-started/4-authenticate-users/index.md
  doc/2/guides/main-concepts/5-authentication/index.md
  lib/config/default.config.js
Labels: 2.x, changelog:exclude

#1859 Add documentation - Develop On Kuzzle - Embedded SDK
  doc/2/guides/advanced/10-internal-logger/index.md
  doc/2/guides/advanced/8-configuration/index.md
  doc/2/guides/develop-on-kuzzle/1-core-module/index.md
  doc/2/guides/develop-on-kuzzle/1-embedded-sdk/index.md
  doc/2/guides/develop-on-kuzzle/3-event-system/index.md
  doc/2/guides/develop-on-kuzzle/5-customize-api-errors/index.md
  lib/core/application/backend.ts
  lib/kerror/index.js
Labels: 2.x, changelog:exclude

#1855 Add documentation - Main Concepts - API
  .kuzzlerc.sample
  doc/2/api/api-protocols/1-http/index.md
  doc/2/api/api-protocols/2-websocket/index.md
  doc/2/api/api-protocols/3-mqtt/index.md
  doc/2/api/api-protocols/index.md
  doc/2/api/essentials/error-handling/index.md
  doc/2/api/essentials/kuzzle-response/index.md
  doc/2/api/essentials/notifications/index.md
  doc/2/api/essentials/query-syntax/index.md
  doc/2/api/essentials/volatile-data/index.md
  doc/2/guides/develop-on-kuzzle/2-api-controllers/index.md
  doc/2/guides/main-concepts/1-api/index.md
Labels: 2.x, changelog:exclude

#1881 Remove stacktrace enhancement
  lib/core/shared/sdk/funnelProtocol.js
  package-lock.json
  package.json
  test/core/shared/sdk/funnelProtocol.test.js
Labels: 2.x, changelog:bug-fixes

#1800 Allow plugins to be written in Typescript
  .eslintignore
  .gitignore
  doc/2/api/controllers/collection/truncate/index.md
  docker/scripts/start-kuzzle-dev.ts
  index.ts
  lib/api/controller/document.js
  lib/api/request/request.ts
  lib/api/request/requestContext.ts
  lib/api/request/requestInput.ts
  lib/api/request/requestResponse.ts
  lib/core/application/backend.ts
  lib/core/plugin/plugin.js
  lib/core/plugin/pluginContext.ts
  lib/core/plugin/pluginsManager.js
  lib/core/plugin/privilegedContext.js
  lib/core/shared/sdk/embeddedSdk.ts
  lib/kerror/errors/kuzzleError.ts
  lib/kerror/index.js
  lib/util/interfaces.ts
  package-lock.json
  package.json
  plugins/available/functional-test-plugin/functionalTestPlugin.js
  test/core/application/Backend.test.js
  test/core/plugin/context/context.test.js
  test/core/plugin/pluginsManager.test.js
  tsconfig.json
Labels: 2.x, changelog:enhancements

#1874 Add "auth|security:checkRights" API actions
  doc/2/api/controllers/auth/check-rights/index.md
  doc/2/api/controllers/security/check-rights/index.md
  features-sdk/AuthController.feature
  features-sdk/SecurityController.feature
  features-sdk/fixtures/securities.js
  features-sdk/step_definitions/auth-steps.js
  lib/api/controller/auth.js
  lib/api/controller/security.js
  lib/config/httpRoutes.js
  lib/core/shared/sdk/funnelProtocol.js
  test/api/controller/auth.test.js
  test/api/controller/security/users.test.js
Labels: 2.x, changelog:new-features

#1878 Add documentation - Advanced - API Keys
  doc/2/guides/advanced/2-api-keys/index.md
Labels: 2.x, changelog:exclude

#1873 Allows to pass Koncorde filters as a search query
  .eslintignore
  .gitignore
  doc/2/api/controllers/auth/search-api-keys/index.md
  doc/2/api/controllers/document/delete-by-query/index.md
  doc/2/api/controllers/document/search/index.md
  doc/2/api/controllers/document/update-by-query/index.md
  doc/2/api/controllers/security/search-api-keys/index.md
  doc/2/api/controllers/security/search-users/index.md
  doc/2/api/essentials/error-codes/api/index.md
  docker/scripts/functional-tests-controller.ts
  features-sdk/AuthController.feature
  features-sdk/DocumentController.feature
  features-sdk/SecurityController.feature
  features-sdk/fixtures/mappings.js
  lib/api/controller/auth.js
  lib/api/controller/base.js
  lib/api/controller/document.js
  lib/api/controller/security.js
  lib/core/storage/clientAdapter.js
  lib/kerror/codes/2-api.json
  lib/service/storage/elasticsearch.js
  lib/service/storage/queryTranslator.js
  lib/util/interfaces.ts
  package.json
  test/api/controller/base.test.js
  test/api/controller/document.test.js
  test/api/controller/security/users.test.js
  test/mocks/kuzzle.mock.js
  test/service/storage/queryTranslator.test.js
Labels: 2.x, changelog:new-features

#1889 New Documentation - Introduction - General Purpose Backend
  doc/2/guides/introduction/1-what-is-kuzzle/index.md
  doc/2/guides/introduction/2-general-purpose-backend/index.md
  doc/2/guides/introduction/2-general-purpose-backend/profiles-roles.png
  doc/2/guides/introduction/2-overview/index.md
Labels: 2.x, changelog:exclude
