Repository kuzzleio/kuzzle, pull requests merged in 2020-12, with the labels that each got.

#1886 Add SDKs snippets test on Kuzzle PRs
  .travis.yml
Labels: 2.x, changelog:exclude

#1890 New Documentation - Import Plugin Doc
  .ci/scripts/check-error-codes-documentation.sh
  doc/2/api/errors/error-codes/api/index.md
  doc/2/api/errors/error-codes/core/index.md
  doc/2/api/errors/error-codes/network/index.md
  doc/2/api/errors/error-codes/plugin/index.md
  doc/2/api/errors/error-codes/protocol/index.md
  doc/2/api/errors/error-codes/security/index.md
  doc/2/api/errors/error-codes/services/index.md
  doc/2/api/errors/error-codes/validation/index.md
  doc/2/framework/abstract-classes/controller/constructor/index.md
  doc/2/framework/abstract-classes/controller/properties/index.md
  doc/2/framework/abstract-classes/plugin/constructor/index.md
  doc/2/framework/abstract-classes/plugin/init/index.md
  doc/2/framework/abstract-classes/plugin/properties/index.md
  doc/2/framework/types/plugin-manifest/index.md
  doc/2/framework/types/strategy-definition/index.md
  doc/2/guides/write-plugins/1-start-writing-plugins/index.md
  doc/2/guides/write-plugins/1-why-writing-plugin/index.md
  doc/2/guides/write-plugins/2-plugins-features/index.md
  doc/2/guides/write-plugins/2-write-first-plugin/index.md
  doc/2/guides/write-plugins/3-integrate-authentication-strategy/index.md
  doc/2/guides/write-plugins/4-network-protocol/index.md
  doc/2/guides/write-plugins/4-old-guides/controllers/index.md
  doc/2/guides/write-plugins/4-old-guides/hooks/index.md
  doc/2/guides/write-plugins/4-old-guides/index.md
  doc/2/guides/write-plugins/4-old-guides/pipes/index.md
  doc/2/guides/write-protocols/1-start-writing-protocols/index.md
  doc/2/guides/write-protocols/2-context/clientconnection/index.md
  doc/2/guides/write-protocols/2-context/debug/index.md
  doc/2/guides/write-protocols/2-context/errors/index.md
  doc/2/guides/write-protocols/2-context/index.md
  doc/2/guides/write-protocols/2-context/intro/index.md
  doc/2/guides/write-protocols/2-context/log/index.md
  doc/2/guides/write-protocols/2-context/request/index.md
  doc/2/guides/write-protocols/2-context/requestcontext/index.md
  doc/2/guides/write-protocols/2-context/requestinput/index.md
  doc/2/guides/write-protocols/3-entrypoint/execute/index.md
  doc/2/guides/write-protocols/3-entrypoint/index.md
  doc/2/guides/write-protocols/3-entrypoint/intro/index.md
  doc/2/guides/write-protocols/3-entrypoint/newconnection/index.md
  doc/2/guides/write-protocols/3-entrypoint/removeconnection/index.md
  doc/2/guides/write-protocols/4-methods/broadcast/index.md
  doc/2/guides/write-protocols/4-methods/disconnect/index.md
  doc/2/guides/write-protocols/4-methods/index.md
  doc/2/guides/write-protocols/4-methods/init/index.md
  doc/2/guides/write-protocols/4-methods/joinchannel/index.md
  doc/2/guides/write-protocols/4-methods/leavechannel/index.md
  doc/2/guides/write-protocols/4-methods/notify/index.md
  doc/2/guides/write-protocols/index.md
  doc/build-error-codes.js
  lib/core/plugin/plugin.js
  lib/kerror/codes/4-plugin.json
  lib/types/Plugin.ts
  lib/types/PluginManifest.ts
  lib/types/StrategyDefinition.ts
Labels: 2.x, changelog:exclude

#1892 Allow to know which user is linked to an authentication token
  doc/2/api/controllers/auth/check-token/index.md
  features-sdk/AuthController.feature
  features-sdk/support/world.js
  lib/api/controller/auth.js
  test/api/controller/auth.test.js
Labels: 2.x, changelog:enhancements

#1896 New Documentation - Update README
  README.md
Labels: 2.x, changelog:exclude

#1897 Fix error thrown when trying to submit an empty document:mUpdate request
  lib/api/controller/document.js
  lib/core/cache/cacheEngine.js
  package-lock.json
  package.json
  test/api/controller/document.test.js
  test/core/cache/cacheEngine.test.js
Labels: 2.x, changelog:bug-fixes

#1900 Fix security:updateRole to replace entire role content
  features-sdk/SecurityController.feature
  features-sdk/step_definitions/security-steps.js
  lib/core/security/roleRepository.js
  test/core/security/roleRepository.test.js
  tsconfig.json
Labels: 2.x, changelog:bug-fixes

#1909 Remove since/experimental badges from guides
  doc/2/guides/advanced/configuration/index.md
  doc/2/guides/develop-on-kuzzle/api-controllers/index.md
  doc/2/guides/develop-on-kuzzle/customize-api-errors/index.md
  doc/2/guides/develop-on-kuzzle/embedded-sdk/index.md
  doc/2/guides/develop-on-kuzzle/event-system/index.md
  doc/2/guides/develop-on-kuzzle/external-plugins/index.md
  doc/2/guides/getting-started/create-new-controllers/index.md
  doc/2/guides/getting-started/customize-api-behavior/index.md
  doc/2/guides/getting-started/write-application/index.md
Labels: 2.x, changelog:exclude

#1908 Expose mutex class to plugins
  doc/1/api/essentials/errors/codes/index.md
  doc/1/plugins/plugin-context/constructors/mutex/index.md
  lib/api/core/plugins/pluginContext.js
  lib/api/kuzzle.js
  lib/config/error-codes/core.json
  lib/util/mutex.js
  test/api/controllers/funnelController/execute.test.js
  test/mocks/kuzzle.mock.js
  test/services/internalEngine/bootstrap.test.js
  test/services/internalEngine/pluginBootstrap.test.js
  test/util/mutex.test.js
Labels: 1.x, changelog:new-features

#1917 Release 1.12.0
  doc/1/api/essentials/errors/codes/index.md
  doc/1/plugins/plugin-context/constructors/mutex/index.md
  lib/api/core/plugins/pluginContext.js
  lib/api/kuzzle.js
  lib/config/error-codes/core.json
  lib/util/mutex.js
  package-lock.json
  package.json
  test/api/controllers/funnelController/execute.test.js
  test/mocks/kuzzle.mock.js
  test/services/internalEngine/bootstrap.test.js
  test/services/internalEngine/pluginBootstrap.test.js
  test/util/mutex.test.js
Labels: release

#1914 Add backend constructor documentation
  doc/2/framework/classes/backend/constructor/index.md
  doc/2/framework/classes/backend/properties/index.md
Labels: 2.x, changelog:exclude

#1920 Delete duplicated documentation section
  doc/2/api/koncorde-filters-syntax/clauses/index.md
Labels: 2.x, changelog:exclude

#1918 Add visual to the documentation page "What is Kuzzle"
  doc/2/guides/getting-started/store-and-access-data/index.md
  doc/2/guides/introduction/what-is-kuzzle/ecosystem-admin-console.png
  doc/2/guides/introduction/what-is-kuzzle/ecosystem-business-plugins.png
  doc/2/guides/introduction/what-is-kuzzle/ecosystem-sdk-platforms.png
  doc/2/guides/introduction/what-is-kuzzle/index.md
  doc/2/guides/main-concepts/api/index.md
  doc/2/guides/main-concepts/data-storage/index.md
Labels: 2.x, changelog:exclude
