Repository kuzzleio/kuzzle, pull requests merged in 2020-10, with the labels that each got.

#1798 Set default log level to info
  .kuzzlerc.sample
  lib/config/default.config.js
Labels: 2.x, changelog:bug-fixes

#1803 Fix bug that limits the number of document deleted by bulk:deleteByQuery
  lib/api/controller/bulk.js
  test/api/controller/bulk.test.js
Labels: 2.x, changelog:bug-fixes

#1775 Allows to load rights for non-existent API actions at startup
  lib/core/security/roleRepository.js
  lib/core/shared/sdk/embeddedSdk.ts
  lib/kuzzle/kuzzle.js
  test/core/security/roleRepository.test.js
  test/core/shared/sdk/embeddedSdk.test.js
  test/kuzzle/kuzzle.test.js
  test/mocks/kuzzle.mock.js
Labels: 2.x, changelog:bug-fixes

#1802 Fix stacktrace cleaning
  lib/kerror/index.js
Labels: 2.x, changelog:bug-fixes

#1799 Add new server:openapi route
  .kuzzlerc.sample
  .travis.yml
  doc/2/api/controllers/server/openapi/index.md
  lib/api/controller/server.js
  lib/config/default.config.js
  lib/config/httpRoutes.js
  lib/core/network/router.js
  package.json
  test/api/controller/server.test.js
  test/core/network/router/httpRequest.test.js
  test/mocks/kuzzle.mock.js
Labels: 2.x, changelog:new-features

#1804 [sonar] fix code smells
  lib/kerror/index.js
Labels: 2.x, changelog:exclude

#1809 Release 2.5.0
  .kuzzlerc.sample
  .travis.yml
  doc/2/api/controllers/server/openapi/index.md
  doc/2/api/essentials/error-codes/services/index.md
  doc/2/plugins/guides/events/realtime/index.md
  docker/scripts/functional-tests-controller.ts
  docker/scripts/start-kuzzle-dev.ts
  features-sdk/Application.feature
  index.ts
  lib/api/controller/bulk.js
  lib/api/controller/server.js
  lib/config/default.config.js
  lib/config/httpRoutes.js
  lib/core/application/backend.ts
  lib/core/network/router.js
  lib/core/security/roleRepository.js
  lib/core/shared/sdk/embeddedSdk.ts
  lib/kerror/codes/1-services.json
  lib/kerror/index.js
  lib/kuzzle/kuzzle.js
  lib/util/interfaces.ts
  package-lock.json
  package.json
  test/api/controller/bulk.test.js
  test/api/controller/server.test.js
  test/core/network/router/httpRequest.test.js
  test/core/security/roleRepository.test.js
  test/core/shared/sdk/embeddedSdk.test.js
  test/kuzzle/kuzzle.test.js
  test/mocks/kuzzle.mock.js
Labels: release

#1815 Repair functional tests (SDK)
  .ci/scripts/run-test.sh
  features-sdk/Application.feature
  package.json
Labels: 2.x, changelog:exclude

#1808 Replace nodemon with a custom reloader
  docker/scripts/reloader.js
  docker/scripts/run-dev.sh
  package-lock.json
  package.json
Labels: 2.x, changelog:exclude

#1811 Add documentation - Getting Started : Quick Start
  doc/2/guides/getting-started/1-quick-start/admin-console-create-connection.png
  doc/2/guides/getting-started/1-quick-start/index.md
Labels: 2.x, changelog:exclude

#1813 Add documentation - Getting Started : Access Control Rights
  doc/2/guides/getting-started/3-access-control-rights/admin-console-profiles.png
  doc/2/guides/getting-started/3-access-control-rights/admin-console-roles.png
  doc/2/guides/getting-started/3-access-control-rights/admin-console-users.png
  doc/2/guides/getting-started/3-access-control-rights/index.md
  doc/2/guides/getting-started/3-access-control-rights/role-profile-user.png
Labels: 2.x, changelog:exclude

#1825 Allow the reloader to restart kuzzle upon a kuzzle crash
  docker/scripts/reloader.js
Labels: 2.x, changelog:exclude

#1818 Allow profile restrictions on Elasticsearch aliases
  doc/2/api/controllers/security/create-or-replace-profile/index.md
  doc/2/api/controllers/security/create-profile/index.md
  doc/2/api/controllers/security/update-profile/index.md
  features-sdk/SecurityController.feature
  features-sdk/step_definitions/controllers-steps.js
  features-sdk/step_definitions/documents-steps.js
  features-sdk/step_definitions/security-steps.js
  features-sdk/support/world.js
  lib/api/controller/security.js
  lib/core/security/profileRepository.js
  lib/model/security/profile.js
  test/api/controller/security/profiles.test.js
  test/core/security/profileRepository.test.js
  test/model/security/profile.test.js
Labels: 2.x, changelog:enhancements

#1829 hotfix: missing lua scripts
  package-lock.json
  package.json
Labels: 2.x, changelog:exclude

#1828 Return an intelligible error when failing to parse kuzzlerc
  doc/2/api/essentials/error-codes/core/index.md
  features-sdk/support/world.js
  features/support/config.js
  features/support/world.js
  lib/config/index.js
  lib/core/application/backend.ts
  lib/kerror/codes/0-core.json
  test/config/index.test.js
  test/kuzzle/kuzzle.test.js
  test/mocks/kuzzle.mock.js
Labels: 2.x, changelog:enhancements

#1824 Add documentation - Getting Started : Add new Controller
  doc/2/guides/getting-started/6-add-new-controller/index.md
Labels: 2.x, changelog:exclude

#1817 Add documentation - Getting Started : Realtime Engine
  doc/2/guides/getting-started/5-realtime-engine/index.md
  doc/2/guides/getting-started/5-realtime/index.md
Labels: 2.x, changelog:exclude

#1812 Add documentation - Getting Started : Storing Data
  doc/2/api/controllers/auth/search-api-keys/index.md
  doc/2/api/controllers/security/search-api-keys/index.md
  doc/2/guides/getting-started/2-storing-and-accessing-data/admin-console-show-document.gif
  doc/2/guides/getting-started/2-storing-and-accessing-data/index.md
  doc/2/guides/getting-started/2-storing-data/index.md
Labels: 2.x, changelog:exclude

#1827 Fix url generation for kaaf
  doc/2/api/essentials/error-codes/plugin/index.md
  docker/scripts/start-kuzzle-dev.ts
  lib/core/application/backend.ts
  lib/core/plugin/pluginsManager.js
  lib/kerror/codes/4-plugin.json
  lib/util/interfaces.ts
  test/core/application/Backend.test.js
  test/core/plugin/pluginsManager.test.js
Labels: 2.x, changelog:bug-fixes

#1826 Add documentation - Getting Started : Modify API behavior
  doc/2/guides/getting-started/7-modify-api-behavior/index.md
  doc/2/guides/getting-started/7-modify-api-behavior/pipes-workflow.png
Labels: 2.x, changelog:exclude

#1832 Add documentation - Getting Started : Deployment
  doc/2/guides/getting-started/8-deploy/deploy-kuzzle-single-node.png
  doc/2/guides/getting-started/8-deploy/index.md
  docker/images/plugin-dev/Dockerfile
Labels: 2.x, changelog:exclude

#1830 Add documentation - Introduction - Why Kuzzle
  doc/2/guides/introduction/1-what-is-kuzzle/feature-acl.png
  doc/2/guides/introduction/1-what-is-kuzzle/feature-api.png
  doc/2/guides/introduction/1-what-is-kuzzle/feature-auth.png
  doc/2/guides/introduction/1-what-is-kuzzle/feature-cluster.png
  doc/2/guides/introduction/1-what-is-kuzzle/feature-data-storage.png
  doc/2/guides/introduction/1-what-is-kuzzle/feature-realtime.png
  doc/2/guides/introduction/1-what-is-kuzzle/index.md
  doc/2/guides/introduction/index.md
  doc/2/guides/what-is-kuzzle/1-what-is-kuzzle/index.md
Labels: 2.x, changelog:exclude

#1831 Add a HTTP endpoint taking a Kuzzle API request in JSON format
  doc/2/api/essentials/query-syntax/index.md
  features-sdk/Api.feature
  features-sdk/step_definitions/controllers-steps.js
  features-sdk/support/world.js
  lib/core/network/router.js
Labels: 2.x, changelog:new-features

#1806 Add deprecation warnings
  features-sdk/ServerController.feature
  features-sdk/step_definitions/controllers-steps.js
  features-sdk/support/hooks.js
  features/step_definitions/http.js
  lib/config/httpRoutes.js
  lib/core/network/router.js
  test/core/network/httpRouter/httpRouter.test.js
  test/core/network/router/httpRequest.test.js
Labels: changelog:enhancements

#1836 Allow kuzzle to handle HTTP forms again
  features/fixtures/multipart_content
  features/kuzzle.feature
  features/step_definitions/http.js
  features/support/api/http.js
  lib/core/network/httpRouter/index.js
  lib/core/network/protocols/http.js
Labels: 2.x, changelog:bug-fixes

#1839 Forbid overriding of native controller in applications
  lib/api/funnel.js
  lib/core/plugin/plugin.js
  lib/core/plugin/pluginsManager.js
  test/core/plugin/pluginsManager.test.js
Labels: 2.x, changelog:bug-fixes

#1834 Add documentation - Getting Started - Harmonization
  doc/2/guides/getting-started/1-run-kuzzle/admin-console-create-connection.png
  doc/2/guides/getting-started/1-run-kuzzle/index.md
  doc/2/guides/getting-started/2-store-and-access-data/admin-console-show-document.gif
  doc/2/guides/getting-started/2-store-and-access-data/index.md
  doc/2/guides/getting-started/3-access-control-rights/admin-console-profiles.png
  doc/2/guides/getting-started/3-access-control-rights/admin-console-roles.png
  doc/2/guides/getting-started/3-access-control-rights/admin-console-users.png
  doc/2/guides/getting-started/3-set-up-permissions/admin-console-profiles.png
  doc/2/guides/getting-started/3-set-up-permissions/admin-console-roles.png
  doc/2/guides/getting-started/3-set-up-permissions/admin-console-users.png
  doc/2/guides/getting-started/3-set-up-permissions/index.md
  doc/2/guides/getting-started/3-set-up-permissions/role-profile-user.png
  doc/2/guides/getting-started/4-authenticate-users/index.md
  doc/2/guides/getting-started/5-subscribe-realtime-notifications/index.md
  doc/2/guides/getting-started/6-write-application/index.md
  doc/2/guides/getting-started/7-create-new-controllers/index.md
  doc/2/guides/getting-started/8-customize-api-behavior/index.md
  doc/2/guides/getting-started/8-customize-api-behavior/pipes-workflow.png
  doc/2/guides/getting-started/9-deploy-your-application/deploy-kuzzle-single-node.png
  doc/2/guides/getting-started/9-deploy-your-application/index.md
  doc/2/guides/introduction/1-what-is-kuzzle/feature-acl.png
  doc/2/guides/introduction/1-what-is-kuzzle/feature-acl.svg
  doc/2/guides/introduction/1-what-is-kuzzle/feature-api.png
  doc/2/guides/introduction/1-what-is-kuzzle/feature-api.svg
  doc/2/guides/introduction/1-what-is-kuzzle/feature-auth.png
  doc/2/guides/introduction/1-what-is-kuzzle/feature-auth.svg
  doc/2/guides/introduction/1-what-is-kuzzle/feature-cluster.png
  doc/2/guides/introduction/1-what-is-kuzzle/feature-data-storage.png
  doc/2/guides/introduction/1-what-is-kuzzle/feature-data-storage.svg
  doc/2/guides/introduction/1-what-is-kuzzle/feature-realtime.png
  doc/2/guides/introduction/1-what-is-kuzzle/feature-realtime.svg
  doc/2/guides/introduction/1-what-is-kuzzle/index.md
Labels: changelog:exclude
