Repository kuzzleio/kuzzle, pull requests merged in 2020-06, with the labels that each got.

#1640 Qualiy of life: faster/better unit tests
  .travis.yml
  package.json
Labels: 2.x, changelog:exclude

#1621 Prevent unhandled rejection in plugin hooks
  doc/2/plugins/guides/events/plugin-events/index.md
  features-sdk/PluginEvents.feature
  features-sdk/run.sh
  features-sdk/step_definitions/realtime-steps.js
  features-sdk/support/hooks.js
  lib/core/plugin/manager.js
  lib/kuzzle/event/kuzzleEventEmitter.js
  plugins/available/functional-test-plugin/index.js
  test/kuzzle/event/kuzzleEventEmitter.test.js
Labels: 2.x, changelog:bug-fixes

#1637 Implement custom redis transaction-like support
  doc/2/api/controllers/memory-storage/mexecute/index.md
  features/kuzzle.feature
  lib/api/controller/memoryStorage.js
  lib/config/httpRoutes.js
  lib/service/cache/redis.js
  test/api/controller/memoryStorage.test.js
  test/service/cache/redis.test.js
Labels: 2.x, changelog:new-features

#1629 Provides a HTTP GET endpoint for document:search
  doc/2/api/controllers/document/search/index.md
  features-sdk/DocumentController.feature
  features-sdk/step_definitions/documents-steps.js
  lib/api/controller/base.js
  lib/config/httpRoutes.js
  lib/service/storage/elasticsearch.js
  package-lock.json
  package.json
  test/api/controller/base.test.js
Labels: 2.x, changelog:enhancements

#1645 Allows to use realtime subscriptions in plugins
  doc/2/api/essentials/error-codes/plugin/index.md
  doc/2/plugins/guides/events/core-kuzzle-start/index.md
  doc/2/plugins/guides/events/kuzzle-start/index.md
  doc/2/plugins/guides/events/kuzzle-state/index.md
  doc/2/plugins/plugin-context/accessors/sdk/index.md
  features-sdk/PluginContext.feature
  features-sdk/step_definitions/realtime-steps.js
  lib/api/controller/index.js
  lib/api/controller/realtime.js
  lib/core/auth/tokenManager.js
  lib/core/network/clientConnection.js
  lib/core/network/entryPoint.js
  lib/core/network/protocols/http.js
  lib/core/network/protocols/internal.js
  lib/core/network/protocols/mqtt.js
  lib/core/network/protocols/protocol.js
  lib/core/network/protocols/websocket.js
  lib/core/plugin/context.js
  lib/core/plugin/sdk/embeddedSdk.js
  lib/core/plugin/sdk/funnelProtocol.js
  lib/core/realtime/hotelClerk.js
  lib/core/realtime/notifier.js
  lib/core/security/loadSecurities.js
  lib/core/storage/bootstrap/internalIndexBootstrap.js
  lib/core/storage/indexStorage.js
  lib/kerror/codes/plugin.json
  lib/kuzzle/event/kuzzleEventEmitter.js
  lib/kuzzle/kuzzle.js
  lib/kuzzle/shutdown.js
  plugins/available/functional-test-plugin/functionalTestPlugin.js
  plugins/available/functional-test-plugin/index.js
  test/api/controller/realtime.test.js
  test/api/rateLimiter.test.js
  test/core/auth/tokenManager.test.js
  test/core/network/entryPoint.test.js
  test/core/network/protocols/http.test.js
  test/core/network/protocols/internal.test.js
  test/core/network/protocols/mqtt.test.js
  test/core/network/protocols/websocket.test.js
  test/core/plugin/context/context.test.js
  test/core/plugin/sdk/embeddedSdk.test.js
  test/core/plugin/sdk/funnelProtocol.test.js
  test/core/realtime/hotelClerk/addSubscription.test.js
  test/core/realtime/hotelClerk/removeCustomerFromAllRooms.test.js
  test/core/realtime/hotelClerk/removeRoomForCustomer.test.js
  test/core/realtime/notifier/notifyMethods.test.js
  test/kuzzle/kuzzle.test.js
  test/kuzzle/shutdown.test.js
  test/mocks/kuzzle.mock.js
Labels: 2.x, changelog:enhancements

#1644 Update swagger to OpenAPI3
  lib/api/swagger.js
Labels: 2.x, changelog:enhancements

#1648 Fix cluster race conditions
  doc/2/api/controllers/document/update/index.md
  docker-compose.yml
  docker-compose/docker-compose-cluster.yml
  docker-compose/scripts/run-dev.sh
  lib/api/controller/document.js
  lib/core/storage/clientAdapter.js
  lib/service/storage/elasticsearch.js
  lib/service/storage/esWrapper.js
  test/api/controller/document.test.js
  test/core/storage/clientAdapter.test.js
  test/service/storage/elasticsearch.test.js
Labels: 2.x, changelog:bug-fixes

#1649 ApiKey info block
  doc/2/api/controllers/auth/create-api-key/index.md
  doc/2/api/controllers/security/create-api-key/index.md
Labels: 2.x, changelog:exclude

#1643 Add errors messages in doc
  doc/2/api/essentials/error-codes/api/index.md
  doc/2/api/essentials/error-codes/core/index.md
  doc/2/api/essentials/error-codes/network/index.md
  doc/2/api/essentials/error-codes/plugin/index.md
  doc/2/api/essentials/error-codes/protocol/index.md
  doc/2/api/essentials/error-codes/security/index.md
  doc/2/api/essentials/error-codes/services/index.md
  doc/2/api/essentials/error-codes/validation/index.md
  doc/build-error-codes.js
  lib/kerror/codes/core.json
  lib/kerror/codes/index.js
  lib/kerror/codes/plugin.json
  lib/kerror/codes/security.json
  lib/kerror/codes/services.json
Labels: 2.x, changelog:exclude

#1636 Reduce images size
  .babelrc
  .ci/privatebuild/Dockerfile
  .ci/scripts/install-plugins.sh
  .ci/scripts/run-test-arm.sh
  .ci/scripts/run-test.sh
  .ci/test-aarch64.yml
  .ci/test-armhf.yml
  .ci/test.yml
  .ci/wait-kuzzle.sh
  .dockerignore
  .travis.yml
  CONTRIBUTING.md
  Dockerfile
  bin/start-kuzzle-server
  bin/wait-elasticsearch
  bin/wait-kuzzle
  build-docker-images.sh
  docker-compose.yml
  docker-compose/scripts/run-dev.sh
  docker-compose/scripts/run.sh
  docker/build-docker-images.sh
  docker/docker-compose-cluster.yml
  docker/fixtures/fixtures.json
  docker/fixtures/mappings.json
  docker/fixtures/securities.json
  docker/images/kuzzle.alpine/Dockerfile
  docker/images/kuzzle.alpine/README.md
  docker/images/kuzzle.scratch/Dockerfile
  docker/images/kuzzle.scratch/README.md
  docker/images/kuzzle/Dockerfile
  docker/images/kuzzle/README.md
  docker/images/plugin-dev/Dockerfile
  docker/images/plugin-dev/README.md
  docker/nginx/kuzzle.conf
  docker/nginx/kuzzle.loc.crt
  docker/nginx/kuzzle.loc.key
  docker/nginx/kuzzleCA.crt
  docker/scripts/clean-node.sh
  docker/scripts/entrypoint.sh
  docker/scripts/install-plugins.sh
  docker/scripts/run-dev.sh
  docker/scripts/run-plugin.sh
  docker/scripts/run-prod.sh
Labels: changelog:enhancements
