Repository kuzzleio/kuzzle, pull requests merged in 2020-01, with the labels that each got.

#1546 Requests rate limit per user
  .ci/test-aarch64.yml
  .ci/test-armhf.yml
  .ci/test.yml
  .kuzzlerc.sample
  default.config.js
  doc/2/api/controllers/security/create-or-replace-profile/index.md
  doc/2/api/controllers/security/create-profile/index.md
  doc/2/api/controllers/security/get-profile/index.md
  doc/2/api/controllers/security/m-get-profiles/index.md
  doc/2/api/controllers/security/scroll-profiles/index.md
  doc/2/api/controllers/security/update-profile/index.md
  doc/2/api/essentials/errors/codes/index.md
  doc/2/guides/essentials/security/index.md
  docker-compose.yml
  features/step_definitions/role.js
  lib/api/funnel.js
  lib/api/rateLimiter.js
  lib/config/error-codes/api.json
  lib/config/index.js
  lib/core/models/repositories/profileRepository.js
  lib/core/models/repositories/repository.js
  lib/core/models/security/profile.js
  lib/core/storage/bootstrap/internalIndexBootstrap.js
  package-lock.json
  package.json
  test/api/funnel/execute.test.js
  test/api/funnel/init.test.js
  test/api/funnel/processRequest.test.js
  test/api/rateLimiter.test.js
  test/config/index.test.js
  test/core/models/repositories/profileRepository.test.js
  test/core/models/security/profile.test.js
Labels: 2.x, changelog:enhancements

#1549 Receive the document updated content when calling document:update
  doc/2/api/controllers/document/update/index.md
  features-sdk/DocumentController.feature
  lib/api/controllers/document.js
  lib/core/notifier.js
  lib/services/elasticsearch.js
  test/core/notifier/notifyDocumentUpdate.test.js
  test/services/elasticsearch.test.js
Labels: 2.x, changelog:enhancements

#1550 Allow to modify collection settings
  doc/2/api/controllers/collection/create/index.md
  doc/2/api/controllers/collection/update-mapping/index.md
  doc/2/api/controllers/collection/update/index.md
  features-sdk/CollectionController.feature
  features-sdk/DocumentController.feature
  features-sdk/step_definitions/collection-steps.js
  features-sdk/step_definitions/controllers-steps.js
  features-sdk/step_definitions/documents-steps.js
  features-sdk/support/world.js
  lib/api/controllers/collection.js
  lib/config/httpRoutes.js
  lib/core/janitor.js
  lib/core/plugins/context.js
  lib/core/storage/clientAdapter.js
  lib/core/storage/indexStorage.js
  lib/services/elasticsearch.js
  test/core/janitor.test.js
  test/core/storage/indexStorage.test.js
  test/mocks/services/elasticsearchClient.mock.js
  test/services/elasticsearch.test.js
Labels: 2.x, changelog:new-features

#1555 Migrate the ci (V1) to use KuzDoc
  .travis.yml
  doc/doc.sh
  package-lock.json
  package.json
Labels: changelog:exclude

#1556 Migrate the ci (V2) to use KuzDoc
  .travis.yml
  doc/doc.sh
  package-lock.json
  package.json
Labels: changelog:exclude

#1562 Add a warning on createUser method for anonymous user
  doc/2/api/controllers/security/create-user/index.md
Labels: 2.x, changelog:exclude

#1565 Fix ES website deadlink for v1
  doc/1/guides/essentials/installing-kuzzle/index.md
  doc/1/guides/essentials/store-access-data/index.md
  doc/1/guides/kuzzle-depth/architecture/index.md
Labels: changelog:exclude

#1564 Fix ES website deadlink
  doc/2/guides/essentials/installing-kuzzle/index.md
  doc/2/guides/essentials/store-access-data/index.md
  doc/2/guides/kuzzle-depth/architecture/index.md
Labels: changelog:exclude

#1560 Add the http verb to the requestContext object
  lib/core/httpRouter/routeHandler.js
  test/core/httpRouter/httpRouter.test.js
Labels: 2.x, changelog:enhancements

#1557 Closure optimization for pipes
  lib/core/plugins/manager.js
  lib/core/plugins/pipeRunner.js
  lib/kuzzle.js
  lib/util/waterfall.js
  package-lock.json
  package.json
  test/core/plugins/manager/pipeRunner.test.js
  test/util/waterfall.test.js
Labels: 2.x, changelog:optimizations

#1554 Add security:mGetUsers route
  doc/2/api/controllers/security/m-get-users/index.md
  features-sdk/SecurityController.feature
  features-sdk/step_definitions/controllers-steps.js
  features-sdk/step_definitions/security-steps.js
  lib/api/controllers/security.js
  lib/config/httpRoutes.js
  test/api/controllers/security/users.test.js
  test/core/models/security/user.test.js
  test/mocks/kuzzle.mock.js
Labels: 2.x, changelog:new-features

#1561 Ensure properties are always declared in the same order (eslint rule)
  .eslintrc.json
  bin/.upgrades/connectors/es.js
  bin/.upgrades/connectors/redis.js
  bin/.upgrades/lib/context.js
  bin/.upgrades/lib/formatters.js
  bin/.upgrades/versions/v1/checkConfiguration.js
  bin/.upgrades/versions/v1/upgradeCache.js
  bin/.upgrades/versions/v1/upgradeStorage.js
  lib/api/controllers/auth.js
  lib/api/controllers/base.js
  lib/api/controllers/bulk.js
  lib/api/controllers/collection.js
  lib/api/controllers/document.js
  lib/api/controllers/index.js
  lib/api/controllers/memoryStorage.js
  lib/api/controllers/security.js
  lib/api/controllers/server.js
  lib/config/documentEventAliases.js
  lib/config/httpRoutes.js
  lib/core/abstractManifest.js
  lib/core/auth/formatProcessing.js
  lib/core/entrypoints/index.js
  lib/core/entrypoints/protocols/http.js
  lib/core/entrypoints/protocols/mqtt.js
  lib/core/entrypoints/protocols/websocket.js
  lib/core/entrypoints/service/httpFormDataStream.js
  lib/core/hotelClerk.js
  lib/core/httpRouter/index.js
  lib/core/httpRouter/routeHandler.js
  lib/core/janitor.js
  lib/core/models/notifications/index.js
  lib/core/models/repositories/repository.js
  lib/core/models/repositories/tokenRepository.js
  lib/core/models/security/profile.js
  lib/core/notifier.js
  lib/core/plugins/context.js
  lib/core/plugins/manager.js
  lib/core/plugins/pipeRunner.js
  lib/core/router.js
  lib/core/statistics.js
  lib/core/storage/bootstrap/internalIndexBootstrap.js
  lib/core/storage/bootstrap/safeBootstrap.js
  lib/core/storage/clientAdapter.js
  lib/core/storage/models/apiKey.js
  lib/core/storage/models/baseModel.js
  lib/core/storage/storageEngine.js
  lib/core/swagger.js
  lib/core/validation/index.js
  lib/core/validation/types/date.js
  lib/kuzzle.js
  lib/services/elasticsearch.js
  lib/util/DocumentExtractor.js
  lib/util/errors.js
  lib/util/esWrapper.js
  lib/util/requestAssertions.js
  lib/util/safeObject.js
  test/core/janitor.test.js
  test/core/storage/bootstrap/internalIndexBootstrap.test.js
Labels: 2.x, changelog:optimizations

#1559 Add document:updateByQuery
  doc/2/api/controllers/collection/refresh/index.md
  doc/2/api/controllers/collection/update/index.md
  doc/2/api/controllers/document/m-update/index.md
  doc/2/api/controllers/document/update-by-query/index.md
  doc/2/api/controllers/security/refresh/index.md
  doc/2/guides/essentials/security/index.md
  features-sdk/DocumentController.feature
  lib/api/controllers/document.js
  lib/config/documentEventAliases.js
  lib/config/httpRoutes.js
  lib/core/storage/clientAdapter.js
  lib/core/storage/indexStorage.js
  lib/services/elasticsearch.js
  test/api/controllers/document.test.js
  test/mocks/clientAdapter.mock.js
  test/mocks/elasticsearch.mock.js
  test/mocks/services/elasticsearchClient.mock.js
  test/services/elasticsearch.test.js
Labels: 2.x, changelog:new-features
