Repository kuzzleio/kuzzle, pull requests merged in 2020-05, with the labels that each got.

#1612 Generic events documentation rewrite
  doc/2/plugins/guides/events/generic-document-events/index.md
Labels: 2.x, changelog:exclude

#1616 Update contributing
  .ci/scripts/run-test-arm.sh
  .ci/scripts/run-test.sh
  .ci/test-aarch64.yml
  .ci/test-armhf.yml
  .ci/test.yml
  .travis.yml
  CONTRIBUTING.md
  features/README.md
  package.json
Labels: changelog:exclude

#1619 Fix API key expiration on realtime subscription
  bin/start-kuzzle-server
  lib/core/auth/tokenManager.js
  package-lock.json
  package.json
  test/core/auth/tokenManager.test.js
Labels: 2.x, changelog:bug-fixes

#1596 Keep the number of opened scroll contexts in check
  lib/api/controllers/admin.js
  lib/core/models/repositories/repository.js
  lib/core/models/repositories/userRepository.js
  lib/core/storage/models/baseModel.js
  lib/services/elasticsearch.js
  test/core/storage/models/baseModel.test.js
  test/kuzzle.test.js
  test/mocks/elasticsearch.mock.js
  test/mocks/services/elasticsearchClient.mock.js
  test/services/elasticsearch.test.js
Labels: 2.x, changelog:bug-fixes

#1598 Add token hash in API key
  doc/2/api/controllers/auth/create-api-key/index.md
  doc/2/api/controllers/auth/search-api-keys/index.md
  doc/2/api/controllers/security/create-api-key/index.md
  doc/2/api/controllers/security/search-api-keys/index.md
  features-sdk/AuthController.feature
  features-sdk/SecurityController.feature
  lib/core/storage/models/apiKey.js
  lib/util/esWrapper.js
  test/core/storage/models/apiKey.test.js
  test/util/esWrapper.test.js
Labels: changelog:enhancements

#1606 Lighter and faster MQTT server
  default.config.js
  lib/core/entrypoints/protocols/mqtt.js
  package-lock.json
  package.json
  test/core/entrypoints/protocols/mqtt.test.js
Labels: 2.x, changelog:enhancements

#1599 Prevent user overriding with admin:loadSecurities
  doc/2/api/controllers/admin/load-securities/index.md
  doc/2/api/controllers/security/create-role/index.md
  doc/2/api/controllers/security/update-role/index.md
  doc/2/api/essentials/error-codes/security/index.md
  features-sdk/AdminController.feature
  features-sdk/step_definitions/auth-steps.js
  features-sdk/step_definitions/controllers-steps.js
  features-sdk/step_definitions/security-steps.js
  features-sdk/support/hooks.js
  lib/api/controllers/admin.js
  lib/api/controllers/base.js
  lib/config/error-codes/security.json
  lib/core/janitor.js
  test/api/controllers/admin.test.js
  test/core/janitor.test.js
Labels: 2.x, changelog:enhancements

#1618 Add user ID in forbidden error log
  lib/api/funnel.js
  lib/config/error-codes/security.json
Labels: 2.x, changelog:enhancements

#1617 Allows inter-plugins method calls with side-effect
  doc/2/api/essentials/error-codes/plugin/index.md
  doc/2/plugins/plugin-context/accessors/trigger/index.md
  features-sdk/PluginContext.feature
  lib/config/error-codes/plugin.json
  lib/core/plugins/context.js
  plugins/available/functional-test-plugin/index.js
  test/core/plugins/context/context.test.js
Labels: 2.x, changelog:enhancements

#1611 create user before credentials
  lib/api/controllers/security.js
  test/api/controllers/security/index.js
  test/api/controllers/security/profiles.test.js
  test/api/controllers/security/roles.test.js
  test/api/controllers/security/users.test.js
Labels: 2.x, changelog:bug-fixes

#1622 Use bytes util
  lib/core/entrypoints/protocols/http.js
  lib/core/entrypoints/protocols/protocol.js
  lib/util/bytes.js
Labels: 2.x, changelog:bug-fixes

#1613 Events overhaul: loose coupling + plugin pipe timeout removal
  .kuzzlerc.sample
  default.config.js
  doc/2/api/essentials/error-codes/plugin/index.md
  doc/2/guides/kuzzle-depth/scalability/index.md
  doc/2/plugins/guides/pipes/index.md
  lib/config/error-codes/plugin.json
  lib/core/events/emitter.js
  lib/core/events/pipeRunner.js
  lib/core/events/waterfall.js
  lib/core/plugins/manager.js
  lib/kuzzle.js
  lib/util/waterfall.js
  test/core/events/emitter.test.js
  test/core/events/pipeRunner.test.js
  test/core/events/waterfall.test.js
  test/core/plugins/manager/pipe.test.js
  test/core/plugins/manager/run.test.js
  test/mocks/kuzzle.mock.js
Labels: 2.x, changelog:enhancements

#1610 Fix errors manager doc
  doc/2/plugins/plugin-context/errors-manager/index.md
  lib/util/errors.js
Labels: 2.x, changelog:exclude

#1625 Install guide: fix min. python version
  doc/2/guides/essentials/installing-kuzzle/index.md
Labels: 2.x, changelog:exclude

#1623 Fix refresh propagation for document:delete
  lib/api/controller/document.js
  test/api/controller/document.test.js
Labels: 2.x, changelog:bug-fixes

#1626 Returns a token expired error when using expired jwt
  lib/core/security/tokenRepository.js
  test/core/security/tokenRepository.test.js
Labels: 2.x, changelog:bug-fixes

#1631 Fix: invalid context on plugin pipes declared with a function name
  features-sdk/PluginEvents.feature
  features-sdk/step_definitions/plugin-events-steps.js
  lib/core/plugin/manager.js
  package-lock.json
  package.json
  plugins/available/functional-test-plugin/index.js
  test/core/plugin/manager/run.test.js
Labels: 2.x, changelog:bug-fixes

#1632 Implement source argument on document:delete & document:deleteByQuery
  doc/2/api/controllers/document/delete-by-query/index.md
  doc/2/api/controllers/document/delete/index.md
  features-sdk/DocumentController.feature
  lib/api/controller/document.js
  test/api/controller/document.test.js
Labels: 2.x, changelog:enhancements

#1635 Use nodemon instead of PM2 for core-dev and plugin-dev images
  .ci/config/pm2.json
  .ci/test-aarch64.yml
  .ci/test-armhf.yml
  .ci/test.yml
  Dockerfile
  doc/2/guides/essentials/installing-kuzzle/index.md
  doc/2/plugins/essentials/getting-started/index.md
  docker-compose.yml
  docker-compose/config/pm2-dev.json
  docker-compose/scripts/devtools.sh
  docker-compose/scripts/run-dev.sh
  lib/kuzzle/dumpGenerator.js
  test/kuzzle/dumpGenerator.test.js
Labels: 2.x, changelog:enhancements
