Repository kuzzleio/kuzzle, pull requests merged in 2020-02, with the labels that each got.

#1535 Fix setting a role with non-existing controller or action
  doc/2/api/controllers/security/create-or-replace-role/index.md
  doc/2/api/controllers/security/create-role/index.md
  doc/2/api/controllers/security/update-role/index.md
  doc/2/api/essentials/errors/codes/index.md
  features-sdk/SecurityController.feature
  features-sdk/step_definitions/controllers-steps.js
  features-sdk/step_definitions/security-steps.js
  features/kuzzle.feature
  lib/api/controllers/security.js
  lib/api/funnel.js
  lib/config/error-codes/security.json
  lib/core/models/repositories/roleRepository.js
  lib/core/plugins/manager.js
  lib/kuzzle.js
  test/api/funnel/processRequest.test.js
  test/core/models/repositories/roleRepository.test.js
  test/kuzzle.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:bug-fixes

#1568 Optimization : get rid of the "delete" keyword on objects
  lib/api/controllers/server.js
  lib/api/funnel.js
  lib/core/entrypoints/protocols/mqtt.js
  lib/core/statistics.js
  lib/core/swagger.js
  lib/services/elasticsearch.js
  test/api/funnel/execute.test.js
  test/core/entrypoints/protocols/mqtt.test.js
  test/core/statistics.test.js
  test/services/elasticsearch.test.js
Labels: 2.x, changelog:optimizations

#1569 Upgrade Node
  Dockerfile
Labels: changelog:exclude

#1572 Fix functional tests
  features-sdk/PluginEvents.feature
Labels: 2.x, changelog:exclude

#1571 Add plugin name in log
  lib/core/plugins/context.js
  lib/util/log.js
  test/core/plugins/context/context.test.js
Labels: 2.x, changelog:enhancements

#1573 better API error codes handling documentation
  doc/2/api/essentials/errors/handling/index.md
Labels: 2.x, changelog:exclude
