Repository kuzzleio/kuzzle, pull requests merged in 2020-04, with the labels that each got.

#1587 Add guide on how to export and import data
  doc/2/api/controllers/admin/dump/index.md
  doc/2/guides/essentials/cli/index.md
  doc/2/guides/essentials/export-import-data/index.md
  doc/2/guides/essentials/kourou-cli/index.md
  doc/2/guides/essentials/plugins/index.md
  doc/2/guides/essentials/security/index.md
  doc/2/guides/essentials/signal-handling/index.md
  doc/2/guides/essentials/store-access-data/index.md
Labels: 2.x, changelog:exclude

#1591 Better error message on 401 and 403
  doc/2/api/essentials/error-codes/security/index.md
  lib/api/funnel.js
  lib/config/error-codes/security.json
  lib/config/error-codes/services.json
  lib/core/storage/clientAdapter.js
  lib/services/elasticsearch.js
  test/util/errors.test.js
Labels: 2.x, changelog:enhancements

#1594 Lighter production dependencies
  bin/start-kuzzle-server
  features/step_definitions/cli.js
  lib/core/janitor.js
  lib/util/bytes.js
  package-lock.json
  package.json
  test/core/janitor.test.js
Labels: 2.x, changelog:exclude

#1593 Use new Kuzzle Vault
  features-sdk/PluginContext.feature
  lib/kuzzle.js
  package-lock.json
  package.json
Labels: changelog:enhancements

#1597 fix security methods not throwing Kuzzle errors
  lib/api/controllers/security.js
Labels: 2.x, changelog:bug-fixes

#1595 Install dependencies when starting a new development stack
  docker-compose/scripts/run-dev.sh
Labels: changelog:exclude

#1600 Fix usage of search_after
  features-sdk/DocumentController.feature
  features-sdk/step_definitions/documents-steps.js
  lib/services/elasticsearch.js
Labels: 2.x, changelog:bug-fixes

#1601 Release 2.1.4
  bin/start-kuzzle-server
  doc/2/api/controllers/collection/list/index.md
  doc/2/api/essentials/error-codes/security/index.md
  docker-compose/scripts/run-dev.sh
  features-sdk/CollectionController.feature
  features-sdk/DocumentController.feature
  features-sdk/PluginContext.feature
  features-sdk/step_definitions/documents-steps.js
  features/step_definitions/cli.js
  lib/api/controllers/collection.js
  lib/api/controllers/security.js
  lib/api/funnel.js
  lib/config/error-codes/security.json
  lib/config/error-codes/services.json
  lib/core/janitor.js
  lib/core/storage/clientAdapter.js
  lib/kuzzle.js
  lib/services/elasticsearch.js
  lib/util/bytes.js
  lib/util/esWrapper.js
  package-lock.json
  package.json
  test/core/janitor.test.js
  test/util/errors.test.js
Labels: release

#1607 Optimization: replaces lodash's memoize with a custom, much faster one
  lib/kuzzle.js
  lib/util/memoize.js
  test/util/memoize.test.js
Labels: 2.x, changelog:exclude

#1608 Update vault guide with Kourou
  doc/2/guides/essentials/secrets-vault/index.md
Labels: 2.x, changelog:exclude

#1602 Add an empty updateByQuery after collection:update
  doc/2/api/controllers/collection/update/index.md
  features-sdk/CollectionController.feature
  lib/services/elasticsearch.js
  test/services/elasticsearch.test.js
Labels: 2.x, changelog:enhancements
