Repository kuzzleio/kuzzle, pull requests merged in 2021-09, with the labels that each got.

#2130 Support ES inner_hits keyword
  doc/2/api/controllers/document/scroll/index.md
  doc/2/api/controllers/document/search/index.md
  doc/2/guides/main-concepts/querying/index.md
  lib/service/storage/elasticsearch.js
  test/service/storage/elasticsearch.test.js
Labels: changelog:bug-fixes

#2128 Customize Open API specification in plugins/controllers
  doc/2/api/errors/error-codes/plugin/index.md
  doc/2/framework/classes/backend-controller/register/index.md
  doc/2/framework/types/controller-definition/index.md
  doc/2/guides/develop-on-kuzzle/api-controllers/index.md
  lib/api/openApiGenerator.js
  lib/core/backend/backendController.ts
  lib/core/plugin/plugin.js
  lib/core/plugin/pluginsManager.js
  lib/kerror/codes/4-plugin.json
  lib/types/ControllerDefinition.ts
  package-lock.json
  package.json
  test/api/openApiGenerator.test.js
  test/core/backend/BackendController.test.js
  test/core/plugin/pluginsManager.test.js
Labels: changelog:enhancements

#2131 Allows to use search queries for roles and profiles
  doc/2/api/controllers/security/create-or-replace-profile/index.md
  doc/2/api/controllers/security/create-or-replace-role/index.md
  doc/2/api/controllers/security/create-profile/index.md
  doc/2/api/controllers/security/create-role/index.md
  doc/2/api/controllers/security/search-profiles/index.md
  doc/2/api/controllers/security/search-roles/index.md
  doc/2/guides/main-concepts/permissions/index.md
  features-legacy/step_definitions/profiles.js
  features-legacy/support/api/apiBase.js
  features-legacy/support/api/http.js
  features/#BackendImport.feature
  features/SecurityController.feature
  lib/api/controllers/securityController.js
  lib/config/default.config.js
  lib/core/security/profileRepository.js
  lib/core/security/roleRepository.js
  lib/core/security/userRepository.js
  lib/core/shared/repository.js
  test/api/controllers/securityController/profiles.test.js
  test/api/controllers/securityController/roles.test.js
  test/core/security/profileRepository.test.js
  test/core/security/roleRepository.test.js
Labels: changelog:enhancements, 2.x

#2136 Fix Wrongly formatted HTTP Response when throwing unauthorized_origin
  lib/api/funnel.js
Labels: changelog:bug-fixes

#2132 Add kuid to realtime events
  doc/2/framework/events/realtime/index.md
  lib/api/controllers/realtimeController.js
  lib/core/plugin/pluginContext.ts
  lib/core/realtime/hotelClerk.js
  test/core/plugin/context/context.test.js
  test/core/realtime/hotelClerk/subscribe.test.js
  test/core/realtime/hotelClerk/unsubscribe.test.js
Labels: changelog:enhancements, 2.x

#2137 Release 2.14.1
  doc/2/api/controllers/document/scroll/index.md
  doc/2/api/controllers/document/search/index.md
  doc/2/api/controllers/security/create-or-replace-profile/index.md
  doc/2/api/controllers/security/create-or-replace-role/index.md
  doc/2/api/controllers/security/create-profile/index.md
  doc/2/api/controllers/security/create-role/index.md
  doc/2/api/controllers/security/search-profiles/index.md
  doc/2/api/controllers/security/search-roles/index.md
  doc/2/api/errors/error-codes/plugin/index.md
  doc/2/framework/classes/backend-controller/register/index.md
  doc/2/framework/events/realtime/index.md
  doc/2/framework/types/controller-definition/index.md
  doc/2/guides/develop-on-kuzzle/api-controllers/index.md
  doc/2/guides/main-concepts/permissions/index.md
  doc/2/guides/main-concepts/querying/index.md
  features-legacy/step_definitions/profiles.js
  features-legacy/support/api/apiBase.js
  features-legacy/support/api/http.js
  features/#BackendImport.feature
  features/SecurityController.feature
  lib/api/controllers/realtimeController.js
  lib/api/controllers/securityController.js
  lib/api/funnel.js
  lib/api/openApiGenerator.js
  lib/config/default.config.js
  lib/core/backend/backend.ts
  lib/core/backend/backendController.ts
  lib/core/plugin/plugin.js
  lib/core/plugin/pluginContext.ts
  lib/core/plugin/pluginsManager.js
  lib/core/realtime/hotelClerk.js
  lib/core/security/profileRepository.js
  lib/core/security/roleRepository.js
  lib/core/security/userRepository.js
  lib/core/shared/KoncordeWrapper.ts
  lib/core/shared/repository.js
  lib/kerror/codes/4-plugin.json
  lib/service/storage/elasticsearch.js
  lib/types/ControllerDefinition.ts
  package-lock.json
  package.json
  test/api/controllers/securityController/profiles.test.js
  test/api/controllers/securityController/roles.test.js
  test/api/openApiGenerator.test.js
  test/core/backend/Backend.test.js
  test/core/backend/BackendConfig.test.js
  test/core/backend/BackendController.test.js
  test/core/backend/BackendHook.test.js
  test/core/backend/BackendImport.test.js
  test/core/backend/BackendPipe.test.js
  test/core/backend/BackendStorage.test.js
  test/core/backend/BackendVault.test.js
  test/core/backend/InternalLogger.test.js
  test/core/plugin/context/context.test.js
  test/core/plugin/pluginsManager.test.js
  test/core/realtime/hotelClerk/subscribe.test.js
  test/core/realtime/hotelClerk/unsubscribe.test.js
  test/core/security/profileRepository.test.js
  test/core/security/roleRepository.test.js
  test/service/storage/elasticsearch.test.js
Labels: release

#2138 Always propagate internal subscriptions to cluster full state
  docker/scripts/start-kuzzle-dev.ts
  lib/core/realtime/hotelClerk.js
  lib/core/shared/sdk/embeddedSdk.ts
  package-lock.json
  package.json
  test/core/realtime/hotelClerk/subscribe.test.js
Labels: changelog:bug-fixes

#2139 Fix kuid in realtime events
  lib/api/controllers/realtimeController.js
  lib/api/funnel.js
  lib/core/auth/tokenManager.js
  lib/core/plugin/pluginContext.ts
  lib/core/realtime/hotelClerk.js
  package-lock.json
  package.json
  test/core/plugin/context/context.test.js
  test/core/realtime/hotelClerk/join.test.js
  test/core/realtime/hotelClerk/subscribe.test.js
  test/core/realtime/hotelClerk/unsubscribe.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:bug-fixes

#2140 Remove experimental banner on framework pages
  doc/2/framework/abstract-classes/controller/constructor/index.md
  doc/2/framework/abstract-classes/controller/properties/index.md
  doc/2/framework/classes/backend-cluster/broadcast/index.md
  doc/2/framework/classes/backend-cluster/off/index.md
  doc/2/framework/classes/backend-cluster/on/index.md
  doc/2/framework/classes/backend-cluster/once/index.md
  doc/2/framework/classes/backend-cluster/properties/index.md
  doc/2/framework/classes/backend-cluster/removeAllListeners/index.md
  doc/2/framework/classes/backend-config/merge/index.md
  doc/2/framework/classes/backend-config/properties/index.md
  doc/2/framework/classes/backend-config/set/index.md
  doc/2/framework/classes/backend-controller/properties/index.md
  doc/2/framework/classes/backend-controller/register/index.md
  doc/2/framework/classes/backend-controller/use/index.md
  doc/2/framework/classes/backend-hook/properties/index.md
  doc/2/framework/classes/backend-hook/register/index.md
  doc/2/framework/classes/backend-import/mappings/index.md
  doc/2/framework/classes/backend-import/profiles/index.md
  doc/2/framework/classes/backend-import/roles/index.md
  doc/2/framework/classes/backend-import/userMappings/index.md
  doc/2/framework/classes/backend-import/users/index.md
  doc/2/framework/classes/backend-pipe/register/index.md
  doc/2/framework/classes/backend-plugin/get/index.md
  doc/2/framework/classes/backend-plugin/list/index.md
  doc/2/framework/classes/backend-plugin/use/index.md
  doc/2/framework/classes/backend-storage/properties/index.md
  doc/2/framework/classes/backend-vault/properties/index.md
  doc/2/framework/classes/backend/constructor/index.md
  doc/2/framework/classes/backend/install/index.md
  doc/2/framework/classes/backend/properties/index.md
  doc/2/framework/classes/backend/start/index.md
  doc/2/framework/classes/backend/trigger/index.md
  doc/2/framework/types/controller-definition/index.md
  doc/2/framework/types/plugin-manifest/index.md
  doc/2/framework/types/request-payload/index.md
  doc/2/framework/types/strategy-definition/index.md
  doc/2/guides/advanced/configuration/index.md
  doc/2/guides/advanced/internal-logger/index.md
  doc/2/guides/advanced/secrets-vault/index.md
Labels: changelog:exclude

#2144 Fix unsubscribe from Embedded SDK
  .eslintignore
  .gitignore
  lib/core/auth/tokenManager.ts
  lib/core/realtime/hotelClerk.js
  lib/core/security/tokenRepository.js
  lib/kuzzle/kuzzle.js
  lib/model/security/token.ts
  test/api/controllers/authController.test.js
  test/api/funnel/checkRights.test.js
  test/core/auth/tokenManager.test.js
  test/core/realtime/hotelClerk/unsubscribe.test.js
  test/core/security/tokenRepository.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:bug-fixes

#2143 Add type for default mappings
  lib/core/backend/backendImport.ts
Labels: changelog:enhancements

#2146 Freeze @elastic/elasticsearch at 7.13.0
  package-lock.json
  package.json
Labels: changelog:bug-fixes

#2141 Refresh ID Card inside Worker Thread to not be impacted by the load on the main Event Loop
  lib/cluster/idCardHandler.js
  lib/cluster/workers/IDCardRenewer.ts
  lib/core/storage/clientAdapter.js
  test/cluster/idCardHandler.test.js
  test/cluster/workers/IDCardRenewer.test.js
  test/mocks/worker.mock.js
Labels: enhancement

#2147 Fix API Key being expired when refreshed
  .gitignore
  doc/2/api/controllers/auth/refresh-token/index.md
  doc/2/api/errors/error-codes/security/index.md
  lib/api/controllers/authController.js
  lib/core/security/tokenRepository.js
  lib/kerror/codes/7-security.json
  test/api/controllers/authController.test.js
  test/core/security/tokenRepository.test.js
Labels: changelog:bug-fixes
