Repository kuzzleio/kuzzle, pull requests merged in 2021-04, with the labels that each got.

#2039 Catch errors when trying to determine the current git commit
  lib/core/backend/backend.ts
  test/core/backend/Backend.test.js
Labels: 2.x, changelog:bug-fixes

#2036 Add bulk:updateByQuery
  doc/2/api/controllers/bulk/update-by-query/index.md
  doc/2/api/controllers/document/update-by-query/index.md
  doc/2/api/errors/error-codes/services/index.md
  doc/2/guides/main-concepts/data-storage/index.md
  features/BulkController.feature
  lib/api/controllers/bulkController.js
  lib/api/controllers/documentController.js
  lib/config/httpRoutes.js
  lib/core/storage/clientAdapter.js
  lib/kerror/codes/1-services.json
  lib/service/storage/elasticsearch.js
  lib/util/extractFields.js
  test/api/controllers/bulkController.test.js
  test/api/controllers/documentController.test.js
  test/core/storage/clientAdapter.test.js
  test/mocks/elasticsearch.mock.js
  test/service/storage/elasticsearch.test.js
  test/util/extractFields.test.js
Labels: changelog:new-features

#2041 ImpersonatedSDK should be able to execute most of the sdk actions
  features/PluginContext.feature
  lib/core/shared/sdk/impersonatedSdk.js
  plugins/available/functional-test-plugin/functionalTestPlugin.js
Labels: 2.x, changelog:bug-fixes

#2043 Fix role loading and node IP configuration in a cluster environment
  .kuzzlerc.sample
  docker/images/kuzzle.alpine/Dockerfile
  docker/images/kuzzle.scratch/Dockerfile
  docker/images/kuzzle/Dockerfile
  docker/images/plugin-dev/Dockerfile
  docker/scripts/start-kuzzle-dev.ts
  lib/cluster/node.js
  lib/config/default.config.js
  lib/config/index.js
  lib/core/network/protocols/httpwsProtocol.js
  lib/kuzzle/kuzzle.js
  package-lock.json
  package.json
  test/cluster/node.test.js
Labels: 2.x, bug

#2045 Hotfix duplicated cors headers on HTTP Request
  lib/api/request/requestResponse.ts
  lib/config/httpRoutes.js
  lib/core/network/httpRouter/index.js
  lib/core/network/protocols/httpwsProtocol.js
  package-lock.json
  package.json
  test/api/request/requestResponse.test.js
  test/core/network/protocols/http.test.js
Labels: 2.x, bug

#2044 Expose Inflector
  .eslintignore
  .gitignore
  doc/2/framework/classes/inflector/index.md
  doc/2/framework/classes/inflector/kebab-case/index.md
  doc/2/framework/classes/inflector/up-first/index.md
  index.ts
  lib/api/request/kuzzleRequest.ts
  lib/api/request/requestResponse.ts
  lib/core/backend/backend.ts
  lib/core/backend/backendPlugin.ts
  lib/core/plugin/pluginsManager.js
  lib/util/inflector.js
  lib/util/inflector.ts
  package.json
Labels: 2.x, changelog:enhancements

#2046 Add KuzzleRequest.getSearchBody documentation
  doc/2/api/controllers/cluster/status/index.md
  doc/2/framework/classes/kuzzle-request/get-search-body/index.md
Labels: 2.x, changelog:exclude

#2050 Cluster: prevent node from starting if IP already used
  lib/cluster/node.js
  test/cluster/node.test.js
Labels: 2.x, changelog:bug-fixes

#2051 Cluster: die if unable to refresh the ID card in time
  lib/cluster/idCardHandler.js
  lib/cluster/node.js
  test/cluster/idCardHandler.test.js
Labels: 2.x, changelog:bug-fixes

#2049 Fix WebSocket rate limiter timer
  docker/scripts/reloader.js
  lib/core/network/protocols/httpwsProtocol.js
Labels: 2.x, changelog:bug-fixes
