Repository kuzzleio/kuzzle, pull requests merged in 2021-12, with the labels that each got.

#2213 Add new API action `server:metrics`
  .gitignore
  doc/2/api/controllers/server/get-all-stats/index.md
  doc/2/api/controllers/server/get-last-stats/index.md
  doc/2/api/controllers/server/get-stats/index.md
  doc/2/api/controllers/server/metrics/index.md
  features/ServerController.feature
  lib/api/controllers/serverController.js
  lib/api/funnel.js
  lib/config/httpRoutes.js
  lib/core/network/router.js
  lib/core/realtime/hotelClerk.ts
  test/api/controllers/serverController.test.js
  test/api/funnel/metrics.test.js
  test/core/network/router/router.test.js
  test/core/realtime/hotelClerk/hotelClerk.test.js
Labels: changelog:new-features

#2220 Upgrade node-segfault-handler to v1.0.4
  package-lock.json
  package.json
Labels: changelog:enhancements

#2221 Return promise in updateCollection adapter
  .eslintignore
  .gitignore
  lib/core/storage/clientAdapter.js
Labels: changelog:bug-fixes

#2218 Remove alpine and scratch images
  docker/build-docker-images.sh
  docker/images/kuzzle.alpine/Dockerfile
  docker/images/kuzzle.alpine/README.md
  docker/images/kuzzle.scratch/Dockerfile
  docker/images/kuzzle.scratch/README.md
Labels: changelog:exclude

#2223 2.15.2 proposal
  .eslintignore
  .gitignore
  lib/core/storage/clientAdapter.js
  package-lock.json
  package.json
Labels: release

#2191 Adding the Open API specification
  doc/2/framework/abstract-classes/base-validation-type/index.md
  features-legacy/support/api/http.js
  features/ServerController.feature
  lib/api/controllers/serverController.js
  lib/api/httpRoutes.js
  lib/api/openApiGenerator.js
  lib/api/openApiGenerator.ts
  lib/api/openapi/documents/count.yaml
  lib/api/openapi/documents/create.yaml
  lib/api/openapi/documents/createOrReplace.yaml
  lib/api/openapi/documents/delete.yaml
  lib/api/openapi/documents/deleteByQuery.yaml
  lib/api/openapi/documents/document.ts
  lib/api/openapi/documents/exists.yaml
  lib/api/openapi/documents/get.yaml
  lib/api/openapi/documents/replace.yaml
  lib/api/openapi/documents/scroll.yaml
  lib/api/openapi/documents/update.yaml
  lib/api/openapi/payloads.yaml
  lib/api/openapi/tools.ts
  lib/config/default.config.js
  package-lock.json
  package.json
  test/api/controllers/serverController.test.js
  test/api/openApiGenerator.test.js
  test/core/network/httpRouter/httpRouter.test.js
Labels: changelog:enhancements

#2216 Remove unicode property names from KuzzleRequest
  lib/api/request/kuzzleRequest.ts
  lib/api/request/requestContext.ts
  lib/api/request/requestInput.ts
  lib/api/request/requestResponse.ts
  lib/core/plugin/pluginsManager.js
  lib/kuzzle/kuzzle.ts
  test/api/controllers/documentController.test.js
  test/api/request/request.test.js
  test/api/request/requestContext.test.js
  test/api/request/requestInput.test.js
  test/api/request/requestResponse.test.js
  test/core/realtime/hotelClerk/subscribe.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:enhancements, 2.x

#2227 Release 2.16.0
  .gitignore
  doc/2/api/controllers/server/get-all-stats/index.md
  doc/2/api/controllers/server/get-last-stats/index.md
  doc/2/api/controllers/server/get-stats/index.md
  doc/2/api/controllers/server/metrics/index.md
  doc/2/framework/abstract-classes/base-validation-type/index.md
  features-legacy/support/api/http.js
  features/ServerController.feature
  lib/api/controllers/serverController.js
  lib/api/funnel.js
  lib/api/httpRoutes.js
  lib/api/openApiGenerator.js
  lib/api/openApiGenerator.ts
  lib/api/openapi/documents/count.yaml
  lib/api/openapi/documents/create.yaml
  lib/api/openapi/documents/createOrReplace.yaml
  lib/api/openapi/documents/delete.yaml
  lib/api/openapi/documents/deleteByQuery.yaml
  lib/api/openapi/documents/document.ts
  lib/api/openapi/documents/exists.yaml
  lib/api/openapi/documents/get.yaml
  lib/api/openapi/documents/replace.yaml
  lib/api/openapi/documents/scroll.yaml
  lib/api/openapi/documents/update.yaml
  lib/api/openapi/payloads.yaml
  lib/api/openapi/tools.ts
  lib/api/request/kuzzleRequest.ts
  lib/api/request/requestContext.ts
  lib/api/request/requestInput.ts
  lib/api/request/requestResponse.ts
  lib/config/default.config.js
  lib/core/network/router.js
  lib/core/plugin/pluginsManager.js
  lib/core/realtime/hotelClerk.ts
  lib/kuzzle/kuzzle.ts
  package-lock.json
  package.json
  test/api/controllers/documentController.test.js
  test/api/controllers/serverController.test.js
  test/api/funnel/metrics.test.js
  test/api/openApiGenerator.test.js
  test/api/request/request.test.js
  test/api/request/requestContext.test.js
  test/api/request/requestInput.test.js
  test/api/request/requestResponse.test.js
  test/core/network/httpRouter/httpRouter.test.js
  test/core/network/router/router.test.js
  test/core/realtime/hotelClerk/hotelClerk.test.js
  test/core/realtime/hotelClerk/subscribe.test.js
  test/mocks/kuzzle.mock.js
Labels: release

#2230 Fix opening of OpenApi definition files
  lib/api/openApiGenerator.ts
  lib/api/openapi/document/index.ts
  lib/api/openapi/index.ts
  package-lock.json
  package.json
Labels: changelog:bug-fixes

#2231 Allows to match KuzzleRequest with Koncorde
  .eslintignore
  .gitignore
  lib/api/request/kuzzleRequest.ts
  lib/api/request/requestContext.ts
  lib/api/request/requestInput.ts
  lib/api/request/requestResponse.ts
  lib/core/plugin/pluginsManager.js
  lib/kuzzle/kuzzle.ts
  package-lock.json
  package.json
  test/api/controllers/documentController.test.js
  test/api/request/request.test.js
  test/api/request/requestContext.test.js
  test/api/request/requestInput.test.js
  test/api/request/requestResponse.test.js
  test/core/realtime/hotelClerk/subscribe.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:enhancements

#2232 Fix OpenAPI specification check at startup
  .eslintignore
  .gitignore
  lib/api/openApiGenerator.ts
  lib/core/backend/backendController.ts
  lib/core/plugin/plugin.js
  lib/core/plugin/pluginsManager.js
  package-lock.json
  package.json
  test/core/backend/BackendController.test.js
Labels: changelog:bug-fixes

#2233 Lazy load Open API definition
  features/ServerController.feature
  lib/api/controllers/serverController.js
  package-lock.json
  package.json
Labels: changelog:bug-fixes

#2238 Support Elasticsearch 7.14+
  .ci/test-cluster.yml
  lib/service/storage/elasticsearch.js
  package-lock.json
  package.json
  test/service/storage/elasticsearch.test.js
Labels: changelog:enhancements
