Repository kuzzleio/kuzzle, pull requests merged in 2021-07, with the labels that each got.

#2084 Use API keys fingerprint as their default ID
  lib/model/storage/apiKey.js
  test/model/storage/apiKey.test.js
Labels: 2.x, changelog:enhancements

#2094 Fix auth:logout expiring apikey
  doc/2/api/controllers/auth/logout/index.md
  lib/api/controllers/authController.js
  lib/core/security/tokenRepository.js
  lib/model/security/token.js
  lib/types/Token.ts
  test/api/controllers/authController.test.js
  test/core/auth/tokenManager.test.js
  test/core/security/tokenRepository.test.js
Labels: changelog:bug-fixes

#2107 Faster collection truncating with deleteByQuery
  lib/api/controllers/collectionController.js
  test/api/controllers/collectionController.test.js
Labels: 2.x, changelog:enhancements

#2109 Fix request unauthorized event
  lib/api/funnel.js
  package-lock.json
  package.json
  test/api/funnel/checkRights.test.js
Labels: 2.x, changelog:bug-fixes

#2108 Allows to manually enable or disable cookie authentication
  .kuzzlerc.sample
  doc/2/guides/main-concepts/authentication/index.md
  lib/api/controllers/authController.js
  lib/api/funnel.js
  lib/config/default.config.js
  lib/config/index.js
  lib/core/network/httpRouter/index.js
  lib/core/network/protocols/httpwsProtocol.js
  test/api/controllers/authController.test.js
  test/api/funnel/checkRights.test.js
  test/config/index.test.js
  test/core/network/httpRouter/httpRouter.test.js
  test/core/network/protocols/http.test.js
Labels: 2.x, changelog:enhancements

#2116 Fix createOrReplace realtime notification not working
  features/DocumentController.feature
  lib/service/storage/elasticsearch.js
  test/service/storage/elasticsearch.test.js
Labels: changelog:bug-fixes

#2115 Add segfault handler that logs segfault stacktraces
  lib/kuzzle/kuzzle.js
  package-lock.json
  package.json
Labels: changelog:enhancements
