Repository kuzzleio/kuzzle, pull requests merged in 2021-01, with the labels that each got.

#1922 Add event type to document notification
  doc/2/api/payloads/notifications/index.md
  doc/2/guides/main-concepts/realtime-engine/index.md
  lib/core/realtime/notification/document.js
  test/core/realtime/notifier/notifyMethods.test.js
Labels: 2.x, changelog:enhancements

#1916 Document error classes
  doc/2/framework/abstract-classes/kuzzle-error/constructor/index.md
  doc/2/framework/abstract-classes/kuzzle-error/index.md
  doc/2/framework/abstract-classes/kuzzle-error/properties/index.md
  doc/2/framework/abstract-classes/kuzzle-error/to-json/index.md
  doc/2/framework/error-classes/bad-request-error/constructor/index.md
  doc/2/framework/error-classes/bad-request-error/index.md
  doc/2/framework/error-classes/bad-request-error/properties/index.md
  doc/2/framework/error-classes/external-service-error/constructor/index.md
  doc/2/framework/error-classes/external-service-error/index.md
  doc/2/framework/error-classes/external-service-error/properties/index.md
  doc/2/framework/error-classes/forbidden-error/constructor/index.md
  doc/2/framework/error-classes/forbidden-error/index.md
  doc/2/framework/error-classes/forbidden-error/properties/index.md
  doc/2/framework/error-classes/gateway-timeout-error/constructor/index.md
  doc/2/framework/error-classes/gateway-timeout-error/index.md
  doc/2/framework/error-classes/gateway-timeout-error/properties/index.md
  doc/2/framework/error-classes/index.md
  doc/2/framework/error-classes/internal-error/constructor/index.md
  doc/2/framework/error-classes/internal-error/index.md
  doc/2/framework/error-classes/internal-error/properties/index.md
  doc/2/framework/error-classes/not-found-error/constructor/index.md
  doc/2/framework/error-classes/not-found-error/index.md
  doc/2/framework/error-classes/not-found-error/properties/index.md
  doc/2/framework/error-classes/partial-error/constructor/index.md
  doc/2/framework/error-classes/partial-error/index.md
  doc/2/framework/error-classes/partial-error/properties/index.md
  doc/2/framework/error-classes/plugin-implementation-error/constructor/index.md
  doc/2/framework/error-classes/plugin-implementation-error/index.md
  doc/2/framework/error-classes/plugin-implementation-error/properties/index.md
  doc/2/framework/error-classes/precondition-error/constructor/index.md
  doc/2/framework/error-classes/precondition-error/index.md
  doc/2/framework/error-classes/precondition-error/properties/index.md
  doc/2/framework/error-classes/service-unavailable-error/constructor/index.md
  doc/2/framework/error-classes/service-unavailable-error/index.md
  doc/2/framework/error-classes/service-unavailable-error/properties/index.md
  doc/2/framework/error-classes/size-limit-error/constructor/index.md
  doc/2/framework/error-classes/size-limit-error/index.md
  doc/2/framework/error-classes/size-limit-error/properties/index.md
  doc/2/framework/error-classes/unauthorized-error/constructor/index.md
  doc/2/framework/error-classes/unauthorized-error/index.md
  doc/2/framework/error-classes/unauthorized-error/properties/index.md
  test/kuzzle/dumpGenerator.test.js
Labels: 2.x, changelog:exclude

#1924 Prevent unhandled rejection in statistics module
  lib/core/statistics/statistics.js
  package-lock.json
  package.json
Labels: 2.x, changelog:bug-fixes

#1919 Add node id to response and logs
  doc/2/api/payloads/notifications/index.md
  doc/2/api/payloads/response/index.md
  doc/2/guides/main-concepts/api/index.md
  lib/api/request/requestResponse.ts
  lib/core/realtime/notification/document.js
  lib/core/realtime/notification/server.js
  lib/core/realtime/notification/user.js
  lib/kuzzle/kuzzle.js
  lib/kuzzle/log.js
  test/api/request/request.test.js
  test/api/request/requestResponse.test.js
  test/core/network/entryPoint.test.js
  test/core/network/protocols/http.test.js
  test/core/realtime/notifier/notifyMethods.test.js
  test/kuzzle/log.test.js
  test/mocks/kuzzle.mock.js
Labels: 2.x, changelog:enhancements

#1929 Configure codecov to better match our needs
  codecov.yml
Labels: 2.x, changelog:exclude

#1926 Add cluster-wide events to applications/plugins
  .ci/scripts/run-test-cluster.sh
  .eslintignore
  .github/actions/functional-tests/action.yml
  .github/workflows/pull_request.workflow.yml
  .github/workflows/push_dev.workflow.yml
  .github/workflows/push_master.workflow.yml
  .gitignore
  .kuzzlerc.sample
  doc/2/framework/classes/backend-cluster/broadcast/index.md
  doc/2/framework/classes/backend-cluster/index.md
  doc/2/framework/classes/backend-cluster/off/index.md
  doc/2/framework/classes/backend-cluster/on/index.md
  doc/2/framework/classes/backend-cluster/once/index.md
  doc/2/framework/classes/backend-cluster/properties/index.md
  doc/2/framework/classes/backend-cluster/removeAllListeners/index.md
  doc/2/framework/classes/backend/properties/index.md
  doc/2/framework/classes/plugin-context-accessors/properties/index.md
  docker/scripts/start-kuzzle-dev.ts
  features/Cluster.feature
  lib/config/default.config.js
  lib/core/application/backend.ts
  lib/core/application/backendCluster.ts
  lib/core/plugin/pluginContext.ts
  lib/kuzzle/event/kuzzleEventEmitter.js
  lib/types/EventHandler.ts
  plugins/available/kuzzle-plugin-cluster/lib/index.js
  plugins/available/kuzzle-plugin-cluster/lib/node.js
Labels: 2.x, changelog:new-features

#1912 Fix checkRights doc
  doc/2/api/controllers/auth/check-rights/index.md
  doc/2/api/controllers/security/check-rights/index.md
Labels: 2.x, changelog:exclude

#1932 Make the list of embedded plugins configurable
  .kuzzlerc.sample
  lib/config/default.config.js
  lib/core/application/backend.ts
  test/core/application/Backend.test.js
Labels: 2.x, changelog:enhancements

#1732 Add support for security:getUserStrategies
  doc/2/api/controllers/security/get-user-strategies/index.md
  features/SecurityController.feature
  lib/api/controller/security.js
  lib/config/httpRoutes.js
  test/api/controller/security/users.test.js
Labels: 2.x, changelog:new-features

#1928 Add document:deleteFields
  doc/2/api/controllers/document/delete-fields/index.md
  features/DocumentController.feature
  lib/api/controller/document.js
  lib/config/httpRoutes.js
  lib/core/shared/store.js
  lib/core/storage/clientAdapter.js
  lib/service/storage/elasticsearch.js
  test/api/controller/document.test.js
  test/core/storage/clientAdapter.test.js
  test/mocks/elasticsearch.mock.js
  test/service/storage/elasticsearch.test.js
Labels: changelog:new-features

#1936 Extract and export HttpRoute from ControllerDefinition
  features/support/assertions.js
  lib/types/ControllerDefinition.ts
Labels: 2.x, changelog:enhancements

#1941 Hotfix: Restore API keys when the cache is wiped clean
  lib/core/security/tokenRepository.js
  lib/kuzzle/internalIndexHandler.js
  package-lock.json
  package.json
  test/core/security/tokenRepository.test.js
  test/kuzzle/internalIndexHandler.test.js
Labels: 2.x, changelog:bug-fixes

#1938 Export BackendCluster class
  .eslintignore
  .gitignore
  index.ts
  lib/core/backend/backend.ts
  lib/core/backend/backendCluster.ts
  lib/core/backend/index.ts
  lib/core/plugin/pluginContext.ts
  lib/kerror/index.js
  lib/types/Controller.ts
  test/core/backend/Backend.test.js
Labels: 2.x, changelog:bug-fixes

#1946 Allows to not send realtime notification on document controller
  doc/2/api/controllers/document/create-or-replace/index.md
  doc/2/api/controllers/document/create/index.md
  doc/2/api/controllers/document/delete-by-query/index.md
  doc/2/api/controllers/document/delete-fields/index.md
  doc/2/api/controllers/document/delete/index.md
  doc/2/api/controllers/document/m-create-or-replace/index.md
  doc/2/api/controllers/document/m-create/index.md
  doc/2/api/controllers/document/m-delete/index.md
  doc/2/api/controllers/document/m-replace/index.md
  doc/2/api/controllers/document/m-update/index.md
  doc/2/api/controllers/document/replace/index.md
  doc/2/api/controllers/document/update-by-query/index.md
  doc/2/api/controllers/document/update/index.md
  doc/2/api/controllers/document/upsert/index.md
  lib/api/controller/document.js
  test/api/controller/document.test.js
Labels: 2.x, changelog:enhancements

#1944 Error stacktrace overhaul
  .eslintignore
  .gitignore
  doc/2/guides/introduction/general-purpose-backend/index.md
  docker/scripts/start-kuzzle-dev.ts
  lib/api/request/kuzzle-request.ts
  lib/core/network/protocols/mqtt.js
  lib/core/network/removeErrorStack.js
  lib/core/shared/sdk/funnelProtocol.js
  lib/kerror/index.js
  lib/kuzzle/kuzzle.js
  lib/service/storage/elasticsearch.js
  lib/service/storage/esWrapper.js
  lib/types/Deprecation.ts
  lib/types/Global.d.ts
  lib/types/Global.ts
  lib/types/ResponsePayload.ts
  lib/types/index.ts
  lib/util/deprecate.js
  lib/util/didYouMean.js
  lib/util/stackTrace.js
  package-lock.json
  package.json
  plugins/available/kuzzle-plugin-cluster/lib/index.js
  test/api/request/request.test.js
  test/core/network/protocols/http.test.js
  test/core/network/protocols/mqtt.test.js
  test/core/network/protocols/websocket.test.js
  test/service/storage/esWrapper.test.js
  test/util/deprecate.test.js
  test/util/errorMatcher.js
  tsconfig.json
Labels: 2.x, changelog:enhancements, stacktrace-overhaul

#1950 Release 2.9.2
  .eslintignore
  .gitignore
  doc/2/api/controllers/document/create-or-replace/index.md
  doc/2/api/controllers/document/create/index.md
  doc/2/api/controllers/document/delete-by-query/index.md
  doc/2/api/controllers/document/delete-fields/index.md
  doc/2/api/controllers/document/delete/index.md
  doc/2/api/controllers/document/m-create-or-replace/index.md
  doc/2/api/controllers/document/m-create/index.md
  doc/2/api/controllers/document/m-delete/index.md
  doc/2/api/controllers/document/m-replace/index.md
  doc/2/api/controllers/document/m-update/index.md
  doc/2/api/controllers/document/replace/index.md
  doc/2/api/controllers/document/update-by-query/index.md
  doc/2/api/controllers/document/update/index.md
  doc/2/api/controllers/document/upsert/index.md
  doc/2/guides/introduction/general-purpose-backend/index.md
  docker/scripts/start-kuzzle-dev.ts
  index.ts
  lib/api/controller/document.js
  lib/api/request/kuzzle-request.ts
  lib/core/backend/backend.ts
  lib/core/backend/backendCluster.ts
  lib/core/backend/index.ts
  lib/core/network/protocols/mqtt.js
  lib/core/network/removeErrorStack.js
  lib/core/plugin/pluginContext.ts
  lib/core/shared/sdk/funnelProtocol.js
  lib/kerror/index.js
  lib/kuzzle/kuzzle.js
  lib/service/storage/elasticsearch.js
  lib/service/storage/esWrapper.js
  lib/types/Controller.ts
  lib/types/Deprecation.ts
  lib/types/Global.d.ts
  lib/types/Global.ts
  lib/types/ResponsePayload.ts
  lib/types/index.ts
  lib/util/deprecate.js
  lib/util/didYouMean.js
  lib/util/stackTrace.js
  package-lock.json
  package.json
  plugins/available/kuzzle-plugin-cluster/lib/index.js
  test/api/controller/document.test.js
  test/api/request/request.test.js
  test/core/backend/Backend.test.js
  test/core/network/protocols/http.test.js
  test/core/network/protocols/mqtt.test.js
  test/core/network/protocols/websocket.test.js
  test/service/storage/esWrapper.test.js
  test/util/deprecate.test.js
  test/util/errorMatcher.js
  tsconfig.json
Labels: release
