Repository kuzzleio/kuzzle, pull requests merged in 2021-05, with the labels that each got.

#2056 Update cluster topology during handshake
  lib/cluster/node.js
  test/cluster/node.test.js
Labels: 2.x, changelog:bug-fixes

#2057 Prevent conflicting names/characters in new indexes/collections
  lib/service/storage/elasticsearch.js
  test/service/storage/elasticsearch.test.js
Labels: 2.x, changelog:bug-fixes

#2054 Improve API performances
  lib/api/request/kuzzleRequest.ts
  lib/core/network/accessLogger.js
  lib/core/network/entryPoint.js
  lib/core/network/protocols/httpwsProtocol.js
  lib/core/network/protocols/mqttProtocol.js
  lib/model/security/role.js
  package-lock.json
  package.json
  test/core/network/accessLogger.test.js
  test/core/network/entryPoint.test.js
  test/core/network/protocols/mqtt.test.js
  test/core/network/protocols/websocket.test.js
Labels: 2.x, changelog:optimizations

#2048 Framework: allow the execution of code only once
  .gitignore
  doc/2/api/errors/error-codes/plugin/index.md
  doc/2/framework/classes/backend/install/index.md
  doc/2/framework/classes/request-input/properties/index.md
  lib/config/default.config.js
  lib/core/backend/applicationManager.ts
  lib/core/backend/backend.ts
  lib/core/backend/backendConfig.ts
  lib/core/backend/backendController.ts
  lib/core/backend/backendHook.ts
  lib/core/backend/backendPipe.ts
  lib/core/backend/backendPlugin.ts
  lib/core/backend/backendStorage.ts
  lib/core/backend/backendVault.ts
  lib/core/backend/index.ts
  lib/core/backend/internalLogger.ts
  lib/kerror/codes/4-plugin.json
  lib/kuzzle/kuzzle.js
  lib/types/index.ts
  test/core/backend/Backend.test.js
  test/core/backend/BackendConfig.test.js
  test/core/backend/BackendController.test.js
  test/core/backend/BackendHook.test.js
  test/core/backend/BackendPipe.test.js
  test/core/backend/BackendStorage.test.js
  test/core/backend/BackendVault.test.js
  test/core/backend/InternalLogger.test.js
  test/kuzzle/kuzzle.test.js
Labels: changelog:new-features

#2058 Update cluster documentation page
  doc/2/guides/advanced/cluster-scalability/index.md
Labels: 2.x, changelog:exclude

#2059 Websocket cookie propagation after Upgrade
  lib/core/network/protocols/httpwsProtocol.js
  test/core/network/protocols/websocket.test.js
  test/mocks/uWS.mock.js
Labels: 2.x, changelog:enhancements

#2060 Coerce ES version before verifying if it's compatible
  doc/2/api/errors/error-codes/services/index.md
  lib/kerror/codes/1-services.json
  lib/service/storage/elasticsearch.js
Labels: 2.x, changelog:bug-fixes

#2063 Access Logs: request responses may contain unserializable objects
  .eslintignore
  lib/core/network/accessLogger.js
  package-lock.json
  package.json
  test/core/network/accessLogger.test.js
Labels: 2.x, changelog:bug-fixes

#2052 Use the newly published hot reloader Ergol
  config/ergol.config.json
  docker/scripts/reloader.js
  docker/scripts/run-dev.sh
  package-lock.json
  package.json
Labels: changelog:exclude

#2062 Fix documentation (dead links, troubleshooting, missing import)
  doc/2/guides/develop-on-kuzzle/event-system/index.md
  doc/2/guides/getting-started/authenticate-users/index.md
  doc/2/guides/getting-started/customize-api-behavior/index.md
  doc/2/guides/getting-started/run-kuzzle/index.md
  doc/2/guides/introduction/general-purpose-backend/index.md
Labels: changelog:exclude

#2068 Cluster: better IP inference and configuration
  .kuzzlerc.sample
  lib/cluster/node.js
  lib/cluster/subscriber.js
  lib/config/default.config.js
  lib/config/index.js
  package-lock.json
  package.json
  test/cluster/node.test.js
Labels: 2.x, changelog:enhancements

#2069 Improve index cache loading
  lib/core/storage/clientAdapter.js
  lib/service/storage/elasticsearch.js
  test/core/storage/clientAdapter.test.js
  test/mocks/elasticsearch.mock.js
  test/service/storage/elasticsearch.test.js
Labels: 2.x, changelog:enhancements

#2064 Add methods to list and get loaded plugins
  CHANGELOG.md
  doc/2/api/errors/error-codes/plugin/index.md
  doc/2/framework/classes/backend-plugin/get/index.md
  doc/2/framework/classes/backend-plugin/list/index.md
  doc/2/guides/develop-on-kuzzle/api-controllers/index.md
  lib/api/controllers/authController.js
  lib/api/controllers/serverController.js
  lib/core/backend/backendPlugin.ts
  lib/kerror/codes/4-plugin.json
  test/api/controllers/authController.test.js
  test/core/backend/BackendPlugin.test.js
Labels: 2.x, changelog:enhancements

#2071 Release 2.12.2
  .kuzzlerc.sample
  CHANGELOG.md
  config/ergol.config.json
  doc/2/api/errors/error-codes/plugin/index.md
  doc/2/framework/classes/backend-plugin/get/index.md
  doc/2/framework/classes/backend-plugin/list/index.md
  doc/2/guides/develop-on-kuzzle/api-controllers/index.md
  doc/2/guides/develop-on-kuzzle/event-system/index.md
  doc/2/guides/getting-started/authenticate-users/index.md
  doc/2/guides/getting-started/customize-api-behavior/index.md
  doc/2/guides/getting-started/run-kuzzle/index.md
  doc/2/guides/introduction/general-purpose-backend/index.md
  docker/scripts/reloader.js
  docker/scripts/run-dev.sh
  lib/api/controllers/authController.js
  lib/api/controllers/serverController.js
  lib/cluster/node.js
  lib/cluster/subscriber.js
  lib/config/default.config.js
  lib/config/index.js
  lib/core/backend/backendPlugin.ts
  lib/core/storage/clientAdapter.js
  lib/kerror/codes/4-plugin.json
  lib/service/storage/elasticsearch.js
  package-lock.json
  package.json
  test/api/controllers/authController.test.js
  test/cluster/node.test.js
  test/core/backend/BackendPlugin.test.js
  test/core/storage/clientAdapter.test.js
  test/mocks/elasticsearch.mock.js
  test/service/storage/elasticsearch.test.js
Labels: release

#1948 New API action: security:searchUsersByCredentials
  doc/2/api/controllers/security/search-users-by-credentials/index.md
  doc/2/api/errors/error-codes/plugin/index.md
  doc/2/framework/classes/plugin-storage/bootstrap/index.md
  doc/2/framework/classes/plugin-strategy/add/index.md
  doc/2/guides/write-plugins/integrate-authentication-strategy/index.md
  lib/api/controllers/baseController.js
  lib/api/controllers/securityController.js
  lib/config/httpRoutes.js
  lib/kerror/codes/4-plugin.json
  lib/types/StrategyDefinition.ts
  test/api/controllers/securityController/credentials.test.js
Labels: 2.x, changelog:new-features
