Repository kuzzleio/kuzzle, pull requests merged in 2021-02, with the labels that each got.

#1943 Implement new _storageStats route
  doc/2/api/controllers/index/stats/index.md
  features/IndexController.feature
  lib/api/controller/index.js
  lib/config/httpRoutes.js
  lib/core/storage/clientAdapter.js
  lib/service/storage/elasticsearch.js
  test/api/controller/index.test.js
  test/core/storage/clientAdapter.test.js
  test/mocks/elasticsearch.mock.js
  test/mocks/service/elasticsearchClient.mock.js
  test/service/storage/elasticsearch.test.js
Labels: 2.x, changelog:new-features

#1954 Dead link to boy scout rule
  CONTRIBUTING.md
Labels: 2.x, changelog:exclude

#1951 Update our CONTRIBUTING templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: changelog:exclude

#1947 Remove "plugin" suffix/prefix from inferred plugin name
  .kuzzlerc.sample
  doc/2/guides/develop-on-kuzzle/external-plugins/index.md
  lib/core/backend/backend.ts
  lib/core/backend/backendPlugin.ts
  lib/core/backend/index.ts
  test/core/backend/Backend.test.js
  test/core/backend/BackendPlugin.test.js
Labels: 2.x, changelog:enhancements

#1955 Documentation: badly formatted links
  doc/2/framework/events/http/index.md
Labels: 2.x, changelog:exclude

#1970 [HOTFIX] Propagate metadata for document:updateByQuery
  doc/2/api/controllers/document/create-or-replace/index.md
  doc/2/api/controllers/document/create/index.md
  doc/2/api/controllers/document/delete-by-query/index.md
  doc/2/api/controllers/document/delete-fields/index.md
  doc/2/api/controllers/document/delete/index.md
  doc/2/api/controllers/document/m-create-or-replace/index.md
  doc/2/api/controllers/document/m-create/index.md
  doc/2/api/controllers/document/m-delete/index.md
  doc/2/api/controllers/document/m-replace/index.md
  doc/2/api/controllers/document/m-update/index.md
  doc/2/api/controllers/document/replace/index.md
  doc/2/api/controllers/document/update-by-query/index.md
  doc/2/api/controllers/document/update/index.md
  doc/2/api/controllers/document/upsert/index.md
  lib/api/controller/document.js
  lib/service/storage/elasticsearch.js
  package-lock.json
  package.json
  test/api/controller/document.test.js
  test/service/storage/elasticsearch.test.js
Labels: 2.x, changelog:bug-fixes

#1949 Allow to generate human readable kuid for users
  doc/2/api/controllers/security/create-first-admin/index.md
  doc/2/api/controllers/security/create-restricted-user/index.md
  doc/2/api/controllers/security/create-user/index.md
  lib/api/controller/base.js
  lib/api/controller/security.js
Labels: 2.x, changelog:enhancements, release-kuzzle-2.10

#1958 Add an application-level PING for WebSocket
  doc/2/api/protocols/websocket/index.md
  features/Websocket.feature
  features/step_definitions/websocket-steps.js
  features/support/hooks.js
  lib/core/network/protocols/websocket.js
  test/core/network/protocols/websocket.test.js
Labels: 2.x, changelog:enhancements, release-kuzzle-2.10

#1925 Fix OpenApi Format + Implement route testing
  features/ServerController.feature
  features/step_definitions/controllers-steps.js
  lib/api/controller/server.js
  lib/api/openApiGenerator.js
  test/api/openApiGenerator.test.js
Labels: 2.x, changelog:bug-fixes, changelog:enhancements, release-kuzzle-2.10

#1975 Upgrade plugin logger version to 3.0.2
  .ci/test-cluster.yml
  .github/actions/functional-tests/action.yml
  .github/workflows/pull_request.workflow.yml
  .github/workflows/push_dev.workflow.yml
  .github/workflows/push_master.workflow.yml
  .gitignore
  docker/scripts/start-kuzzle-dev.ts
  features-legacy/kuzzle.feature
  features-legacy/support/hooks.js
  features/IndexController.feature
  package-lock.json
  package.json
  plugins/available/functional-test-plugin/functionalTestPlugin.js
  tsconfig.json
Labels: changelog:enhancements, release-kuzzle-2.10

#1930 Allow to check user rights when using EmbeddedSDK.as impersonation
  doc/2/framework/classes/embedded-sdk/as/index.md
  doc/2/guides/develop-on-kuzzle/embedded-sdk/index.md
  features/PluginContext.feature
  lib/api/controllers/adminController.js
  lib/api/controllers/authController.js
  lib/api/controllers/baseController.js
  lib/api/controllers/bulkController.js
  lib/api/controllers/collectionController.js
  lib/api/controllers/documentController.js
  lib/api/controllers/index.js
  lib/api/controllers/indexController.js
  lib/api/controllers/memoryStorageController.js
  lib/api/controllers/realtimeController.js
  lib/api/controllers/securityController.js
  lib/api/controllers/serverController.js
  lib/api/funnel.js
  lib/core/backend/backend.ts
  lib/core/plugin/pluginsManager.js
  lib/core/shared/sdk/embeddedSdk.ts
  lib/core/shared/sdk/funnelProtocol.js
  lib/core/shared/sdk/impersonatedSdk.js
  lib/types/Global.ts
  plugins/available/functional-test-plugin/functionalTestPlugin.js
  test/api/controllers/adminController.test.js
  test/api/controllers/authController.test.js
  test/api/controllers/baseController.test.js
  test/api/controllers/bulkController.test.js
  test/api/controllers/collectionController.test.js
  test/api/controllers/documentController.test.js
  test/api/controllers/indexController.test.js
  test/api/controllers/memoryStorageController.test.js
  test/api/controllers/realtimeController.test.js
  test/api/controllers/securityController/credentials.test.js
  test/api/controllers/securityController/profiles.test.js
  test/api/controllers/securityController/roles.test.js
  test/api/controllers/securityController/security.test.js
  test/api/controllers/securityController/users.test.js
  test/api/controllers/serverController.test.js
  test/api/funnel/init.test.js
  test/api/funnel/processRequest.test.js
  test/core/backend/Backend.test.js
  test/core/backend/BackendPlugin.test.js
  test/core/plugin/pluginsManager.test.js
  test/core/security/roleRepository.test.js
  test/core/shared/sdk/embeddedSdk.test.js
  test/core/shared/sdk/funnelProtocol.test.js
  test/core/shared/sdk/impersonatedSdk.test.js
  test/mocks/controller.mock.js
Labels: 2.x, changelog:enhancements, release-kuzzle-2.10

#1983 Upgrade script: URL validation didn't accept non-FQDN addresses
  bin/.upgrades/connectors/es.js
  bin/.upgrades/versions/v1/checkConfiguration.js
  bin/.upgrades/versions/v1/index.js
  bin/upgrade
Labels: 2.x, changelog:bug-fixes

#1985 docs: fix invalid links and type formats
  doc/2/api/controllers/auth/refresh-token/index.md
  doc/2/framework/events/api/index.md
  doc/2/framework/events/core/index.md
  doc/2/framework/events/generic-document/index.md
  doc/2/framework/events/hook/index.md
  doc/2/framework/events/http/index.md
  doc/2/framework/events/plugin/index.md
  doc/2/framework/events/realtime/index.md
  doc/2/framework/events/request/index.md
  doc/2/framework/events/wildcard/index.md
Labels: 2.x, changelog:exclude

#1984 Upgrade script: fix large documents migration
  bin/.upgrades/lib/context.js
  bin/.upgrades/versions/v1/upgradeStorage.js
  bin/upgrade
Labels: 2.x, changelog:bug-fixes

#1977 Add full path in notification updated fields
  lib/api/controllers/documentController.js
  lib/service/storage/queryTranslator.js
  test/api/controllers/documentController.test.js
  test/service/storage/queryTranslator.test.js
Labels: 2.x, changelog:bug-fixes, release-kuzzle-2.10

#1959 Enable usage of HttpOnly Cookies to authenticate browsers
  .ci/test-aarch64.yml
  .ci/test-armhf.yml
  .ci/test-cluster.yml
  .ci/test.yml
  .eslintignore
  doc/2/api/controllers/auth/check-token/index.md
  doc/2/api/controllers/auth/login/index.md
  doc/2/api/controllers/auth/logout/index.md
  doc/2/api/controllers/auth/refresh-token/index.md
  doc/2/api/errors/error-codes/core/index.md
  doc/2/api/errors/error-codes/security/index.md
  doc/2/api/protocols/http/index.md
  doc/2/guides/main-concepts/authentication/index.md
  features/AuthController.feature
  features/step_definitions/controllers-steps.js
  lib/api/controllers/authController.js
  lib/api/funnel.js
  lib/config/default.config.js
  lib/core/network/httpRouter/index.js
  lib/kerror/codes/0-core.json
  lib/kerror/codes/7-security.json
  package.json
  test/api/controllers/authController.test.js
  test/api/funnel/checkRights.test.js
  test/core/network/httpRouter/httpRouter.test.js
Labels: 2.x, changelog:new-features, release-kuzzle-2.10

#1989 Add missing SinceBadge on the new index:stats API action
  doc/2/api/controllers/index/stats/index.md
Labels: 2.x, changelog:exclude
