Repository kuzzleio/kuzzle, pull requests merged in 2021-06, with the labels that each got.

#2070 Kuzzle action with ES queries should not tolerate script keyword
  doc/2/api/errors/error-codes/services/index.md
  lib/kerror/codes/1-services.json
  lib/service/storage/elasticsearch.js
  lib/util/safeObject.js
  test/service/storage/elasticsearch.test.js
Labels: changelog:bug-fixes

#2078 Check plugin required kuzzleVersion
  doc/2/api/errors/error-codes/plugin/index.md
  lib/core/backend/backend.ts
  lib/core/plugin/plugin.js
  lib/core/plugin/pluginsManager.js
  lib/kerror/codes/4-plugin.json
  lib/kuzzle/kuzzle.js
  lib/types/Plugin.ts
  test/core/backend/Backend.test.js
  test/core/backend/BackendPipe.test.js
  test/core/plugin/plugin.test.js
Labels: 2.x, changelog:bug-fixes

#2081 Allows to use aliased collection with forbidden characters
  lib/service/storage/elasticsearch.js
  test/service/storage/elasticsearch.test.js
Labels: 2.x, changelog:bug-fixes

#2079 [kuzdoc] Install latest minor
  .github/actions/deploy-doc/action.yml
Labels: changelog:exclude

#2083 Add a configurable maximum TTL for API keys
  .kuzzlerc.sample
  doc/2/guides/advanced/api-keys/index.md
  doc/2/guides/main-concepts/authentication/index.md
  lib/api/controllers/securityController.js
  lib/config/default.config.js
  lib/core/security/tokenRepository.js
  lib/model/storage/apiKey.js
  test/core/security/tokenRepository.test.js
  test/model/storage/apiKey.test.js
Labels: 2.x, changelog:enhancements

#2082 Remove the _kuzzle_keep collection from non-empty indexes
  lib/service/storage/elasticsearch.js
  test/service/storage/elasticsearch.test.js
Labels: 2.x, changelog:optimizations

#2087 Fix Main concepts permissions deadlinks
  doc/2/guides/main-concepts/permissions/index.md
Labels: bug

#2080 [kuzdoc] Install latest minor (2-dev)
  .github/actions/deploy-doc/action.yml
Labels: changelog:exclude

#2088 Adapt default encrypted secret file path for kaaf
  features/step_definitions/websocket-steps.js
  lib/kuzzle/vault.js
Labels: 2.x, changelog:bug-fixes

#2089 Fix security refresh doc
  doc/2/api/controllers/security/refresh/index.md
Labels: changelog:exclude, enhancement

#2092 Add minimum rights to connect to AC
  doc/2/guides/getting-started/run-kuzzle/index.md
Labels: changelog:exclude

#2093 Fix after subscribe event
  doc/2/framework/events/realtime/index.md
  lib/core/realtime/hotelClerk.js
  test/core/realtime/hotelClerk/subscribe.test.js
  test/core/realtime/hotelClerk/unsubscribe.test.js
Labels: 2.x, changelog:bug-fixes

#2066 Support for elasticsearch 7.13.1
  lib/service/storage/elasticsearch.js
Labels: changelog:enhancements, services-upgrade

#1974 Official support Redis 6.2.4
  .ci/test-aarch64.yml
  .ci/test-armhf.yml
  .ci/test-cluster.yml
  .ci/test.yml
  doc/2/guides/advanced/configuration/index.md
  doc/2/guides/getting-started/deploy-your-application/index.md
  docker-compose.yml
  docker/images/plugin-dev/README.md
Labels: 2.x, changelog:enhancements, services-upgrade

#1971 Official support for Node.js 14.17.0
  .ci/scripts/run-test-arm.sh
  .ci/scripts/run-test-cluster.sh
  .ci/scripts/run-test.sh
  .github/workflows/pull_request.workflow.yml
  .github/workflows/push_dev.workflow.yml
  .github/workflows/push_master.workflow.yml
  docker-compose.yml
  docker/scripts/run-dev.sh
Labels: 2.x, changelog:enhancements, services-upgrade

#2099 [Hotfix] Fix race condition when creating/deleting hidden collection
  lib/service/storage/elasticsearch.js
  lib/service/storage/esWrapper.js
  package-lock.json
  package.json
  test/service/storage/elasticsearch.test.js
Labels: 2.x, changelog:bug-fixes

#2101 Upgrade Koncorde to v4
  .eslintignore
  .gitignore
  .kuzzlerc.sample
  doc/2/api/errors/error-codes/core/index.md
  index.ts
  lib/api/controllers/baseController.js
  lib/cluster/node.js
  lib/cluster/protobuf/sync.proto
  lib/cluster/publisher.js
  lib/cluster/state.js
  lib/cluster/subscriber.js
  lib/config/default.config.js
  lib/config/index.js
  lib/core/plugin/pluginContext.ts
  lib/core/realtime/hotelClerk.js
  lib/core/realtime/notifier.js
  lib/core/shared/KoncordeWrapper.ts
  lib/core/validation/types/geoPoint.js
  lib/core/validation/types/geoShape.js
  lib/core/validation/validation.js
  lib/kerror/codes/0-core.json
  lib/kuzzle/kuzzle.js
  lib/util/koncordeCompat.ts
  package-lock.json
  package.json
  test/cluster/node.test.js
  test/cluster/publisher.test.js
  test/cluster/state.test.js
  test/cluster/subscriber.test.js
  test/core/plugin/context/context.test.js
  test/core/realtime/hotelClerk/listCollections.test.js
  test/core/realtime/hotelClerk/subscribe.test.js
  test/core/realtime/notifier/notifyDocumentCreate.test.js
  test/core/realtime/notifier/notifyDocumentDelete.test.js
  test/core/realtime/notifier/notifyDocumentUpdate.test.js
  test/core/validation/init.test.js
  test/core/validation/types/geoShape.test.js
  test/core/validation/validate.test.js
  test/mocks/kuzzle.mock.js
Labels: 2.x, changelog:enhancements

#2102 [Hotfix] startup loading of indexes with 0 collections in index cache
  lib/service/storage/elasticsearch.js
  package-lock.json
  package.json
  test/service/storage/elasticsearch.test.js
Labels: 2.x, changelog:bug-fixes
