Repository kuzzleio/kuzzle, pull requests merged in 2021-03, with the labels that each got.

#2004 Cookie authentication hotfix
  lib/api/funnel.js
  test/api/funnel/checkRights.test.js
Labels: changelog:bug-fixes

#2003 Fix import of ACLs w/ credentials at startup
  lib/kuzzle/kuzzle.js
  package-lock.json
  package.json
  test/kuzzle/kuzzle.test.js
Labels: 2.x, changelog:bug-fixes

#1990 Expose vault before startup
  doc/2/framework/classes/backend-vault/properties/index.md
  doc/2/guides/advanced/configuration/index.md
  doc/2/guides/advanced/secrets-vault/index.md
  lib/core/backend/backend.ts
  lib/core/backend/backendPlugin.ts
  lib/core/backend/index.ts
  lib/kuzzle/vault.js
  test/core/backend/Backend.test.js
Labels: 2.x, changelog:enhancements

#2006 Hotfix 2.10.1
  lib/api/funnel.js
  lib/kuzzle/kuzzle.js
  package-lock.json
  package.json
  test/api/funnel/checkRights.test.js
  test/kuzzle/kuzzle.test.js
Labels: 2.x, changelog:exclude, release

#1987 Development features must be opt-in instead of opt-out
  lib/service/storage/elasticsearch.js
  lib/service/storage/esWrapper.js
  lib/util/deprecate.js
  lib/util/didYouMean.js
  test/core/plugin/pluginsManager.test.js
  test/core/shared/sdk/embeddedSdk.test.js
  test/service/storage/elasticsearch.test.js
  test/util/didYouMean.test.js
Labels: 2.x, changelog:bug-fixes

#2002 Fix a deadlink in the CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: 2.x, changelog:exclude

#1995 Add kourou examples to document controller
  doc/2/api/controllers/document/count/index.md
  doc/2/api/controllers/document/create-or-replace/index.md
  doc/2/api/controllers/document/create/index.md
  doc/2/api/controllers/document/delete-by-query/index.md
  doc/2/api/controllers/document/delete-fields/index.md
  doc/2/api/controllers/document/delete/index.md
  doc/2/api/controllers/document/exists/index.md
  doc/2/api/controllers/document/get/index.md
  doc/2/api/controllers/document/m-create-or-replace/index.md
  doc/2/api/controllers/document/m-create/index.md
  doc/2/api/controllers/document/m-delete/index.md
  doc/2/api/controllers/document/m-get/index.md
  doc/2/api/controllers/document/m-replace/index.md
  doc/2/api/controllers/document/m-update/index.md
  doc/2/api/controllers/document/replace/index.md
  doc/2/api/controllers/document/scroll/index.md
  doc/2/api/controllers/document/search/index.md
  doc/2/api/controllers/document/update-by-query/index.md
  doc/2/api/controllers/document/update/index.md
  doc/2/api/controllers/document/upsert/index.md
  doc/2/api/controllers/document/validate/index.md
Labels: 2.x, changelog:exclude

#1992 Fix usage of empty koncorde filters in document:search
  lib/api/controllers/baseController.js
  lib/api/controllers/documentController.js
  test/api/controllers/baseController.test.js
Labels: 2.x, changelog:bug-fixes

#1996 Allows dynamic pipe registration
  doc/2/api/errors/error-codes/plugin/index.md
  docker/scripts/start-kuzzle-dev.ts
  features/Application.feature
  features/support/hooks.js
  index.ts
  lib/api/controllers/securityController.js
  lib/core/backend/backend.ts
  lib/core/plugin/pluginsManager.js
  lib/kerror/codes/4-plugin.json
  lib/kuzzle/event/kuzzleEventEmitter.js
  test/core/backend/Backend.test.js
  test/core/plugin/pluginsManager.test.js
  test/kuzzle/event/kuzzleEventEmitter.test.js
Labels: 2.x, changelog:exclude

#2005 Deprecate listing of realtime collections
  doc/2/api/controllers/collection/list/index.md
  doc/2/guides/getting-started/customize-api-behavior/index.md
  lib/api/controllers/collectionController.js
  package-lock.json
Labels: 2.x, changelog:new-features

#1991 Prefix ApiKey tokens and node name
  lib/api/controllers/securityController.js
  lib/core/security/tokenRepository.js
  lib/kuzzle/kuzzle.js
  lib/model/storage/apiKey.js
  lib/util/name-generator.js
  test/core/security/tokenRepository.test.js
  test/model/storage/apiKey.test.js
Labels: 2.x, changelog:enhancements

#2009 Release 2.10.2
  doc/2/api/controllers/collection/list/index.md
  doc/2/api/errors/error-codes/plugin/index.md
  doc/2/framework/classes/backend-vault/properties/index.md
  doc/2/guides/advanced/configuration/index.md
  doc/2/guides/advanced/secrets-vault/index.md
  doc/2/guides/getting-started/customize-api-behavior/index.md
  docker/scripts/start-kuzzle-dev.ts
  features/Application.feature
  features/support/hooks.js
  index.ts
  lib/api/controllers/baseController.js
  lib/api/controllers/collectionController.js
  lib/api/controllers/documentController.js
  lib/api/controllers/securityController.js
  lib/api/rateLimiter.js
  lib/core/backend/backend.ts
  lib/core/backend/backendPlugin.ts
  lib/core/backend/index.ts
  lib/core/plugin/pluginsManager.js
  lib/core/security/tokenRepository.js
  lib/kerror/codes/4-plugin.json
  lib/kuzzle/event/kuzzleEventEmitter.js
  lib/kuzzle/kuzzle.js
  lib/kuzzle/vault.js
  lib/model/storage/apiKey.js
  lib/service/storage/elasticsearch.js
  lib/service/storage/esWrapper.js
  lib/util/deprecate.js
  lib/util/didYouMean.js
  lib/util/name-generator.js
  package-lock.json
  package.json
  plugins/available/functional-test-plugin/index.js
  test/api/controllers/baseController.test.js
  test/core/backend/Backend.test.js
  test/core/plugin/pluginsManager.test.js
  test/core/security/tokenRepository.test.js
  test/core/shared/sdk/embeddedSdk.test.js
  test/kuzzle/event/kuzzleEventEmitter.test.js
  test/model/storage/apiKey.test.js
  test/service/storage/elasticsearch.test.js
  test/util/didYouMean.test.js
Labels: release

#2013 Throw when cookieAuth is present and CORS headers not properly configured
  lib/api/funnel.js
  test/api/funnel/checkRights.test.js
Labels: 2.x, changelog:enhancements

#2012 Allow overriding configuration properties with JSON strings
  doc/2/guides/advanced/configuration/index.md
  lib/config/index.js
  test/config/index.test.js
Labels: 2.x, changelog:enhancements

#2011 Allow fine-tuning Redis connections using Kuzzle configuration
  .kuzzlerc.sample
  lib/config/default.config.js
  lib/service/cache/redis.js
  package.json
  test/mocks/service/redisClient.mock.js
  test/mocks/service/redisClusterClient.mock.js
  test/service/cache/redis.test.js
Labels: backend, changelog:enhancements, priority-high

#2015 Release 2.10.3
  .kuzzlerc.sample
  doc/2/guides/advanced/configuration/index.md
  lib/api/funnel.js
  lib/config/default.config.js
  lib/config/index.js
  lib/service/cache/redis.js
  package-lock.json
  package.json
  test/api/funnel/checkRights.test.js
  test/config/index.test.js
  test/mocks/service/redisClient.mock.js
  test/mocks/service/redisClusterClient.mock.js
  test/service/cache/redis.test.js
Labels: release

#2018 Doc: Improve what is kuzzle
  doc/2/guides/introduction/general-purpose-backend/index.md
  doc/2/guides/introduction/general-purpose-backend/profiles-roles.png
Labels: 2.x, changelog:exclude

#2020 Add controller name in action not found
  doc/2/api/errors/error-codes/api/index.md
  lib/api/funnel.js
  lib/api/request/index.ts
  lib/api/request/kuzzleRequest.ts
  lib/kerror/codes/2-api.json
Labels: 2.x, changelog:enhancements

#2019 Add “suggest” to the whitelisted ES search body keys
  doc/2/guides/main-concepts/querying/index.md
  lib/api/controllers/documentController.js
  lib/service/storage/elasticsearch.js
  test/service/storage/elasticsearch.test.js
Labels: 2.x, changelog:enhancements

#2024 Better error on wrong search query
  doc/2/api/errors/error-codes/api/index.md
  doc/2/api/errors/error-codes/services/index.md
  doc/2/guides/getting-started/store-and-access-data/index.md
  doc/2/guides/main-concepts/querying/index.md
  lib/api/controllers/baseController.js
  lib/core/realtime/hotelClerk.js
  lib/kerror/codes/1-services.json
  lib/kerror/codes/2-api.json
  lib/kerror/index.js
  lib/service/storage/esWrapper.js
  test/core/backend/Backend.test.js
  test/service/storage/esWrapper.test.js
Labels: 2.x, changelog:enhancements

#2023 Move specific resources arguments to the standard args object
  doc/2/api/payloads/notifications/index.md
  doc/2/framework/classes/request-input/properties/index.md
  doc/2/framework/events/generic-document/index.md
  doc/2/guides/develop-on-kuzzle/api-controllers/index.md
  doc/2/guides/main-concepts/api/index.md
  doc/2/guides/write-plugins/old-guides/controllers/index.md
  docker/scripts/start-kuzzle-dev.ts
  lib/api/controllers/baseController.js
  lib/api/controllers/documentController.js
  lib/api/controllers/memoryStorageController.js
  lib/api/documentExtractor.js
  lib/api/request/kuzzleRequest.ts
  lib/api/request/requestInput.ts
  lib/core/network/entryPoint.js
  lib/core/network/removeErrorStack.js
  lib/core/realtime/hotelClerk.js
  lib/core/realtime/notification/document.js
  lib/core/realtime/notification/user.js
  lib/core/realtime/notifier.js
  lib/model/security/role.js
  lib/util/requestAssertions.js
  plugins/available/functional-test-plugin/functionalTestPlugin.js
  test/api/controllers/baseController.test.js
  test/api/controllers/bulkController.test.js
  test/api/controllers/collectionController.test.js
  test/api/controllers/documentController.test.js
  test/api/controllers/realtimeController.test.js
  test/api/controllers/securityController/profiles.test.js
  test/api/controllers/securityController/roles.test.js
  test/api/controllers/securityController/security.test.js
  test/api/controllers/securityController/users.test.js
  test/api/documentExtractor.test.js
  test/api/funnel/processRequest.test.js
  test/api/request/requestInput.test.js
  test/api/request/requestResponse.test.js
  test/core/network/entryPoint.test.js
  test/core/network/protocols/http.test.js
  test/core/plugin/context/context.test.js
  test/core/realtime/hotelClerk/subscribe.test.js
  test/core/realtime/notifier/notifyDocumentReplace.test.js
  test/core/realtime/notifier/notifyDocumentUpdate.test.js
  test/core/realtime/notifier/notifyMethods.test.js
  test/core/realtime/notifier/publish.test.js
  test/core/security/securityLoader.test.js
  test/kuzzle/log.test.js
  test/mocks/kuzzle.mock.js
  test/model/security/role.test.js
Labels: 2.x, changelog:enhancements

#2026 Use auth token when using the JSON query endpoint
  .eslintignore
  .gitignore
  features/Api.feature
  features/AuthController.feature
  features/step_definitions/controllers-steps.js
  features/step_definitions/documents-steps.js
  lib/core/network/router.js
  package-lock.json
  package.json
Labels: 2.x, changelog:bug-fixes

#2028 Add param extraction method in KuzzleRequest
  doc/2/framework/classes/kuzzle-request/get-array/index.md
  doc/2/framework/classes/kuzzle-request/get-body-array/index.md
  doc/2/framework/classes/kuzzle-request/get-body-boolean/index.md
  doc/2/framework/classes/kuzzle-request/get-body-integer/index.md
  doc/2/framework/classes/kuzzle-request/get-body-number/index.md
  doc/2/framework/classes/kuzzle-request/get-body-object/index.md
  doc/2/framework/classes/kuzzle-request/get-body-string/index.md
  doc/2/framework/classes/kuzzle-request/get-body/index.md
  doc/2/framework/classes/kuzzle-request/get-boolean/index.md
  doc/2/framework/classes/kuzzle-request/get-collection/index.md
  doc/2/framework/classes/kuzzle-request/get-id/index.md
  doc/2/framework/classes/kuzzle-request/get-index-and-collection/index.md
  doc/2/framework/classes/kuzzle-request/get-index/index.md
  doc/2/framework/classes/kuzzle-request/get-integer/index.md
  doc/2/framework/classes/kuzzle-request/get-kuid/index.md
  doc/2/framework/classes/kuzzle-request/get-lang-param/index.md
  doc/2/framework/classes/kuzzle-request/get-number/index.md
  doc/2/framework/classes/kuzzle-request/get-object/index.md
  doc/2/framework/classes/kuzzle-request/get-refresh/index.md
  doc/2/framework/classes/kuzzle-request/get-search-params/index.md
  doc/2/framework/classes/kuzzle-request/get-string/index.md
  doc/2/framework/classes/kuzzle-request/get-user/index.md
  doc/2/guides/develop-on-kuzzle/api-controllers/index.md
  doc/2/guides/develop-on-kuzzle/embedded-sdk/index.md
  doc/2/guides/develop-on-kuzzle/event-system/index.md
  doc/2/guides/getting-started/create-new-controllers/index.md
  lib/api/controllers/adminController.js
  lib/api/controllers/authController.js
  lib/api/controllers/baseController.js
  lib/api/controllers/bulkController.js
  lib/api/controllers/collectionController.js
  lib/api/controllers/documentController.js
  lib/api/controllers/indexController.js
  lib/api/controllers/realtimeController.js
  lib/api/controllers/securityController.js
  lib/api/controllers/serverController.js
  lib/api/request/kuzzleRequest.ts
  lib/service/storage/elasticsearch.js
  test/api/controllers/baseController.test.js
  test/api/request/request.test.js
Labels: 2.x, changelog:new-features

#2029 WebSocket: enable support for per-message compression
  .github/actions/es-lint/action.yml
  .gitignore
  .kuzzlerc.sample
  doc/2/api/errors/error-codes/network/index.md
  docker-compose.yml
  features/Api.feature
  features/PluginContext.feature
  features/step_definitions/realtime-steps.js
  features/support/world.js
  lib/api/controllers/serverController.js
  lib/api/funnel.js
  lib/config/default.config.js
  lib/config/index.js
  lib/core/network/context.js
  lib/core/network/entryPoint.js
  lib/core/network/protocols/http.js
  lib/core/network/protocols/httpMessage.js
  lib/core/network/protocols/httpwsProtocol.js
  lib/core/network/protocols/internalProtocol.js
  lib/core/network/protocols/mqttProtocol.js
  lib/core/network/protocols/protocol.js
  lib/core/network/protocols/websocket.js
  lib/core/network/service/httpFormDataStream.js
  lib/kerror/codes/3-network.json
  lib/kuzzle/kuzzle.js
  package-lock.json
  package.json
  plugins/available/functional-test-plugin/functionalTestPlugin.js
  test/config/index.test.js
  test/core/network/entryPoint.test.js
  test/core/network/httpRouter/httpRouter.test.js
  test/core/network/protocols/http.test.js
  test/core/network/protocols/internal.test.js
  test/core/network/protocols/mqtt.test.js
  test/core/network/protocols/websocket.test.js
  test/core/network/router/httpRequest.test.js
  test/mocks/entrypoint.mock.js
  test/mocks/uWS.mock.js
Labels: 2.x, changelog:enhancements

#2017 Implement requestResponse.configure()
  doc/2/framework/classes/request-response/configure/index.md
  doc/2/framework/classes/request-response/properties/index.md
  lib/api/request/requestResponse.ts
  test/api/request/requestResponse.test.js
Labels: 2.x, changelog:enhancements
