Repository kuzzleio/kuzzle, pull requests merged in 2021-08, with the labels that each got.

#2118 Fix default config ttl being expressed in seconds instead of milliseconds
  .kuzzlerc.sample
  lib/config/default.config.js
Labels: changelog:bug-fixes

#2111 Enhance CORS origin verification
  .kuzzlerc.sample
  docker-compose.yml
  lib/api/controllers/authController.js
  lib/api/funnel.js
  lib/config/default.config.js
  lib/config/index.js
  test/api/funnel/execute.test.js
Labels: changelog:enhancements, 2.x

#2124 Send tokens to every user with persistent connection
  .kuzzlerc.sample
  lib/api/controllers/authController.js
  lib/api/controllers/realtimeController.js
  lib/api/funnel.js
  lib/config/default.config.js
  lib/config/index.js
  lib/core/auth/tokenManager.js
  test/core/auth/tokenManager.test.js
Labels: changelog:new-features

#2117 Use aliases instead of indices by default in ElasticSearch
  doc/2/api/errors/error-codes/services/index.md
  doc/2/guides/main-concepts/data-storage/index.md
  lib/api/controllers/securityController.js
  lib/cluster/idCardHandler.js
  lib/core/storage/clientAdapter.js
  lib/kerror/codes/1-services.json
  lib/service/storage/elasticsearch.js
  lib/util/name-generator.js
  test/core/storage/clientAdapter.test.js
  test/mocks/name-generator.mock.js
  test/mocks/service/elasticsearchClient.mock.js
  test/service/storage/elasticsearch.test.js
Labels: changelog:enhancements

#2106 Framework: BackendImport
  .gitignore
  doc/2/api/errors/error-codes/plugin/index.md
  doc/2/framework/classes/backend-import/index.md
  doc/2/framework/classes/backend-import/mappings/index.md
  doc/2/framework/classes/backend-import/profiles/index.md
  doc/2/framework/classes/backend-import/properties/index.md
  doc/2/framework/classes/backend-import/roles/index.md
  doc/2/framework/classes/backend-import/userMappings/index.md
  doc/2/framework/classes/backend-import/users/index.md
  doc/2/framework/classes/backend/properties/index.md
  docker/scripts/start-kuzzle-dev.ts
  features/#BackendImport.feature
  features/fixtures/imports.json
  features/fixtures/permissions.js
  features/step_definitions/controllers-steps.js
  features/support/hooks.js
  features/support/world.js
  lib/api/controllers/adminController.js
  lib/core/backend/backend.ts
  lib/core/backend/backendImport.ts
  lib/core/backend/index.ts
  lib/core/security/securityLoader.js
  lib/core/security/userRepository.js
  lib/core/storage/clientAdapter.js
  lib/kerror/codes/4-plugin.json
  lib/kerror/index.js
  lib/kuzzle/kuzzle.js
  test/core/backend/Backend.test.js
  test/core/backend/BackendImport.test.js
  test/core/storage/clientAdapter.test.js
  test/kuzzle/kuzzle.test.js
Labels: changelog:new-features
