Repository kuzzleio/kuzzle, pull requests merged in 2021-11, with the labels that each got.

#2179 Convert HotelClerk to Typescript
  .eslintignore
  .gitignore
  docker/scripts/start-kuzzle-dev.ts
  lib/cluster/state.ts
  lib/core/auth/tokenManager.ts
  lib/core/network/router.js
  lib/core/realtime/channel.ts
  lib/core/realtime/connectionRooms.ts
  lib/core/realtime/hotelClerk.ts
  lib/core/realtime/index.js
  lib/core/realtime/notifier.js
  lib/core/realtime/room.ts
  lib/core/realtime/subscription.ts
  lib/types/KuzzleDocument.ts
  lib/types/index.ts
  lib/types/realtime/RealtimeScope.ts
  lib/types/realtime/RealtimeUsers.ts
  lib/types/realtime/RoomList.ts
  test/core/auth/tokenManager.test.js
  test/core/network/router/router.test.js
  test/core/realtime/hotelClerk/disconnect.test.js
  test/core/realtime/hotelClerk/join.test.js
  test/core/realtime/hotelClerk/list.test.js
  test/core/realtime/hotelClerk/listCollections.test.js
  test/core/realtime/hotelClerk/subscribe.test.js
  test/core/realtime/hotelClerk/unsubscribe.test.js
  test/core/realtime/notifier/notifyMethods.test.js
Labels: changelog:exclude

#2173 Fix realtime connection cleaning after unexpected deconnection
  docker/scripts/run-dev.sh
  lib/api/funnel.js
  lib/core/auth/tokenManager.ts
  lib/core/network/router.js
  lib/core/realtime/channel.ts
  lib/core/realtime/hotelClerk.ts
  lib/types/realtime/RealtimeUsers.ts
  test/api/funnel/checkRights.test.js
  test/core/auth/tokenManager.test.js
  test/core/network/router/router.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:bug-fixes

#2180 Allows to disable the SDK version safety check
  .kuzzlerc.sample
  doc/2/api/errors/error-codes/api/index.md
  lib/api/funnel.js
  lib/config/default.config.js
  lib/kerror/codes/2-api.json
  test/api/funnel/processRequest.test.js
Labels: changelog:enhancements

#2181 Properly disconnect connections on shutdown
  docker-compose.yml
  lib/core/realtime/hotelClerk.ts
  lib/kuzzle/kuzzle.ts
  test/core/realtime/hotelClerk/disconnect.test.js
  test/core/realtime/hotelClerk/hotelClerk.test.js
  test/kuzzle/kuzzle.test.js
Labels: changelog:bug-fixes

#2174 Allows to deactivate stats module
  .kuzzlerc.sample
  doc/2/api/errors/error-codes/services/index.md
  lib/config/default.config.js
  lib/core/statistics/statistics.js
  lib/kerror/codes/1-services.json
  test/core/statistics/statistics.test.js
Labels: changelog:enhancements, 2.x

#2182 Release 2.14.11
  .eslintignore
  .github/actions/deploy-doc/action.yml
  .github/workflows/pull_request.workflow.yml
  .github/workflows/push_dev.workflow.yml
  .github/workflows/push_master.workflow.yml
  .gitignore
  .kuzzlerc.sample
  doc/2/api/controllers/security/get-user-strategies/index.md
  doc/2/api/errors/error-codes/api/index.md
  doc/2/api/errors/error-codes/services/index.md
  doc/2/framework/events/realtime/index.md
  doc/2/guides/main-concepts/authentication/index.md
  docker-compose.yml
  docker/nginx/kuzzle.conf
  docker/scripts/run-dev.sh
  docker/scripts/start-kuzzle-dev.ts
  lib/api/funnel.js
  lib/cluster/node.js
  lib/cluster/state.ts
  lib/config/default.config.js
  lib/config/index.js
  lib/core/auth/tokenManager.ts
  lib/core/network/router.js
  lib/core/realtime/channel.ts
  lib/core/realtime/connectionRooms.ts
  lib/core/realtime/hotelClerk.ts
  lib/core/realtime/index.js
  lib/core/realtime/notifier.js
  lib/core/realtime/room.ts
  lib/core/realtime/subscription.ts
  lib/core/statistics/statistics.js
  lib/kerror/codes/1-services.json
  lib/kerror/codes/2-api.json
  lib/kuzzle/kuzzle.ts
  lib/types/KuzzleDocument.ts
  lib/types/Plugin.ts
  lib/types/index.ts
  lib/types/realtime/RealtimeScope.ts
  lib/types/realtime/RealtimeUsers.ts
  lib/types/realtime/RoomList.ts
  package-lock.json
  package.json
  test/api/funnel/checkRights.test.js
  test/api/funnel/processRequest.test.js
  test/core/auth/tokenManager.test.js
  test/core/network/router/router.test.js
  test/core/realtime/hotelClerk/disconnect.test.js
  test/core/realtime/hotelClerk/hotelClerk.test.js
  test/core/realtime/hotelClerk/join.test.js
  test/core/realtime/hotelClerk/list.test.js
  test/core/realtime/hotelClerk/listCollections.test.js
  test/core/realtime/hotelClerk/subscribe.test.js
  test/core/realtime/hotelClerk/unsubscribe.test.js
  test/core/realtime/notifier/notifyMethods.test.js
  test/core/statistics/statistics.test.js
  test/kuzzle/kuzzle.test.js
  test/mocks/kuzzle.mock.js
Labels: release

#2184 Fix realtime:shutdown event race condition
  lib/core/realtime/hotelClerk.ts
  lib/kuzzle/kuzzle.ts
  package-lock.json
  package.json
  test/core/realtime/hotelClerk/hotelClerk.test.js
  test/kuzzle/kuzzle.test.js
Labels: changelog:bug-fixes

#2185 Freeze Elasticsearch client version
  package-lock.json
  package.json
Labels: changelog:bug-fixes

#2183 Increase ID card expiration delay
  lib/cluster/idCardHandler.js
  lib/cluster/workers/IDCardRenewer.js
  test/cluster/idCardHandler.test.js
  test/cluster/workers/IDCardRenewer.test.js
Labels: changelog:enhancements

#2190 Store ID Card's keys in a Redis set to speed up handshake
  docker/docker-compose-swarm.yml
  lib/cluster/idCardHandler.js
  lib/cluster/node.js
  lib/cluster/subscriber.js
  lib/core/cache/cacheEngine.js
  package-lock.json
  package.json
  test/cluster/idCardHandler.test.js
  test/cluster/subscriber.test.js
Labels: changelog:enhancements

#2176 Add type to http configuration
  lib/types/config/HttpConfiguration.ts
  lib/types/config/KuzzleConfiguration.ts
  lib/types/index.ts
Labels: changelog:exclude

#2205 Ensure ID Card is refreshed while worker thread starts
  .eslintignore
  .gitignore
  lib/cluster/idCardHandler.ts
  lib/cluster/workers/IDCardRenewer.js
  test/cluster/idCardHandler.test.js
  test/cluster/workers/IDCardRenewer.test.js
Labels: changelog:bug-fixes

#2204 Add an action to manually refresh the index cache
  lib/api/controllers/adminController.js
  lib/cluster/node.js
  lib/cluster/protobuf/sync.proto
  lib/cluster/subscriber.js
  lib/config/httpRoutes.js
  lib/core/storage/clientAdapter.js
  lib/core/storage/indexCache.ts
  test/api/controllers/adminController.test.js
  test/cluster/node.test.js
  test/cluster/subscriber.test.js
  test/core/storage/indexCache.test.js
Labels: changelog:new-features, 2.x

#2211 Send document body in notification when exiting the scope
  doc/2/api/payloads/notifications/index.md
  doc/2/guides/main-concepts/api/index.md
  features-legacy/kuzzle.feature
  lib/api/controllers/documentController.js
  lib/core/realtime/notifier.js
  test/core/realtime/notifier/notifyDocumentDelete.test.js
  test/core/realtime/notifier/notifyDocumentReplace.test.js
  test/core/realtime/notifier/notifyDocumentUpdate.test.js
Labels: changelog:enhancements

#2210 Replace segfault handler dependency
  .github/actions/cache-node-modules/action.yml
  .github/actions/install-packages/action.yml
  .github/workflows/pull_request.workflow.yml
  .github/workflows/push_dev.workflow.yml
  .github/workflows/push_master.workflow.yml
  docker/images/kuzzle.alpine/Dockerfile
  docker/images/kuzzle.scratch/Dockerfile
  docker/images/kuzzle/Dockerfile
  docker/images/plugin-dev/Dockerfile
  lib/kuzzle/kuzzle.ts
  package-lock.json
  package.json
Labels: changelog:enhancements

#2177 Add type to limits configuration
  lib/types/config/KuzzleConfiguration.ts
  lib/types/config/LimitsConfiguration.ts
  lib/types/index.ts
Labels: changelog:exclude

#2178 Add type to plugin configuration
  lib/kuzzle/kuzzle.ts
  lib/types/config/KuzzleConfiguration.ts
  lib/types/config/PluginsConfiguration.ts
  lib/types/index.ts
Labels: changelog:exclude

#2187 Add type to security configuration
  lib/types/config/KuzzleConfiguration.ts
  lib/types/config/SecurityConfiguration.ts
  lib/types/index.ts
Labels: changelog:exclude

#2188 Add type for services config
  lib/types/config/InternalCacheConfiguration.ts
  lib/types/config/KuzzleConfiguration.ts
  lib/types/config/MemoryStorageConfiguration.ts
  lib/types/config/ServicesConfiguration.ts
  lib/types/config/elasticsearch/StorageService.ts
  lib/types/index.ts
Labels: changelog:exclude

#2189 Add type for server config
  lib/types/config/KuzzleConfiguration.ts
  lib/types/config/ServerConfiguration.ts
  lib/types/index.ts
Labels: changelog:exclude

#2214 Allows stored-scripts in queries
  lib/service/storage/elasticsearch.js
  package-lock.json
  package.json
  test/service/storage/elasticsearch.test.js
Labels: changelog:enhancements

#2217 Release 2.15.1
  doc/2/api/controllers/admin/dump/index.md
  doc/2/api/controllers/admin/load-fixtures/index.md
  doc/2/api/controllers/admin/load-mappings/index.md
  doc/2/api/controllers/admin/load-securities/index.md
  doc/2/api/controllers/admin/reset-cache/index.md
  doc/2/api/controllers/admin/reset-database/index.md
  doc/2/api/controllers/admin/reset-security/index.md
  doc/2/api/controllers/admin/shutdown/index.md
  doc/2/api/controllers/auth/refresh-token/index.md
  doc/2/api/controllers/bulk/m-write/index.md
  doc/2/api/controllers/bulk/write/index.md
  doc/2/api/controllers/collection/create/index.md
  doc/2/api/controllers/collection/get-mapping/index.md
  doc/2/api/controllers/collection/update-mapping/index.md
  doc/2/api/controllers/realtime/join/index.md
  doc/2/api/controllers/realtime/validate/index.md
  doc/2/framework/events/core/index.md
  doc/2/framework/events/generic-document/index.md
  doc/2/framework/events/http/index.md
  doc/2/guides/advanced/secrets-vault/index.md
  doc/2/guides/write-protocols/context/errors/index.md
  doc/2/guides/write-protocols/context/request/index.md
  lib/service/storage/elasticsearch.js
  package-lock.json
  package.json
  test/service/storage/elasticsearch.test.js
Labels: release

#2195 Create action for document controller
  lib/api/httpRoutes.js
  lib/api/openApiGenerator.ts
  lib/api/openapi/documents/create.yaml
  lib/api/openapi/documents/document.ts
  test/api/controllers/serverController.test.js
Labels: changelog:exclude

#2196 CreateOrReplace action for document controller
  lib/api/httpRoutes.js
  lib/api/openApiGenerator.ts
  lib/api/openapi/documents/createOrReplace.yaml
  lib/api/openapi/documents/document.ts
Labels: changelog:exclude

#2199 Get action for document controller
  lib/api/httpRoutes.js
  lib/api/openApiGenerator.ts
  lib/api/openapi/documents/document.ts
  lib/api/openapi/documents/get.yaml
Labels: changelog:exclude

#2200 Replace action for document controller
  lib/api/httpRoutes.js
  lib/api/openApiGenerator.ts
  lib/api/openapi/documents/document.ts
  lib/api/openapi/documents/replace.yaml
Labels: changelog:exclude

#2201 Update action for document controller
  lib/api/httpRoutes.js
  lib/api/openApiGenerator.ts
  lib/api/openapi/documents/document.ts
  lib/api/openapi/documents/update.yaml
Labels: changelog:exclude

#2202 Exists action for document controller
  lib/api/httpRoutes.js
  lib/api/openApiGenerator.ts
  lib/api/openapi/documents/document.ts
  lib/api/openapi/documents/exists.yaml
Labels: changelog:exclude

#2203 Scroll action for document controller
  lib/api/httpRoutes.js
  lib/api/openApiGenerator.ts
  lib/api/openapi/documents/document.ts
  lib/api/openapi/documents/scroll.yaml
  lib/api/openapi/payloads.yaml
Labels: changelog:exclude

#2197 Delete action for docuement controller
  lib/api/httpRoutes.js
  lib/api/openApiGenerator.ts
  lib/api/openapi/documents/delete.yaml
  lib/api/openapi/documents/document.ts
Labels: changelog:exclude

#2198 DeleteByQuery action for document controller
  lib/api/httpRoutes.js
  lib/api/openApiGenerator.ts
  lib/api/openapi/documents/deleteByQuery.yaml
  lib/api/openapi/documents/document.ts
Labels: changelog:exclude
