Repository kuzzleio/kuzzle, pull requests merged in 2022-11, with the labels that each got.

#2393 2.19.6 - Fix double export of ResponsePayload
  .github/workflows/workflow.yaml
  doc/2/framework/types/request-payload/index.md
  doc/2/framework/types/response-payload/index.md
  docker/scripts/start-kuzzle-dev.ts
  lib/core/shared/sdk/embeddedSdk.ts
  lib/types/RequestPayload.ts
  lib/types/ResponsePayload.ts
  lib/types/index.ts
  package-lock.json
  package.json
Labels: changelog:bug-fixes

#2394 2.19.7 - Add default type to EmbeddedSDK.query
  lib/core/shared/sdk/embeddedSdk.ts
  lib/kerror/index.ts
  lib/service/storage/esWrapper.js
  package-lock.json
  package.json
  test/service/storage/esWrapper.test.js
Labels: changelog:bug-fixes

#2391 Allow to force number of replicas and shards per index from Kuzzle configuration
  .eslintignore
  .gitignore
  .kuzzlerc.sample
  lib/config/default.config.ts
  lib/service/storage/elasticsearch.js
  lib/types/config/storageEngine/StorageEngineElasticsearchConfiguration.ts
  package-lock.json
  test/service/storage/elasticsearch.test.js
Labels: changelog:new-features

#2396 Allows foreign keywords in Koncorde DSL
  doc/2/guides/main-concepts/querying/index.md
  features/DocumentController.feature
  lib/api/controllers/baseController.js
  lib/service/storage/queryTranslator.js
  test/api/controllers/baseController.test.js
Labels: changelog:enhancements

#2397 Release 2.19.8
  .eslintignore
  .gitignore
  .kuzzlerc.sample
  doc/2/guides/main-concepts/querying/index.md
  features/DocumentController.feature
  lib/api/controllers/baseController.js
  lib/config/default.config.ts
  lib/service/storage/elasticsearch.js
  lib/service/storage/queryTranslator.js
  lib/types/config/storageEngine/StorageEngineElasticsearchConfiguration.ts
  package-lock.json
  package.json
  test/api/controllers/baseController.test.js
  test/service/storage/elasticsearch.test.js
Labels: release

#2398 Fix ZeroMQ version to avoid npm install errors
  package-lock.json
  package.json
Labels: changelog:exclude

#2399 Fix set-cookie header not respecting the RFC when having multiple of them
  lib/core/network/protocols/httpwsProtocol.js
  test/core/network/protocols/http.test.js
Labels: changelog:bug-fixes

#2402 Forward errors to HTTP stream consumers
  lib/util/dump-collection.ts
Labels: changelog:bug-fixes

#2403 Release 2.19.10
  .github/workflows/workflow.yaml
  .gitignore
  doc/2/api/controllers/document/count/index.md
  features/DocumentController.feature
  lib/api/controllers/documentController.js
  lib/core/network/protocols/httpwsProtocol.js
  lib/service/storage/elasticsearch.js
  lib/util/dump-collection.ts
  package-lock.json
  package.json
  test/core/network/protocols/http.test.js
  test/service/storage/elasticsearch.test.js
Labels: release
