Repository kuzzleio/kuzzle, pull requests merged in 2022-12, with the labels that each got.

#2409 Ensure alias is being deleted when removing a collection
  .ci/scripts/run-monkey-tests.sh
  .ci/scripts/run-test-cluster.sh
  .github/workflows/workflow-deployments.yaml
  .github/workflows/workflow.yaml
  lib/service/storage/elasticsearch.js
  package-lock.json
  test/service/storage/elasticsearch.test.js
Labels: changelog:bug-fixes

#2411 Release 2.19.11
  .ci/scripts/run-monkey-tests.sh
  .ci/scripts/run-test-cluster.sh
  .github/workflows/workflow-deployments.yaml
  .github/workflows/workflow.yaml
  lib/core/network/protocols/httpwsProtocol.js
  lib/service/storage/elasticsearch.js
  lib/types/ClientConnection.ts
  lib/types/HttpMessage.ts
  lib/types/events/EventProtocol.ts
  lib/types/index.ts
  package-lock.json
  package.json
  test/core/network/protocols/http.test.js
  test/core/network/protocols/websocket.test.js
  test/mocks/uWS.mock.js
  test/service/storage/elasticsearch.test.js
Labels: release, changelog:exclude

#2412 Fix ProfileDefinition type
  lib/types/ProfileDefinition.ts
Labels: changelog:bug-fixes

#2414 Release 2.19.12
  lib/types/ProfileDefinition.ts
  package-lock.json
  package.json
Labels: release

#2415 Add Inflector.snakeCase method
  .eslintignore
  .gitignore
  doc/2/framework/classes/inflector/camel-case/index.md
  doc/2/framework/classes/inflector/pascal-case/index.md
  doc/2/framework/classes/inflector/snake-case/index.md
  index.ts
  lib/api/openapi/openApiGenerator.ts
  lib/core/backend/backendController.ts
  lib/core/backend/backendPlugin.ts
  lib/core/plugin/pluginsManager.js
  lib/util/Inflector.ts
Labels: changelog:enhancements

#2417 Fixing : title : duplicated creating an error when seoUpgrade
  doc/2/framework/error-classes/unauthorized-error/index.md
  doc/2/guides/advanced/secrets-vault/index.md
  doc/2/guides/write-plugins/old-guides/index.md
Labels: changelog:bug-fixes
