Repository kuzzleio/kuzzle, pull requests merged in 2022-02, with the labels that each got.

#2262 Release 2.16.10: fix API keys loading
  lib/core/security/tokenRepository.js
  package-lock.json
  package.json
  test/core/security/tokenRepository.test.js
Labels: changelog:bug-fixes, 2.x

#2242 Add server:capabilities api action
  doc/2/api/controllers/server/capabilities/index.md
  features/ServerController.feature
  lib/api/controllers/serverController.js
  lib/api/httpRoutes.js
  package.json
Labels: changelog:enhancements, 2.x

#2268 Add header to force close connection after HTTP Requests
  lib/core/network/protocols/httpwsProtocol.js
Labels: changelog:bug-fixes

#2267 Support patch and options HTTP verbs
  .eslintrc.json
  features-legacy/step_definitions/role.js
  features-legacy/step_definitions/subscription.js
  features-legacy/support/api/apiBase.js
  features-legacy/support/api/http.js
  features-legacy/support/world.js
  lib/api/controllers/authController.js
  lib/api/controllers/memoryStorageController.js
  lib/api/httpRoutes.js
  lib/api/openApiGenerator.ts
  lib/config/default.config.ts
  lib/core/network/router.js
  lib/core/shared/store.js
  lib/model/storage/baseModel.js
  lib/service/storage/elasticsearch.js
  lib/types/ControllerDefinition.ts
  test/api/controllers/securityController/credentials.test.js
  test/core/backend/BackendImport.test.js
  test/core/network/httpRouter/httpRouter.test.js
  test/core/plugin/pluginsManager.test.js
  test/core/shared/repository.test.js
  test/core/validation/baseType.test.js
  test/core/validation/types/string.test.js
  test/core/validation/util.test.js
  test/mocks/kuzzle.mock.js
  test/service/storage/elasticsearch.test.js
Labels: changelog:enhancements

#2255 Allows to disable Cluster
  doc/2/framework/classes/backend-config/merge/index.md
  doc/2/framework/classes/backend-config/properties/index.md
  doc/2/framework/classes/backend-config/set/index.md
  doc/2/guides/advanced/configuration/index.md
  lib/api/openapi/OpenApiManager.ts
  lib/api/openapi/openApiGenerator.ts
  lib/config/default.config.ts
  lib/core/backend/backendConfig.ts
  lib/core/plugin/pluginsManager.js
  lib/kuzzle/kuzzle.ts
  lib/types/config/KuzzleConfiguration.ts
  lib/types/config/ServicesConfiguration.ts
  lib/types/config/storageEngine/StorageEngineElasticsearchConfiguration.ts
  lib/types/index.ts
  test/core/plugin/pluginsManager.test.js
  test/kuzzle/kuzzle.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:new-features

#2263 Support HTTP streams
  .eslintc-ts.json
  .eslintrc.json
  doc/2/api/controllers/document/export/index.md
  doc/2/api/errors/error-codes/api/index.md
  doc/2/api/errors/error-codes/network/index.md
  doc/2/framework/classes/http-stream/constructor/index.md
  doc/2/framework/classes/http-stream/index.md
  doc/2/framework/classes/http-stream/properties/index.md
  doc/2/guides/develop-on-kuzzle/api-controllers/index.md
  features/DocumentController.feature
  features/step_definitions/controllers-steps.js
  features/step_definitions/documents-steps.js
  lib/api/controllers/documentController.js
  lib/api/httpRoutes.js
  lib/api/request/kuzzleRequest.ts
  lib/core/network/protocols/httpwsProtocol.js
  lib/kerror/codes/2-api.json
  lib/kerror/codes/3-network.json
  lib/service/storage/elasticsearch.js
  lib/types/HttpStream.ts
  lib/types/index.ts
  lib/util/bufferedPassThrough.ts
  lib/util/dump-collection.ts
  package.json
  test/core/network/protocols/http.test.js
  test/core/security/tokenRepository.test.js
  test/mocks/uWS.mock.js
Labels: changelog:new-features

#2276 Fix double Content-Length header
  lib/core/network/protocols/httpwsProtocol.js
  test/api/controllers/documentController.test.js
  test/core/network/protocols/http.test.js
Labels: changelog:bug-fixes

#2278 Add missing requestId when responding with an error in websocket message handling
  lib/core/network/protocols/httpwsProtocol.js
Labels: changelog:bug-fixes
