Repository kuzzleio/kuzzle, pull requests merged in 2022-04, with the labels that each got.

#2302 Allows refresh param to admin:loadFixtures
  lib/api/controllers/adminController.js
  lib/core/storage/clientAdapter.js
  lib/service/storage/elasticsearch.js
  test/api/controllers/adminController.test.js
Labels: changelog:enhancements

#2304 Release 2.17.6
  doc/2/api/controllers/admin/load-fixtures/index.md
  lib/api/controllers/adminController.js
  lib/core/storage/clientAdapter.js
  lib/service/storage/elasticsearch.js
  package-lock.json
  package.json
  test/api/controllers/adminController.test.js
Labels: release

#2303 Added strict and test
  doc/2/api/controllers/document/update-by-query/index.md
  lib/api/controllers/documentController.js
  test/api/controllers/documentController.test.js
Labels: changelog:enhancements

#2309 Fix error when using access log with non clonable objects
  lib/core/network/accessLogger.js
  package-lock.json
  package.json
Labels: changelog:bug-fixes

#2265 Fix mExists action when using the HTTP protocol
  .ci/test-cluster.yml
  features/DocumentController.feature
  lib/api/httpRoutes.js
Labels: changelog:bug-fixes

#2307 Added strict argument for document:updateByQuery and associated test
  doc/2/api/controllers/document/update-by-query/index.md
  lib/api/controllers/documentController.js
  test/api/controllers/documentController.test.js
Labels: changelog:enhancements

#2244 Add _source argument for mCreateOrReplce API action
  doc/2/api/controllers/document/m-create-or-replace/index.md
  features/DocumentController.feature
  lib/api/controllers/documentController.js
  lib/api/httpRoutes.js
  lib/api/openapi/OpenApiManager.ts
  lib/api/openapi/components/document/index.ts
  lib/api/openapi/components/document/mCreateOrReplace.yaml
  lib/service/storage/elasticsearch.js
  test/api/controllers/documentController.test.js
  test/service/storage/elasticsearch.test.js
Labels: changelog:enhancements, 2.x

#2301 Enfore our Typescript standard with tslint
  .eslintc-ts.json
  lib/api/request/kuzzleRequest.ts
  lib/api/request/requestContext.ts
  lib/core/backend/backend.ts
  lib/core/backend/backendHook.ts
  lib/core/backend/backendImport.ts
  lib/core/backend/backendPlugin.ts
  lib/core/backend/backendVault.ts
  lib/core/plugin/pluginContext.ts
  lib/core/realtime/channel.ts
  lib/core/realtime/hotelClerk.ts
  lib/core/security/profileRepository.ts
  lib/core/shared/KoncordeWrapper.ts
  lib/core/shared/sdk/embeddedSdk.ts
  lib/kuzzle/kuzzle.ts
  lib/types/ControllerDefinition.ts
  lib/types/ControllerRights.ts
  lib/types/Kuzzle.ts
  lib/types/OpenApiDefinition.ts
  lib/types/PasswordPolicy.ts
  lib/types/Plugin.ts
  lib/types/PolicyRestrictions.ts
  lib/types/RoleDefinition.ts
  lib/types/StrategyDefinition.ts
  lib/types/config/DumpConfiguration.ts
  lib/types/config/HttpConfiguration.ts
  lib/types/config/KuzzleConfiguration.ts
  lib/types/config/LimitsConfiguration.ts
  lib/types/config/PluginsConfiguration.ts
  lib/types/config/SecurityConfiguration.ts
  lib/types/config/ServerConfiguration.ts
  lib/types/config/ServicesConfiguration.ts
  lib/types/config/internalCache/InternalCacheRedisConfiguration.ts
  lib/types/config/publicCache/PublicCacheRedisConfiguration.ts
  lib/types/config/storageEngine/StorageEngineElasticsearchConfiguration.ts
  lib/types/errors/ErrorDomains.ts
  lib/types/realtime/RoomList.ts
  lib/util/dump-collection.ts
  lib/util/koncordeCompat.ts
  lib/util/mutex.ts
Labels: changelog:exclude

#2317 Fix stacktrace enhancement for errors in pipes
  .eslintignore
  .gitignore
  lib/core/network/entryPoint.js
  lib/core/network/protocols/httpwsProtocol.js
  lib/core/network/protocols/mqttProtocol.js
  lib/core/network/removeErrorStack.js
  lib/core/network/router.js
  lib/core/shared/sdk/embeddedSdk.ts
  lib/core/shared/sdk/funnelProtocol.ts
  lib/kerror/index.ts
  lib/types/KuzzleDocument.ts
  lib/util/stackTrace.js
  package.json
  test/core/shared/sdk/funnelProtocol.test.js
  test/util/stacktrace.test.js
Labels: changelog:bug-fixes, 2.x

#2310 Fix cluster desync
  lib/cluster/node.js
  lib/cluster/subscriber.js
  lib/core/realtime/hotelClerk.ts
  lib/kuzzle/event/kuzzleEventEmitter.js
  test/cluster/node.test.js
  test/cluster/subscriber.test.js
  test/core/realtime/hotelClerk/join.test.js
  test/core/realtime/hotelClerk/subscribe.test.js
  test/core/realtime/hotelClerk/unsubscribe.test.js
  test/kuzzle/event/kuzzleEventEmitter.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:bug-fixes

#2326 Allow multiple aliases on same index as long as they are not prefixed with @
  doc/2/api/errors/error-codes/services/index.md
  lib/kerror/codes/1-services.json
  lib/service/storage/elasticsearch.js
  test/service/storage/elasticsearch.test.js
Labels: changelog:enhancements

#2327 [Export CSV] Fix wrong exported fields
  lib/util/dump-collection.ts
  test/util/dump-collection.test.js
Labels: changelog:bug-fixes

#2305 Fix typo in openapi for the document:get API action
  lib/api/openapi/components/document/get.yaml
Labels: changelog:exclude

#2328 Fix race condition when creating index hidden indice
  doc/2/guides/advanced/configuration/index.md
  lib/service/storage/elasticsearch.js
  test/service/storage/elasticsearch.test.js
Labels: changelog:bug-fixes

#2331 Support for multiple alias pointing to one index
  doc/2/api/controllers/document/search/index.md
  features/DocumentController.feature
  features/fixtures/mappings.js
  features/step_definitions/documents-steps.js
  lib/model/security/user.ts
  lib/service/storage/elasticsearch.js
  test/model/security/user.test.js
  test/service/storage/elasticsearch.test.js
Labels: priority-high, changelog:enhancements

#2335 Fix index:mDelete usage with EmbeddedSDK
  lib/api/controllers/indexController.js
  test/api/controllers/indexController.test.js
Labels: changelog:bug-fixes

#2321 Date extractor in Kuzzle request
  lib/api/request/kuzzleRequest.ts
  test/api/request/request.test.js
Labels: changelog:new-features

#2330 better writing of scenario names
  features/BulkController.feature
  features/CollectionController.feature
  features/DocumentController.feature
  features/IndexController.feature
  features/PluginEvents.feature
  features/step_definitions/documents-steps.js
Labels: changelog:exclude

#2336 Fix unauthorized error codes not printing %s:%s instead of controller action
  lib/api/controllers/authController.js
Labels: changelog:exclude

#2334 Early check of controller definition for better errors
  lib/core/backend/backendController.ts
  lib/core/plugin/plugin.js
  test/core/backend/BackendController.test.js
Labels: changelog:enhancements

#2340 Add headers in response content
  docker/scripts/start-kuzzle-dev.ts
  features/HTTP.feature
  features/Websocket.feature
  features/step_definitions/controllers-steps.js
  features/step_definitions/websocket-steps.js
  lib/api/controllers/documentController.js
  lib/api/request/kuzzleRequest.ts
  lib/api/request/requestResponse.ts
  lib/core/network/protocols/httpwsProtocol.js
  test/api/request/requestResponse.test.js
  test/core/network/protocols/websocket.test.js
Labels: changelog:enhancements

#2342 Standardize arrays and objects in querystring
  doc/2/framework/classes/kuzzle-request/get-array/index.md
  doc/2/framework/classes/kuzzle-request/get-object/index.md
  lib/api/controllers/securityController.js
  lib/api/controllers/serverController.js
  lib/api/documentExtractor.js
  lib/api/request/kuzzleRequest.ts
  test/api/request/request.test.js
Labels: changelog:enhancements

#2345 Release 2.18.1
  doc/2/framework/classes/kuzzle-request/get-array/index.md
  doc/2/framework/classes/kuzzle-request/get-object/index.md
  docker/scripts/start-kuzzle-dev.ts
  features/HTTP.feature
  features/Websocket.feature
  features/step_definitions/controllers-steps.js
  features/step_definitions/websocket-steps.js
  lib/api/controllers/authController.js
  lib/api/controllers/documentController.js
  lib/api/controllers/securityController.js
  lib/api/controllers/serverController.js
  lib/api/documentExtractor.js
  lib/api/request/kuzzleRequest.ts
  lib/api/request/requestResponse.ts
  lib/core/backend/backendController.ts
  lib/core/network/protocols/httpwsProtocol.js
  lib/core/plugin/plugin.js
  package-lock.json
  package.json
  test/api/request/request.test.js
  test/api/request/requestResponse.test.js
  test/core/backend/BackendController.test.js
  test/core/network/protocols/websocket.test.js
Labels: release
