Repository kuzzleio/kuzzle, pull requests merged in 2022-05, with the labels that each got.

#2349 Ensure usage of string for index and collection for `document:search` action
  .gitignore
  lib/api/controllers/documentController.js
  lib/api/request/kuzzleRequest.ts
  test/api/controllers/documentController.test.js
Labels: changelog:enhancements

#2341 Remove import mappings lock on `admin:resetDatabase` action
  .gitignore
  lib/api/controllers/adminController.js
  lib/kuzzle/kuzzle.ts
  lib/model/storage/apiKey.js
  lib/util/crypto.ts
  test/api/controllers/adminController.test.js
  test/kuzzle/kuzzle.test.js
Labels: changelog:bug-fixes

#2354 Split jobs doc
  .github/workflows/workflow-deployments.yaml
  .github/workflows/workflow.yaml
Labels: changelog:exclude

#2314 Preserve settings when truncate collection
  lib/service/storage/elasticsearch.js
  test/service/storage/elasticsearch.test.js
Labels: changelog:bug-fixes

#2323 Generic events are not triggered on some actions
  features/PluginEvents.feature
  lib/api/controllers/documentController.js
  lib/api/documentExtractor.js
  lib/api/funnel.js
  lib/config/documentEventAliases.ts
Labels: changelog:bug-fixes

#2312 Deprecate auth controller in the embeded sdk
  doc/2/api/errors/error-codes/api/index.md
  doc/2/guides/develop-on-kuzzle/embedded-sdk/index.md
  lib/core/shared/sdk/embeddedSdk.ts
  lib/kerror/codes/2-api.json
  test/core/shared/sdk/embeddedSdk.test.js
Labels: changelog:bug-fixes

#2353 Add retry function and cluster steps for cucumber framework
  doc/2/api/payloads/response/index.md
  features/step_definitions/cluster-steps.js
  features/step_definitions/realtime-steps.js
  features/support/hooks.js
  features/support/world.js
Labels: changelog:exclude
