Repository kuzzleio/kuzzle, pull requests merged in 2022-03, with the labels that each got.

#2280 Fix API Key id not generated when missing
  features/AuthController.feature
  features/SecurityController.feature
  lib/api/controllers/authController.js
  lib/api/controllers/securityController.js
  lib/api/request/kuzzleRequest.ts
  package-lock.json
Labels: changelog:bug-fixes

#2283 Fix missing origin header after ws upgrade
  lib/api/funnel.js
  lib/core/network/protocols/httpwsProtocol.js
  test/core/network/protocols/websocket.test.js
Labels: changelog:bug-fixes

#2287 Allows to specify custom error domain
  doc/2/framework/classes/backend-errors/get-from/index.md
  doc/2/framework/classes/backend-errors/get/index.md
  doc/2/framework/classes/backend-errors/register/index.md
  doc/2/guides/develop-on-kuzzle/customize-api-errors/index.md
  docker/scripts/start-kuzzle-dev.ts
  lib/core/backend/backendErrors.ts
  package-lock.json
  package.json
  test/core/backend/BackendErrors.test.js
Labels: changelog:enhancements

#2288 Expose errors placeholders
  README.md
  doc/2/api/payloads/error/index.md
  lib/kerror/errors/kuzzleError.ts
  lib/kerror/index.ts
  test/kerror/kerror.test.js
Labels: changelog:enhancements

#2295 Release 2.17.5
  README.md
  doc/2/api/payloads/error/index.md
  lib/kerror/errors/kuzzleError.ts
  lib/kerror/index.ts
  package-lock.json
  package.json
  test/kerror/kerror.test.js
Labels: release
