Repository kuzzleio/kuzzle, pull requests merged in 2022-09, with the labels that each got.

#2379 Fix second argument for hook on generic event
  docker/scripts/start-kuzzle-dev.ts
  features/PluginEvents.feature
  lib/kuzzle/event/pipeRunner.js
Labels: changelog:bug-fixes

#2383 Strong typing for pipe and hooks
  doc/2/framework/abstract-classes/plugin/properties/index.md
  doc/2/framework/classes/backend-cluster/off/index.md
  doc/2/framework/classes/backend-cluster/on/index.md
  doc/2/framework/classes/backend-cluster/once/index.md
  doc/2/framework/classes/backend-hook/register/index.md
  doc/2/framework/classes/backend-pipe/register/index.md
  doc/2/framework/types/event-handler/index.md
  docker/scripts/start-kuzzle-dev.ts
  lib/core/backend/backend.ts
  lib/core/backend/backendCluster.ts
  lib/core/backend/backendHook.ts
  lib/core/backend/backendPipe.ts
  lib/types/EventHandler.ts
  lib/types/Plugin.ts
  lib/types/events/EventGenericDocument.ts
  lib/types/index.ts
Labels: changelog:enhancements

#2384 Bump koncorde version to 4.0.3
  package-lock.json
  package.json
Labels: changelog:enhancements

#2385 Release 2.19.4
  doc/2/framework/abstract-classes/plugin/properties/index.md
  doc/2/framework/classes/backend-cluster/off/index.md
  doc/2/framework/classes/backend-cluster/on/index.md
  doc/2/framework/classes/backend-cluster/once/index.md
  doc/2/framework/classes/backend-hook/register/index.md
  doc/2/framework/classes/backend-pipe/register/index.md
  doc/2/framework/types/event-handler/index.md
  docker/scripts/start-kuzzle-dev.ts
  features/PluginEvents.feature
  lib/api/request/kuzzleRequest.ts
  lib/core/backend/backend.ts
  lib/core/backend/backendCluster.ts
  lib/core/backend/backendHook.ts
  lib/core/backend/backendPipe.ts
  lib/kuzzle/event/pipeRunner.js
  lib/types/EventHandler.ts
  lib/types/Plugin.ts
  lib/types/events/EventGenericDocument.ts
  lib/types/index.ts
  package-lock.json
  package.json
Labels: release

#2386 HOTFIX: Deprecate EventHandler
  lib/types/EventHandler.ts
  package-lock.json
  package.json
Labels: changelog:bug-fixes

#2388 Add eslint-plugin-kuzzle
  README.md
  package-lock.json
  package.json
Labels: changelog:exclude
