Repository kuzzleio/kuzzle, pull requests merged in 2022-01, with the labels that each got.

#2175 Add types for the configuration object
  bin/.upgrades/lib/context.js
  features-legacy/support/config.js
  features-legacy/support/world.js
  features/support/world.js
  lib/config/default.config.ts
  lib/config/index.js
  lib/core/backend/backendConfig.ts
  lib/kuzzle/kuzzle.ts
  lib/types/PasswordPolicy.ts
  lib/types/Plugin.ts
  lib/types/ProfileDefinition.ts
  lib/types/RoleDefinition.ts
  lib/types/config/DumpConfiguration.ts
  lib/types/config/HttpConfiguration.ts
  lib/types/config/KuzzleConfiguration.ts
  lib/types/config/LimitsConfiguration.ts
  lib/types/config/PluginsConfiguration.ts
  lib/types/config/SecurityConfiguration.ts
  lib/types/config/ServerConfiguration.ts
  lib/types/config/ServicesConfiguration.ts
  lib/types/config/StorageService/StorageServiceElasticsearchConfiguration.ts
  lib/types/config/internalCache/InternalCacheRedisConfiguration.ts
  lib/types/config/publicCache/PublicCacheRedisConfiguration.ts
  lib/types/index.ts
  package-lock.json
  test/config/index.test.js
  test/kuzzle/kuzzle.test.js
  test/mocks/kuzzle.mock.js
Labels: changelog:enhancements

#2239 Revert `collection:truncate` behavior
  doc/2/api/controllers/collection/truncate/index.md
  lib/api/controllers/collectionController.js
  package-lock.json
  package.json
  test/api/controllers/collectionController.test.js
Labels: changelog:bug-fixes

#2229 Better error on invalid role profile
  lib/model/security/profile.js
  lib/model/security/role.js
  test/model/security/profile.test.js
Labels: changelog:enhancements

#2249 Add a keepalive for Redis
  .kuzzlerc.sample
  lib/service/cache/redis.js
  test/service/cache/redis.test.js
Labels: changelog:bug-fixes

#2240 Anonymous token if we have no token
  lib/api/controllers/authController.js
  test/api/controllers/authController.test.js
Labels: changelog:exclude, 2.x

#2251 Release 2.16.8
  .kuzzlerc.sample
  bin/.upgrades/lib/context.js
  features-legacy/support/config.js
  features-legacy/support/world.js
  features/support/world.js
  lib/api/controllers/authController.js
  lib/config/default.config.ts
  lib/config/index.js
  lib/core/backend/backendConfig.ts
  lib/kuzzle/kuzzle.ts
  lib/model/security/profile.js
  lib/model/security/role.js
  lib/service/cache/redis.js
  lib/types/PasswordPolicy.ts
  lib/types/Plugin.ts
  lib/types/ProfileDefinition.ts
  lib/types/RoleDefinition.ts
  lib/types/config/DumpConfiguration.ts
  lib/types/config/HttpConfiguration.ts
  lib/types/config/KuzzleConfiguration.ts
  lib/types/config/LimitsConfiguration.ts
  lib/types/config/PluginsConfiguration.ts
  lib/types/config/SecurityConfiguration.ts
  lib/types/config/ServerConfiguration.ts
  lib/types/config/ServicesConfiguration.ts
  lib/types/config/StorageService/StorageServiceElasticsearchConfiguration.ts
  lib/types/config/internalCache/InternalCacheRedisConfiguration.ts
  lib/types/config/publicCache/PublicCacheRedisConfiguration.ts
  lib/types/index.ts
  package-lock.json
  package.json
  test/api/controllers/authController.test.js
  test/config/index.test.js
  test/kuzzle/kuzzle.test.js
  test/mocks/kuzzle.mock.js
  test/model/security/profile.test.js
  test/service/cache/redis.test.js
Labels: release

#2254 Check Redis service before usage in IdCardRenewer
  lib/cluster/workers/IDCardRenewer.js
  test/cluster/workers/IDCardRenewer.test.js
Labels: changelog:bug-fixes

#2253 Support M1 chip
  README.md
  docker-compose.yml
  package.json
Labels: changelog:enhancements, 2.x

#2237 Support lodash syntax in request argument extractors
  doc/2/framework/classes/kuzzle-request/get-body-array/index.md
  doc/2/framework/classes/kuzzle-request/get-body-boolean/index.md
  doc/2/framework/classes/kuzzle-request/get-body-integer/index.md
  doc/2/framework/classes/kuzzle-request/get-body-number/index.md
  doc/2/framework/classes/kuzzle-request/get-body-object/index.md
  doc/2/framework/classes/kuzzle-request/get-body-string/index.md
  doc/2/framework/classes/kuzzle-request/get-boolean/index.md
  doc/2/framework/classes/kuzzle-request/get-integer/index.md
  doc/2/framework/classes/kuzzle-request/get-number/index.md
  doc/2/framework/classes/kuzzle-request/get-object/index.md
  doc/2/framework/classes/kuzzle-request/get-string/index.md
  lib/api/request/kuzzleRequest.ts
  test/api/controllers/securityController/users.test.js
  test/api/request/request.test.js
Labels: changelog:enhancements, 2.x

#2256 Expose Kuzzle Node unique identifier and the Mutex class to the PluginContext
  .eslintignore
  .gitignore
  doc/2/framework/classes/plugin-context-accessors/properties/index.md
  doc/2/framework/classes/plugin-context-constructors/properties/index.md
  lib/core/plugin/pluginContext.ts
  test/core/plugin/context/context.test.js
Labels: changelog:new-features

#2259 Release 2.16.9
  .eslintignore
  .gitignore
  doc/2/framework/classes/kuzzle-request/get-body-array/index.md
  doc/2/framework/classes/kuzzle-request/get-body-boolean/index.md
  doc/2/framework/classes/kuzzle-request/get-body-integer/index.md
  doc/2/framework/classes/kuzzle-request/get-body-number/index.md
  doc/2/framework/classes/kuzzle-request/get-body-object/index.md
  doc/2/framework/classes/kuzzle-request/get-body-string/index.md
  doc/2/framework/classes/kuzzle-request/get-boolean/index.md
  doc/2/framework/classes/kuzzle-request/get-integer/index.md
  doc/2/framework/classes/kuzzle-request/get-number/index.md
  doc/2/framework/classes/kuzzle-request/get-object/index.md
  doc/2/framework/classes/kuzzle-request/get-string/index.md
  doc/2/framework/classes/plugin-context-accessors/properties/index.md
  doc/2/framework/classes/plugin-context-constructors/properties/index.md
  lib/api/controllers/adminController.js
  lib/api/request/kuzzleRequest.ts
  lib/cluster/workers/IDCardRenewer.js
  lib/core/plugin/pluginContext.ts
  lib/core/security/securityLoader.js
  lib/core/shared/repository.js
  package-lock.json
  package.json
  test/api/controllers/adminController.test.js
  test/api/controllers/securityController/users.test.js
  test/api/request/request.test.js
  test/cluster/workers/IDCardRenewer.test.js
  test/core/plugin/context/context.test.js
Labels: release

#2258 Write openapi doc for document:validate
  lib/api/httpRoutes.js
  lib/api/openApiGenerator.ts
  lib/api/openapi/document/index.ts
  lib/api/openapi/document/validate.yaml
Labels: changelog:complements

#2260 Document checkToken behaviour when no token is given
  doc/2/api/controllers/auth/check-token/index.md
Labels: changelog:exclude
