Repository kuzzleio/kuzzle, pull requests merged in 2023-10, with the labels that each got.

#2483 Update uwebsocket to 20.32.0
  package.json
Labels: changelog:enhancements

#2484 Release 2.26.3
  package-lock.json
  package.json
Labels: release

#2487 Enhance websocket options and documentation
  .kuzzlerc.sample.jsonc
  config/.keep
  doc/2/api/protocols/websocket/index.md
  doc/2/guides/advanced/cluster-scalability/index.md
  doc/2/guides/advanced/configuration/index.md
  doc/2/guides/advanced/debugging/index.md
  docker/images/kuzzle/Dockerfile
  docker/images/plugin-dev/Dockerfile
  lib/config/default.config.ts
  lib/config/index.js
  lib/core/network/protocols/httpMessage.js
  lib/core/network/protocols/httpwsProtocol.js
  lib/types/config/ServerConfiguration.ts
  package-lock.json
  test/config/index.test.js
  test/core/network/protocols/http.test.js
  test/core/network/protocols/websocket.test.js
  test/kuzzle/kuzzlerc.test.js
Labels: changelog:enhancements

#2485 Add fields property to allowed fields
  doc/2/api/controllers/document/export/index.md
  doc/2/api/controllers/document/search/index.md
  doc/2/guides/main-concepts/querying/index.md
  lib/service/storage/elasticsearch.js
Labels: changelog:new-features

#2486 Update documentation about api keys
  doc/2/guides/advanced/api-keys/index.md
  doc/2/screenshots/api-key-check.png
  doc/2/screenshots/api-key-create.png
  doc/2/screenshots/api-key-delete.png
  doc/2/screenshots/api-key-search.png
Labels: changelog:exclude

#2488 Release 2.27.0
  .kuzzlerc.sample.jsonc
  config/.keep
  doc/2/api/controllers/document/export/index.md
  doc/2/api/controllers/document/search/index.md
  doc/2/api/protocols/websocket/index.md
  doc/2/guides/advanced/api-keys/index.md
  doc/2/guides/advanced/cluster-scalability/index.md
  doc/2/guides/advanced/configuration/index.md
  doc/2/guides/advanced/debugging/index.md
  doc/2/guides/main-concepts/querying/index.md
  doc/2/screenshots/api-key-check.png
  doc/2/screenshots/api-key-create.png
  doc/2/screenshots/api-key-delete.png
  doc/2/screenshots/api-key-search.png
  docker/images/kuzzle/Dockerfile
  docker/images/plugin-dev/Dockerfile
  lib/config/default.config.ts
  lib/config/index.js
  lib/core/network/protocols/httpMessage.js
  lib/core/network/protocols/httpwsProtocol.js
  lib/service/storage/elasticsearch.js
  lib/types/config/ServerConfiguration.ts
  package-lock.json
  package.json
  test/config/index.test.js
  test/core/network/protocols/http.test.js
  test/core/network/protocols/websocket.test.js
  test/kuzzle/kuzzlerc.test.js
Labels: release

#2490 Fix incorrect HTTP Content-Type headers being accepted
  lib/core/network/protocols/httpwsProtocol.js
  test/core/network/protocols/http.test.js
Labels: changelog:bug-fixes, 2.x

#2492 Release 2.27.1
  jest/api/controller/document/mCreate.test.ts
  lib/core/network/protocols/httpwsProtocol.js
  lib/service/storage/elasticsearch.js
  package-lock.json
  package.json
  test/core/network/protocols/http.test.js
Labels: release
