Repository kuzzleio/kuzzle, pull requests merged in 2023-11, with the labels that each got.

#2494 misc: change "Twitter" to "𝕏 (Twitter)" in README.md
  README.md
Labels: changelog:exclude

#2495 Update package.json
  package.json
Labels: changelog:bug-fixes

#2491 Update docker compose
  docker-compose.yml
  docker/nginx-dev/kuzzle.conf
  package-lock.json
Labels: changelog:enhancements, 2.x

#2497 Using docker compose instead of docker-compose in scripts
  .ci/haproxy/haproxy.cfg
  .ci/haproxy/snakeoil.pem
  .ci/privatebuild/.gitignore
  .ci/privatebuild/Dockerfile
  .ci/privatebuild/build.sh
  .ci/scripts/install-aarch64-deps.sh
  .ci/scripts/install-armhf-deps.sh
  .ci/scripts/install-plugins.sh
  .ci/scripts/run-monkey-tests.sh
  .ci/scripts/run-test-cluster.sh
  .ci/scripts/run-test.sh
  .ci/test-aarch64.yml
  .ci/test-armhf.yml
  .ci/test-cluster.yml
  .ci/test.yml
  .github/actions/build-and-run-kuzzle/action.yml
  .github/actions/dockerhub/action.yml
  .github/actions/es-lint/action.yml
  .github/actions/unit-tests/action.yml
  .github/workflows/workflow-deployments.yaml
  .github/workflows/workflow.yaml
  .gitignore
  CONTRIBUTING.md
  README.md
  doc/2/guides/getting-started/deploy-your-application/index.md
  doc/2/guides/getting-started/run-kuzzle/index.md
  docker/images/kuzzle/Dockerfile
  docker/images/kuzzle/README.md
  docker/images/plugin-dev/Dockerfile
  docker/scripts/run-plugin.sh
  docker/scripts/start-kuzzle-test.ts
  jest/api/controller/document/mCreate.test.ts
  jest/api/controller/document/metadata.test.ts
  jest/api/controller/document/search.test.ts
  package-lock.json
  package.json
  vagrant/kuzzle.sh
Labels: changelog:bug-fixes

#2498 Update index.md
  doc/2/guides/main-concepts/api/index.md
Labels: changelog:exclude
