Repository kuzzleio/kuzzle, pull requests merged in 2023-02, with the labels that each got.

#2432 Allow plugins to imports defaults (rights, users, mappings)
  doc/2/guides/write-plugins/plugins-features/index.md
  jest/helpers/useSdk.ts
  jest/plugins/default-imports.test.ts
  lib/core/plugin/plugin.js
  lib/core/plugin/pluginsManager.js
  lib/kuzzle/kuzzle.ts
  lib/types/Plugin.ts
  plugins/available/functional-test-plugin/functionalTestPlugin.js
Labels: changelog:enhancements

#2431 fix : Typo replace app by Backend
  doc/2/guides/develop-on-kuzzle/api-controllers/index.md
Labels: changelog:exclude

#2434 Allow to disable missing alias generation
  .kuzzlerc.sample
  lib/config/default.config.ts
  lib/core/storage/clientAdapter.js
  lib/service/storage/elasticsearch.js
  lib/types/config/storageEngine/StorageEngineElasticsearchConfiguration.ts
  package-lock.json
  package.json
  test/core/storage/clientAdapter.test.js
  test/service/storage/elasticsearch.test.js
Labels: changelog:bug-fixes

#2436 Release 2.21.0
  doc/2/api/controllers/debug/add-listener/index.md
  doc/2/api/controllers/debug/disable/index.md
  doc/2/api/controllers/debug/enable/index.md
  doc/2/api/controllers/debug/post/index.md
  doc/2/framework/events/generic-document/index.md
  doc/2/framework/events/http/index.md
  doc/2/framework/events/websocket/index.md
  doc/2/guides/advanced/debugging/index.md
  docker/scripts/start-kuzzle-dev.ts
  jest/api/controller/document/metadata.test.ts
  jest/plugins/default-imports.test.ts
  lib/api/controllers/debugController.ts
  lib/api/controllers/documentController.js
  lib/api/request/kuzzleRequest.ts
  lib/cluster/idCardHandler.ts
  lib/cluster/node.js
  lib/cluster/protobuf/sync.proto
  lib/cluster/publisher.js
  lib/cluster/subscriber.js
  lib/cluster/workers/IDCardRenewer.js
  lib/core/debug/kuzzleDebugger.ts
  lib/kuzzle/dumpGenerator.js
  lib/kuzzle/kuzzle.ts
  lib/service/storage/elasticsearch.js
  lib/types/DebugModule.ts
  lib/types/events/EventGenericDocument.ts
  package-lock.json
  package.json
  test/api/controllers/debugController.test.js
  test/api/controllers/documentController.test.js
  test/cluster/idCardHandler.test.js
  test/cluster/node.test.js
  test/cluster/subscriber.test.js
  test/cluster/workers/IDCardRenewer.test.js
  test/core/debug/kuzzleDebugger.test.js
  test/kuzzle/dumpGenerator.test.js
  test/mocks/child_process.mock.js
  test/mocks/debugModule.mock.js
  test/mocks/fs.mock.js
  test/mocks/worker.mock.js
Labels: release
