Repository kuzzleio/kuzzle, pull requests merged in 2023-09, with the labels that each got.

#2475 Doc/fix guides
  doc/2/guides/getting-started/run-kuzzle/index.md
  doc/2/guides/getting-started/set-up-permissions/index.md
  doc/2/guides/getting-started/store-and-access-data/data-storage-organization.8a731985.png
  doc/2/guides/getting-started/store-and-access-data/index.md
  doc/2/guides/getting-started/subscribe-realtime-notifications/index.md
Labels: changelog:exclude

#2477 Release 2.26.0
  .ci/danger.config.yaml
  .ci/scripts/run-monkey-tests.sh
  .ci/scripts/run-test-arm.sh
  .ci/scripts/run-test-cluster.sh
  .ci/scripts/run-test.sh
  .github/actions/install-packages/action.yml
  .github/workflows/workflow-deployments.yaml
  .github/workflows/workflow.yaml
  doc/2/api/controllers/auth/check-token/index.md
  doc/2/api/controllers/bulk/update-by-query/index.md
  doc/2/api/controllers/document/search/index.md
  doc/2/api/protocols/websocket/index.md
  doc/2/guides/getting-started/run-kuzzle/index.md
  doc/2/guides/getting-started/set-up-permissions/index.md
  doc/2/guides/getting-started/store-and-access-data/data-storage-organization.8a731985.png
  doc/2/guides/getting-started/store-and-access-data/index.md
  doc/2/guides/getting-started/subscribe-realtime-notifications/index.md
  docker-compose.yml
  docker/images/kuzzle/Dockerfile
  docker/images/plugin-dev/Dockerfile
  lib/core/network/protocols/httpwsProtocol.js
  package-lock.json
  package.json
  test/core/network/protocols/websocket.test.js
Labels: release

#2478 Multiple update of deps
  package-lock.json
  package.json
Labels: changelog:enhancements, 2.x

#2479 Release 2.26.1
  package-lock.json
  package.json
Labels: release

#2480 Update doco, scripts, dockerfile to nodejs 18
  .ci/scripts/run-monkey-tests.sh
  .ci/scripts/run-test-arm.sh
  .ci/scripts/run-test-cluster.sh
  .ci/scripts/run-test.sh
  doc/2/api/controllers/server/health-check/index.md
  docker-compose.yml
  docker/docker-compose-swarm.yml
  docker/images/kuzzle/Dockerfile
  docker/images/kuzzle/README.md
  docker/images/plugin-dev/Dockerfile
  docker/images/plugin-dev/README.md
  docker/scripts/docker-compose.test.yml
  docker/scripts/run-dev.sh
  docker/scripts/run-test.sh
Labels: changelog:enhancements

#2481 Update uWebsocket to his latest version available
  lib/core/network/protocols/httpMessage.js
  package-lock.json
  package.json
Labels: changelog:enhancements
