Repository kuzzleio/kuzzle, pull requests merged in 2023-01, with the labels that each got.

#2413 Bump segfault handler to 1.4.2
  package-lock.json
  package.json
  test/kuzzle/kuzzle.test.js
  test/mocks/node-segfault-handler.js
Labels: changelog:enhancements

#2423 Add action to generate single use token
  doc/2/api/controllers/auth/create-token/index.md
  doc/2/api/controllers/document/export/index.md
  doc/2/api/errors/error-codes/security/index.md
  docker-compose.yml
  features/AuthController.feature
  features/step_definitions/auth-steps.js
  lib/api/controllers/authController.ts
  lib/api/controllers/baseController.ts
  lib/api/httpRoutes.js
  lib/api/request/kuzzleRequest.ts
  lib/core/plugin/pluginRepository.js
  lib/core/security/index.js
  lib/core/security/profileRepository.ts
  lib/core/security/roleRepository.js
  lib/core/security/tokenRepository.ts
  lib/core/security/userRepository.js
  lib/core/shared/repository.ts
  lib/kerror/codes/7-security.json
  lib/model/security/token.ts
  lib/service/storage/elasticsearch.js
  package.json
  test/core/security/profileRepository.test.js
  test/core/security/roleRepository.test.js
  test/core/security/tokenRepository.test.js
  test/core/security/userRepository.test.js
  test/core/shared/repository.test.js
Labels: changelog:new-features

#2426 Allows to pass arguments for GET `document:export`
  doc/2/api/controllers/document/export/index.md
  features/DocumentController.feature
  features/step_definitions/documents-steps.js
  lib/api/controllers/documentController.js
  lib/api/request/kuzzleRequest.ts
Labels: changelog:enhancements

#2425 Remove duplicated Transfer-Encoding header
  .github/actions/unit-tests/action.yml
  .github/workflows/workflow.yaml
  docker/scripts/start-kuzzle-dev.ts
  jest.config.js
  jest/network/http/http-stream.test.ts
  lib/api/funnel.js
  lib/core/network/protocols/httpwsProtocol.js
  package-lock.json
  package.json
  test/core/network/protocols/http.test.js
Labels: changelog:bug-fixes

#2427 Release 2.20.1
  .github/actions/unit-tests/action.yml
  .github/workflows/workflow.yaml
  doc/2/api/controllers/document/export/index.md
  docker/scripts/start-kuzzle-dev.ts
  features/DocumentController.feature
  features/step_definitions/documents-steps.js
  jest.config.js
  jest/network/http/http-stream.test.ts
  lib/api/controllers/documentController.js
  lib/api/funnel.js
  lib/api/request/kuzzleRequest.ts
  lib/core/network/protocols/httpwsProtocol.js
  package-lock.json
  package.json
  test/core/network/protocols/http.test.js
Labels: release

#2428 fix : documentation typo
  doc/2/guides/main-concepts/querying/index.md
Labels: changelog:exclude

#2429 fix : Typo in getting started
  doc/2/guides/getting-started/run-kuzzle/index.md
Labels: changelog:exclude

#2430 Fix documentation dead link
  doc/2/api/controllers/document/export/index.md
Labels: changelog:exclude
