Repository kuzzleio/kuzzle, pull requests merged in 2023-05, with the labels that each got.

#2454 Update the readme with up to date informations
  README.md
Labels: changelog:exclude, 2.x

#2455 Add a new public _healthcheck route
  doc/2/guides/main-concepts/api/index.md
  jest/network/network/healthcheck.test.ts
  lib/core/network/router.js
  package-lock.json
  package.json
Labels: changelog:new-features, 2.x

#2457 fix(getting started): update node version to support 18
  doc/2/guides/getting-started/run-kuzzle/index.md
Labels: changelog:exclude, 2.x

#2458 Update main kuzzle docs
  doc/2/guides/introduction/general-purpose-backend/index.md
  doc/2/guides/introduction/what-is-kuzzle/index.md
Labels: changelog:exclude

#2459 Delete ID Card directly from Redis when Kuzzle is shutting down
  lib/cluster/idCardHandler.ts
  lib/cluster/workers/IDCardRenewer.js
Labels: changelog:enhancements

#2460 Fix document:search error response when index or collection are missing
  lib/api/controllers/documentController.js
  test/api/controllers/documentController.test.js
Labels: changelog:bug-fixes

#2463 Fix koncorde exists keyword translation to ES query
  doc/2/api/errors/error-codes/services/index.md
  jest/api/controller/document/search.test.ts
  lib/kerror/codes/1-services.json
  lib/service/storage/queryTranslator.js
Labels: changelog:bug-fixes

#2461 Add http protocol parameter additionalContentTypes
  .ci/test-cluster.yml
  .kuzzlerc.sample
  doc/2/api/protocols/http/index.md
  doc/2/guides/advanced/content-types/index.md
  docker/scripts/functional-tests-controller.ts
  docker/scripts/start-kuzzle-dev.ts
  jest/network/http/http-additional-content-types.test.ts
  lib/config/default.config.ts
  lib/config/index.js
  lib/core/network/protocols/httpwsProtocol.js
  lib/types/config/ServerConfiguration.ts
  test/config/index.test.js
  test/core/network/protocols/http.test.js
  test/core/network/protocols/websocket.test.js
Labels: changelog:new-features
