Repository kuzzleio/kuzzle, pull requests merged in 2023-03, with the labels that each got.

#2437 Overall improvement of the Debug Controller
  lib/api/controllers/debugController.ts
  lib/api/funnel.js
  lib/cluster/node.js
  lib/cluster/subscriber.js
  lib/cluster/workers/IDCardRenewer.js
  lib/core/debug/kuzzleDebugger.ts
  lib/core/network/clientConnection.js
  lib/core/network/protocols/httpwsProtocol.js
  lib/kuzzle/kuzzle.ts
  test/api/controllers/debugController.test.js
  test/core/debug/kuzzleDebugger.test.js
  test/mocks/kuzzle.mock.js
  test/mocks/uWS.mock.js
Labels: changelog:enhancements

#2438 Fix missing parameters in deployment workflow call
  .github/workflows/workflow-deployments.yaml
  .github/workflows/workflow.yaml
Labels: changelog:exclude

#2439 Release 2.21.1
  .github/workflows/workflow-deployments.yaml
  .github/workflows/workflow.yaml
  lib/api/controllers/debugController.ts
  lib/api/funnel.js
  lib/cluster/node.js
  lib/cluster/subscriber.js
  lib/cluster/workers/IDCardRenewer.js
  lib/core/debug/kuzzleDebugger.ts
  lib/core/network/clientConnection.js
  lib/core/network/protocols/httpwsProtocol.js
  lib/kuzzle/kuzzle.ts
  package-lock.json
  package.json
  test/api/controllers/debugController.test.js
  test/core/debug/kuzzleDebugger.test.js
  test/mocks/kuzzle.mock.js
  test/mocks/uWS.mock.js
Labels: release

#2440 Allows to register realtime subscriptions from the backend
  doc/2/framework/classes/backend-subscription/add/index.md
  doc/2/framework/classes/backend-subscription/index.md
  doc/2/framework/classes/backend-subscription/properties/index.md
  doc/2/framework/classes/backend-subscription/remove/index.md
  doc/2/framework/classes/backend/properties/index.md
  doc/2/guides/main-concepts/realtime-engine/index.md
  docker/scripts/start-kuzzle-dev.ts
  lib/core/backend/backend.ts
  lib/core/backend/backendSubscription.ts
  lib/core/backend/index.ts
  package-lock.json
Labels: changelog:new-features

#2441 Release 2.22.0
  doc/2/framework/classes/backend-subscription/add/index.md
  doc/2/framework/classes/backend-subscription/index.md
  doc/2/framework/classes/backend-subscription/properties/index.md
  doc/2/framework/classes/backend-subscription/remove/index.md
  doc/2/framework/classes/backend/properties/index.md
  doc/2/guides/main-concepts/realtime-engine/index.md
  docker/scripts/start-kuzzle-dev.ts
  lib/core/backend/backend.ts
  lib/core/backend/backendSubscription.ts
  lib/core/backend/index.ts
  package-lock.json
  package.json
Labels: release
